'use strict';
const App={
  data:{clubs:[],leagues:[],players:[],trophies:[],events:[]},player:null,route:'home',creation:null,monthContext:null,
  async init(){UI.init();try{const [clubData,players,trophies,events]=await Promise.all([fetch('data/clubs.json').then(r=>r.json()),fetch('data/players.json').then(r=>r.json()),fetch('data/trophies.json').then(r=>r.json()),fetch('data/events.json').then(r=>r.json())]);this.data={clubs:clubData.clubs,leagues:clubData.leagues,players,trophies,events};document.querySelector('#boot').remove();document.querySelector('#app').hidden=false;this.showWelcome()}catch(err){document.querySelector('#boot').innerHTML=`<div class="boot-mark">!</div><b>载入失败</b><span>${U.esc(err.message)}</span>`;console.error(err)}},
  club(id){return this.data.clubs.find(c=>c.id===id)||this.data.clubs[0]},
  showWelcome(){this.player=null;this.route='welcome';UI.renderWelcome()},
  navigate(route){if(!this.player)return this.showWelcome();this.route=route;this.render()},
  render(){const map={home:'renderHome',career:'renderCareer',world:'renderWorld',honours:'renderHonours',profile:'renderProfile'};UI[map[this.route]||'renderHome']()},
  startCreation(){this.creation={name:'许一信',nationality:'中国',position:'ST',seed:`career-${Math.floor(Math.random()*999999)}`,roll:0,candidate:null};this.rollCandidate();UI.renderCreation()},
  rollCandidate(){this.creation.candidate=Engine.randomCandidate(this.creation)},
  randomName(nation){const names={中国:['许一信','林宇辰','陈嘉豪','吴龙飞','赵天佑','顾明远','周启航','陆子轩'],日本:['佐藤蓮','高桥悠真','伊藤海斗','中村苍'],韩国:['金志勋','李贤宇','朴俊浩','崔敏宰'],法国:['Lucas Martin','Noah Dubois','Hugo Bernard'],英格兰:['Ethan Cole','Leo Bennett','Jack Turner'],西班牙:['Álex Romero','Iker Navarro','Mateo García'],德国:['Jonas Keller','Lukas Brandt','Felix Wagner'],意大利:['Luca Romano','Matteo Ricci','Andrea Conti'],巴西:['Gabriel Santos','João Lima','Matheus Costa'],阿根廷:['Thiago López','Mateo Fernández','Nicolás Ruiz'],荷兰:['Daan de Jong','Sem van Dijk','Milan Bakker'],尼日利亚:['Chinedu Okafor','Tobi Adeyemi','Samuel Eze'],塞内加尔:['Moussa Ndiaye','Ibrahima Fall','Saliou Diop']};const a=names[nation]||names.中国;return U.pick(a,U.rng(this.creation.seed+'name'+this.creation.roll))},
  beginCareer(){const name=(document.querySelector('#nameInput')?.value||this.creation.name).trim();this.creation.name=name||this.creation.name;this.player=Engine.createPlayer(this.creation,this.creation.candidate,this.data);Store.save(this.player);this.route='home';this.render();UI.toast('职业生涯开始')},
  load(id){const p=Store.saves().find(x=>x.id===id);if(!p)return;this.player=p;this.route='home';this.render()},
  async startMonth(){if(!this.player||this.monthContext)return;if(this.player.monthlyQueue?.length&&this.player.pendingMonth){this.monthContext=this.player.pendingMonth;const ev=this.data.events.find(e=>e.id===this.player.monthlyQueue[0]);const step=this.monthContext.total-this.player.monthlyQueue.length+1;UI.showEvent(ev,step,this.monthContext.total);return}const before={ovr:this.player.ovr,attrs:{...this.player.attrs}};const games=Engine.simulateMonth(this.player,this.data);const queue=Engine.prepareEvents(this.player,this.data.events);this.monthContext={before,games,total:queue.length};this.player.pendingMonth=this.monthContext;Store.save(this.player);if(queue.length){const ev=this.data.events.find(e=>e.id===queue[0]);UI.showEvent(ev,1,queue.length)}else UI.showMonthSummary(games,before)},
  async resolveChoice(event,index,step,total){const choice=event.choices[index];await UI.showDraw();const outcome=Engine.pickOutcome(this.player,event,choice);const effects=Engine.applyEvent(this.player,event,choice,outcome);Store.save(this.player);UI.showResult(event,choice,outcome,effects,step,total)},
  nextMonthStep(step,total){if(this.player.monthlyQueue.length){const ev=this.data.events.find(e=>e.id===this.player.monthlyQueue[0]);const next=total-this.player.monthlyQueue.length+1;UI.showEvent(ev,next,total)}else UI.showMonthSummary(this.monthContext.games,this.monthContext.before)},
  finishMonth(){delete this.player.pendingMonth;Store.save(this.player);this.monthContext=null;this.route='home';this.render()},
  exportSave(){const blob=new Blob([JSON.stringify(this.player,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${this.player.name}-career-v9.json`;a.click();URL.revokeObjectURL(a.href)},
  retire(){if(!confirm('确定结束当前生涯并保存永久退役档案？'))return;this.player.careerEnded=true;this.player.timeline.unshift({icon:'🏁',title:'宣布退役',text:'职业球员生涯结束，档案永久保存。',date:`${this.player.year}/${this.player.month}`});Store.archive({...this.player,retiredAt:Date.now()});UI.toast('退役档案已保存');setTimeout(()=>this.showWelcome(),800)}
};
window.addEventListener('DOMContentLoaded',()=>App.init());
