'use strict';

const VERSION='8.0.0';
const SAVE_KEY='pitchlife_v8_saves';
const ARCHIVE_KEY='pitchlife_v8_archives';
const MEDIA_KEY='pitchlife_v8_media';
const ATTRS=['pac','sho','pas','dri','def','phy'];
const ATTR_CN={pac:'速度',sho:'射门',pas:'传球',dri:'盘带',def:'防守',phy:'身体'};
const POSITIONS={ST:'中锋',LW:'左边锋',RW:'右边锋',CAM:'前腰',CM:'中前卫',CDM:'后腰',LB:'左后卫',CB:'中后卫',RB:'右后卫',GK:'门将'};
const NAV=[['home','⌂','主页'],['career','◫','生涯'],['world','◎','世界'],['honours','♛','荣誉'],['profile','◉','档案']];
const ROLE_CHANCE={'核心':.96,'主力':.86,'轮换':.58,'替补':.28,'预备队':.10,'青年队':.15,'未进名单':.02};
const ROLE_COLOR={'核心':'gold','主力':'green','轮换':'blue','替补':'orange','预备队':'muted','青年队':'muted','未进名单':'red'};

let DATA={clubs:[],leagues:[],players:[],trophies:[]};
let CLUB_BY_ID={},PLAYERS_BY_CLUB={};
let saves=[],archives=[],state=null,route='home',creation=null;
let EVENT_LIBRARY=[];
const app=document.querySelector('#app'),boot=document.querySelector('#boot'),view=document.querySelector('#view'),topbar=document.querySelector('#topbar'),nav=document.querySelector('#nav');
const sheet=document.querySelector('#sheet'),sheetBody=document.querySelector('#sheetBody'),eventDialog=document.querySelector('#eventDialog'),eventBody=document.querySelector('#eventBody'),toastEl=document.querySelector('#toast');

const storage={
 get(k,fallback){try{const v=localStorage.getItem(k);return v?JSON.parse(v):fallback}catch{return fallback}},
 set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){console.warn('save failed',e)}}
};
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0))}
function hashString(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296}}
function rngFor(seed,salt=''){return mulberry32(hashString(`${seed}|${salt}`))}
function pick(arr,r=Math.random){return arr[Math.floor(r()*arr.length)]}
function money(n){n=Number(n)||0;if(n>=1e8)return `€${(n/1e8).toFixed(1)}亿`;if(n>=1e4)return `€${(n/1e4).toFixed(n>=1e5?0:1)}万`;return `€${Math.round(n)}`}
function seasonLabel(y){return `${y}/${String(y+1).slice(-2)}`}
function toast(text){toastEl.textContent=text;toastEl.classList.add('show');clearTimeout(toastEl._t);toastEl._t=setTimeout(()=>toastEl.classList.remove('show'),2100)}
function facePath(seed){const i=hashString(seed)%48;return `assets/faces/face_${String(i).padStart(2,'0')}.${i<24?'png':'webp'}`}
function faceRemote(seed){return `https://randomuser.me/api/portraits/men/${hashString(seed)%100}.jpg`}
function faceHTML(seed,cls='',alt='虚构球员头像'){const fallback=facePath(seed);return `<img class="${cls}" src="${faceRemote(seed)}" data-wiki="" data-fallback="${fallback}" alt="${esc(alt)}">`}
function fallbackTrophy(i){return `assets/trophies/trophy_${String(i%10).padStart(2,'0')}.png`}
function saveAll(){storage.set(SAVE_KEY,saves);storage.set(ARCHIVE_KEY,archives)}
function saveState(){if(!state)return;const i=saves.findIndex(s=>s.id===state.id);if(i>=0)saves[i]=state;else saves.unshift(state);saves=saves.slice(0,20);saveAll();syncHeader()}
function club(id){return CLUB_BY_ID[id]||DATA.clubs[0]}
function clubPlayers(id){return PLAYERS_BY_CLUB[id]||[]}
function realPlayer(idOrName){return DATA.players.find(p=>p.name===idOrName||p.cn===idOrName)}
function wikiThumbHTML(wiki,fallback,cls='',alt=''){return `<img class="${cls}" src="${fallback}" data-wiki="${esc(wiki||'')}" data-fallback="${fallback}" alt="${esc(alt)}">`}
function badgeFallback(c){const h=hashString(c.code||c.id)%360;return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="hsl(${h} 70% 54%)"/><stop offset="1" stop-color="hsl(${(h+70)%360} 60% 30%)"/></linearGradient></defs><path d="M50 4 88 18v31c0 25-15 40-38 47C27 89 12 74 12 49V18z" fill="url(#g)" stroke="white" stroke-width="4"/><text x="50" y="57" fill="white" font-family="Arial" font-size="25" font-weight="900" text-anchor="middle">${esc(c.code||'FC')}</text></svg>`)}`}
function crestHTML(c,cls=''){const fallback=badgeFallback(c);if(c.crest)return `<img class="${cls}" src="https://crests.football-data.org/${c.crest}.png" data-wiki="${esc(c.wiki||c.native)}" data-fallback="${fallback}" alt="${esc(c.cn)}队徽">`;return wikiThumbHTML(c.wiki||c.native,fallback,cls,`${c.cn}队徽`)}
async function hydrateMedia(root=document){
 const cache=storage.get(MEDIA_KEY,{});const imgs=[...root.querySelectorAll('img[data-wiki]')];
 const unique=[...new Set(imgs.map(i=>i.dataset.wiki).filter(Boolean))];
 for(const title of unique){
   let src=cache[title];
   if(!src){
     try{const res=await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`);if(res.ok){const j=await res.json();src=j.thumbnail?.source||j.originalimage?.source||'';if(src){cache[title]=src;storage.set(MEDIA_KEY,cache)}}}catch{}
   }
   if(src)imgs.filter(i=>i.dataset.wiki===title).forEach(i=>{i.src=src});
 }
 imgs.forEach(img=>img.addEventListener('error',()=>{if(img.src!==img.dataset.fallback)img.src=img.dataset.fallback},{once:true}));
}
function radarSVG(attrs,cls='radar-svg'){
 const cx=110,cy=110,r=76,vals=ATTRS.map(k=>clamp(attrs[k],1,99));
 const point=(i,m=1)=>{const a=-Math.PI/2+i*Math.PI/3;return [cx+Math.cos(a)*r*m,cy+Math.sin(a)*r*m]};
 const grid=[.25,.5,.75,1].map(m=>`<polygon points="${ATTRS.map((_,i)=>point(i,m).join(',')).join(' ')}" fill="none" stroke="currentColor" opacity=".11"/>`).join('');
 const axes=ATTRS.map((_,i)=>{const [x,y]=point(i);return `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="currentColor" opacity=".1"/>`}).join('');
 const poly=vals.map((v,i)=>point(i,v/99).join(',')).join(' ');
 const labels=ATTRS.map((k,i)=>{const [x,y]=point(i,1.22);return `<text x="${x}" y="${y+3}" text-anchor="middle" fill="currentColor" opacity=".68" font-size="9">${ATTR_CN[k]} ${vals[i]}</text>`}).join('');
 return `<svg class="${cls}" viewBox="0 0 220 220">${grid}${axes}<polygon points="${poly}" fill="rgba(0,122,255,.18)" stroke="#007aff" stroke-width="3"/>${vals.map((v,i)=>{const [x,y]=point(i,v/99);return `<circle cx="${x}" cy="${y}" r="3.7" fill="#007aff"/>`}).join('')}${labels}</svg>`
}

function buildEventLibrary(){
 const categories=[
  {id:'coach',label:'教练关系',icon:'⌁',color:'#007aff',base:'主教练在训练基地单独叫住了你',a:['认真听取并执行','坦率说明自己的想法'],fx1:{coachFavor:4,professionalism:2},fx2:{morale:3,reputation:1}},
  {id:'selection',label:'阵容竞争',icon:'◫',color:'#ff9f0a',base:'同位置竞争者近期状态出色，你的出场顺位正在变化',a:['接受轮换并等待机会','要求教练给出明确承诺'],fx1:{coachFavor:2,form:2},fx2:{coachFavor:-3,ambition:4}},
  {id:'teammate',label:'更衣室',icon:'◎',color:'#34c759',base:'一名资深队友对你的处理球方式提出了意见',a:['主动沟通并请教','在训练中用表现回应'],fx1:{relations:4,professionalism:2},fx2:{form:3,relations:-1}},
  {id:'agent',label:'经纪团队',icon:'◇',color:'#af52de',base:'经纪人带来一份关于你未来路线的新评估',a:['优先考虑竞技空间','优先考虑合同待遇'],fx1:{ambition:3,reputation:1},fx2:{money:12000,coachFavor:-1}},
  {id:'media',label:'媒体舆论',icon:'◌',color:'#ff3b30',base:'一段关于你的报道突然冲上当地体育新闻首页',a:['发布克制的公开回应','保持沉默让比赛说话'],fx1:{reputation:3,morale:-1},fx2:{professionalism:2,followers:800}},
  {id:'family',label:'家庭生活',icon:'♡',color:'#ff2d55',base:'家人希望你在密集赛程中抽出时间处理一件重要事情',a:['回家陪伴家人','留在基地完成恢复'],fx1:{morale:5,fitness:-3},fx2:{fitness:5,morale:-2}},
  {id:'injury',label:'身体状态',icon:'＋',color:'#ff453a',base:'医疗组发现你的身体指标出现了一些异常',a:['立即接受保守治疗','降低负荷继续随队'],fx1:{fitness:8,form:-2},fx2:{fitness:-5,coachFavor:2}},
  {id:'training',label:'个人训练',icon:'↗',color:'#30b0c7',base:'训练师为你设计了一套额外的专项计划',a:['完成高强度加练','只做恢复和技术细节'],fx1:{growth:3,fitness:-7},fx2:{growth:1,fitness:5}},
  {id:'contract',label:'合同进展',icon:'✎',color:'#5856d6',base:'俱乐部管理层更新了对你合同价值的内部判断',a:['授权经纪人启动谈判','暂缓谈判专注赛季'],fx1:{salaryBoost:1,coachFavor:-1},fx2:{form:2,professionalism:2}},
  {id:'loan',label:'租借抉择',icon:'⇄',color:'#0a84ff',base:'一家能够提供更多出场时间的俱乐部正式询问你的情况',a:['接受租借寻找比赛','留队继续争夺位置'],fx1:{loanInterest:4,ambition:2},fx2:{coachFavor:2,morale:-1}},
  {id:'transfer',label:'转会市场',icon:'✈',color:'#5e5ce6',base:'球探部门确认另一家俱乐部正在持续观察你',a:['让经纪人保持接触','明确表示本赛季不离队'],fx1:{transferInterest:5,reputation:2},fx2:{coachFavor:4,transferInterest:-2}},
  {id:'national',label:'国家队',icon:'⚑',color:'#32d74b',base:'国家队工作人员向俱乐部询问了你的近期状态',a:['公开表达为国出战愿望','不回应并继续证明自己'],fx1:{nationalRep:4,reputation:2},fx2:{professionalism:2,form:2}},
  {id:'fans',label:'球迷关系',icon:'♥',color:'#ff375f',base:'支持者组织邀请你参加一次公开活动',a:['参加活动与球迷交流','婉拒活动保护休息'],fx1:{followers:2400,fitness:-2},fx2:{fitness:4,reputation:-1}},
  {id:'finance',label:'财富管理',icon:'€',color:'#ffcc00',base:'财务顾问提交了一项与你场外收入有关的方案',a:['选择稳健长期安排','接受高回报高风险方案'],fx1:{money:18000,professionalism:1},fx2:{money:40000,morale:-2}},
  {id:'lifestyle',label:'场外生活',icon:'⌂',color:'#bf5af2',base:'你在休息日收到一个会占用大量时间的私人邀请',a:['参加并扩大社交圈','拒绝并保持职业节奏'],fx1:{followers:1300,fitness:-3},fx2:{professionalism:3,fitness:3}},
  {id:'leadership',label:'队内责任',icon:'♜',color:'#ff9f0a',base:'球队需要有人在困难时期站出来承担责任',a:['主动发言并鼓励队友','保持低调专注个人任务'],fx1:{leadership:4,relations:2},fx2:{form:2,leadership:-1}},
  {id:'culture',label:'海外适应',icon:'🌐',color:'#64d2ff',base:'新的语言和生活习惯开始影响你的日常状态',a:['报名语言课程主动融入','把注意力全部放在足球'],fx1:{adaptability:4,money:-3000},fx2:{form:2,relations:-2}},
  {id:'ethics',label:'职业原则',icon:'⚖',color:'#8e8e93',base:'有人向你提出一项不完全透明但看起来很有利的安排',a:['拒绝并报告俱乐部','保持距离但不公开'],fx1:{integrity:5,reputation:1},fx2:{integrity:1,morale:1}}
 ];
 const situations=['季前集训刚刚结束','连续客场让所有人疲惫','转会窗口即将关闭','球队刚经历一场失利','你连续两场没有出场','你刚刚打出高评分','队内伤病突然增加','一场关键德比即将到来','赛季目标面临压力','青年队新人被提拔到一线队'];
 const tones=[['私下会谈','对方希望事情不要被媒体知道'],['公开关注','这件事已经被部分记者注意到'],['时间紧迫','你必须在今天给出答复'],['关系复杂','不同利益方给出了完全相反的建议'],['机会难得','这样的窗口可能不会很快再次出现']];
 const stakes=[['稳妥','风险较低，但收益有限'],['积极','可能加速成长，也可能引发压力'],['强硬','能够表达立场，但会影响部分关系'],['长期','短期变化不大，结果会在未来体现']];
 const pool=[];
 categories.forEach((cat,ci)=>situations.forEach((sit,si)=>tones.forEach((tone,ti)=>stakes.forEach((stake,ki)=>{
   pool.push({id:`${cat.id}-${si}-${ti}-${ki}`,cat,si,ti,ki,title:`${cat.label}：${tone[0]} · ${stake[0]}路线`,body:`${sit}。${cat.base}。${tone[1]}；${stake[1]}。你的身份、出场顺位与职业阶段都会改变后续结果。`,choices:[
     {label:cat.a[0],sub:`选择更偏向${stake[0]}的处理方式`,effect:cat.fx1},
     {label:cat.a[1],sub:`保留另一条职业路径`,effect:cat.fx2}
   ]})
 }))));
 return pool;
}

async function init(){
 try{
  const [clubs,players,trophies]=await Promise.all([fetch('data/clubs.json').then(r=>r.json()),fetch('data/players.json').then(r=>r.json()),fetch('data/trophies.json').then(r=>r.json())]);
  DATA={...clubs,players,trophies};
  CLUB_BY_ID=Object.fromEntries(DATA.clubs.map(c=>[c.id,c]));
  PLAYERS_BY_CLUB=DATA.players.reduce((a,p)=>((a[p.clubId]??=[]).push(p),a),{});
  EVENT_LIBRARY=buildEventLibrary();
  saves=storage.get(SAVE_KEY,[]);archives=storage.get(ARCHIVE_KEY,[]);
  boot.remove();app.hidden=false;bindGlobal();renderWelcome();
 }catch(e){boot.innerHTML=`<div class="boot-ball">!</div><b>载入失败</b><span>${esc(e.message)}</span>`;console.error(e)}
}
function bindGlobal(){
 document.querySelector('.sheet-close').addEventListener('click',()=>sheet.close());
 sheet.addEventListener('click',e=>{if(e.target===sheet)sheet.close()});
 nav.addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(b){route=b.dataset.route;renderApp()}});
 topbar.addEventListener('click',e=>{if(e.target.closest('[data-menu]'))openSettings();if(e.target.closest('[data-brand]')){route='home';renderApp()}});
}
function syncHeader(){
 if(!state)return;
 const c=club(state.clubId);
 topbar.innerHTML=`<button class="brand" data-brand><span class="brand-icon">⚽</span><span class="brand-copy"><b>绿茵浮沉</b><small>CAREER 8.0</small></span></button><div class="top-player"><span class="top-stat"><small>年龄</small><b>${state.age}</b></span><span class="top-stat"><small>OVR</small><b>${state.ovr}</b></span><button class="round-btn" data-menu>•••</button></div>`;
 nav.innerHTML=NAV.map(([id,icon,label])=>`<button data-route="${id}" class="${route===id?'active':''}"><span>${icon}</span>${label}</button>`).join('');
}
function renderWelcome(){state=null;route='home';topbar.innerHTML=`<button class="brand"><span class="brand-icon">⚽</span><span class="brand-copy"><b>绿茵浮沉</b><small>PLAYER LIFE 8.0</small></span></button><button class="round-btn" id="welcomeHelp">?</button>`;nav.innerHTML='';
 view.innerHTML=`<section class="screen welcome"><div class="welcome-hero card"><div class="welcome-copy"><div class="eyebrow">PLAYER LIFE SIMULATION</div><h1>不是踢一场球<br>是走完一生。</h1><p>比赛自动模拟。你面对的是青训、替补席、教练信任、租借、合同、伤病、转会、国家队、荣誉与退役后的永久档案。</p><div class="welcome-actions"><button class="primary green-bg" id="newCareer">创建球员</button>${saves.length?'<button class="secondary" id="continueCareer">继续最近生涯</button>':''}</div></div></div><aside class="welcome-side card"><div><div class="label">生涯存档</div><h2>每个人，都有不同的路</h2></div><div class="save-list">${saves.length?saves.map(saveRow).join(''):'<div class="subtle-card" style="padding:18px;text-align:center;color:var(--muted);font-size:12px">还没有存档。创建一名球员开始。</div>'}</div><div class="welcome-meta"><span>${DATA.clubs.length} 家真实俱乐部</span><span>${DATA.leagues.length} 个联赛</span><span>${EVENT_LIBRARY.length} 个事件组合</span></div></aside></section>`;
 document.querySelector('#newCareer').onclick=startCreation;document.querySelector('#continueCareer')?.addEventListener('click',()=>loadCareer(saves[0].id));document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>loadCareer(b.dataset.save));document.querySelector('#welcomeHelp').onclick=()=>openSheet('玩法说明',`<p class="intro">核心规则</p><div class="timeline"><div class="timeline-item"><i>1</i><div><b>比赛自动模拟</b><p>你不需要逐次选择射门或传球，系统根据能力、状态、对手与队内顺位计算结果。</p></div></div><div class="timeline-item"><i>2</i><div><b>现实出场逻辑</b><p>能力不足会落选名单、坐替补、下放预备队或被租借。</p></div></div><div class="timeline-item"><i>3</i><div><b>事件不重复</b><p>每个存档拥有独立事件历史，同一事件组合不会在该生涯中再次出现。</p></div></div></div>`);hydrateMedia(view)}
function saveRow(s){const c=club(s.clubId);return `<button class="save-row" data-save="${s.id}">${s.photoWiki?wikiThumbHTML(s.photoWiki,facePath(s.faceSeed),'',s.name):faceHTML(s.faceSeed,'',s.name)}<span><b>${esc(s.name)}</b><small>${s.age}岁 · ${c.cn} · ${POSITIONS[s.position]} · ${seasonLabel(s.season)}</small></span><em>${s.ovr}</em></button>`}
function loadCareer(id){state=saves.find(s=>s.id===id)||null;if(!state)return;state.seenEvents??=[];state.feed??=[];state.timeline??=[];state.honours??=[];route='home';renderApp()}

function startCreation(){
 const seed=`${Date.now().toString(36)}-${Math.floor(Math.random()*1e6).toString(36)}`;
 creation={seed,draw:0,name:'',nationality:'中国',position:'ST',candidate:null,clubId:null};rollCandidate();renderCreation();
}
function calculateOVR(attrs,pos){const W={ST:[.17,.34,.11,.18,.03,.17],LW:[.27,.20,.14,.28,.02,.09],RW:[.27,.20,.14,.28,.02,.09],CAM:[.12,.16,.30,.29,.03,.10],CM:[.10,.10,.30,.22,.13,.15],CDM:[.08,.04,.23,.14,.30,.21],LB:[.20,.04,.16,.14,.27,.19],RB:[.20,.04,.16,.14,.27,.19],CB:[.08,.02,.12,.06,.42,.30],GK:[.04,.02,.12,.06,.50,.26]}[pos];return Math.round(ATTRS.reduce((n,k,i)=>n+attrs[k]*W[i],0))}
function rollCandidate(){const r=rngFor(creation.seed,`${creation.draw}-${creation.position}-${creation.nationality}`);const base=49+Math.floor(r()*16);const attrs={};ATTRS.forEach(k=>attrs[k]=clamp(base-7+Math.floor(r()*17),31,75));const focus={ST:['sho','phy'],LW:['pac','dri'],RW:['pac','dri'],CAM:['pas','dri'],CM:['pas','phy'],CDM:['def','phy'],LB:['pac','def'],RB:['pac','def'],CB:['def','phy'],GK:['def','phy']}[creation.position];focus.forEach(k=>attrs[k]=clamp(attrs[k]+6+Math.floor(r()*6),40,79));const ovr=calculateOVR(attrs,creation.position);const pot=clamp(ovr+14+Math.floor(r()*21),74,95);const traits=['爆发型','沉着型','创造型','对抗型','大器晚成','训练狂人','大场面球员','多位置适应','左脚天才','领袖气质'];creation.candidate={attrs,ovr,potential:pot,trait:pick(traits,r),professionalism:40+Math.floor(r()*55),adaptability:35+Math.floor(r()*60),bigGame:35+Math.floor(r()*60),injuryRisk:12+Math.floor(r()*58),weakFoot:2+Math.floor(r()*4),skillMoves:2+Math.floor(r()*4),faceSeed:`${creation.seed}-${creation.draw}`};creation.clubId=startingOffers()[0]?.id}
function startingOffers(){const c=creation.candidate;const countryLeagues={'中国':['CHN2','CHN1'],'日本':['JPN2','JPN1'],'韩国':['KOR1'],'西班牙':['ESP2'],'英格兰':['ENG2'],'德国':['GER2'],'意大利':['ITA2'],'法国':['FRA2'],'巴西':['BRA1'],'阿根廷':['ARG1']}[creation.nationality]||['AUS1','USA1','CHN2'];let pool=DATA.clubs.filter(x=>countryLeagues.includes(x.leagueId)&&x.rep<=c.ovr+15);if(pool.length<3)pool=DATA.clubs.filter(x=>x.rep<=c.ovr+13&&['C','D'].includes(x.tier));const r=rngFor(creation.seed,`offers-${creation.draw}`);return [...pool].sort(()=>r()-.5).slice(0,4)}
function renderCreation(){topbar.innerHTML=`<button class="brand" id="exitCreate"><span class="brand-icon">‹</span><span class="brand-copy"><b>创建球员</b><small>球探报告同屏显示</small></span></button><span class="pill">刷新 ${creation.draw+1}</span>`;nav.innerHTML='';const c=creation.candidate,offers=startingOffers();
 view.innerHTML=`<section class="screen creation"><div class="portrait-stage card"><div class="portrait-wrap"><div class="creation-score"><b>${c.ovr}</b><small>${creation.position} · 潜力 ${c.potential}</small></div>${faceHTML(c.faceSeed,'','随机球员真人风格头像')}</div><div class="portrait-controls"><label class="field-label" style="gap:3px"><span>生涯种子</span><input id="seedInput" value="${esc(creation.seed)}"></label><button class="secondary" id="reroll">刷新角色</button></div></div><div class="create-panel card"><div class="create-head"><div><div class="label">ONE-SCREEN CREATION</div><h2>身份、位置和球探报告</h2></div><span class="pill ${c.potential>=90?'gold':'blue'}">${c.trait}</span></div><div class="form-scroll"><div style="display:grid;grid-template-columns:1fr 1fr;gap:9px"><label class="field-label">球员姓名<input id="nameInput" value="${esc(creation.name)}" placeholder="留空将随机生成"></label><label class="field-label">国籍<select id="nationSelect">${['中国','日本','韩国','西班牙','英格兰','德国','意大利','法国','巴西','阿根廷','葡萄牙','荷兰','美国'].map(n=>`<option ${n===creation.nationality?'selected':''}>${n}</option>`).join('')}</select></label></div><div><div class="label" style="margin-bottom:7px">选择场上位置</div><div class="position-grid">${Object.entries(POSITIONS).map(([id,label])=>`<button data-pos="${id}" class="${creation.position===id?'active':''} ${id==='GK'?'gk':''}">${id}<br><small>${label}</small></button>`).join('')}</div></div><div class="scout-inline"><div class="radar-box subtle-card">${radarSVG(c.attrs)}</div><div class="scout-box subtle-card"><div class="label">球探结论</div><h3>${c.potential>=91?'世界级苗子':c.potential>=86?'高级别潜力':c.potential>=80?'职业级潜力':'需要耐心培养'}</h3><div class="scout-row"><span>潜力区间</span><b>${c.potential-2}–${Math.min(99,c.potential+2)}</b></div><div class="scout-row"><span>职业态度</span><b>${c.professionalism}</b></div><div class="scout-row"><span>适应能力</span><b>${c.adaptability}</b></div><div class="scout-row"><span>伤病风险</span><b>${c.injuryRisk<30?'低':c.injuryRisk<52?'中':'高'}</b></div><div class="scout-row"><span>弱脚 / 花式</span><b>${c.weakFoot}★ / ${c.skillMoves}★</b></div></div></div><div><div class="label" style="margin-bottom:7px">首份合同邀请</div><div class="offer-strip">${offers.map(o=>`<button class="offer ${creation.clubId===o.id?'active':''}" data-offer="${o.id}">${crestHTML(o)}<span><b>${o.cn}</b><small>${o.native}<br>${o.leagueCn} · ${o.tier}级</small></span></button>`).join('')}</div></div></div><div class="create-actions"><button class="secondary" id="randomName">随机姓名</button><button class="primary green-bg" id="beginCareer">签约并开始生涯</button></div></div></section>`;
 document.querySelector('#exitCreate').onclick=renderWelcome;document.querySelector('#reroll').onclick=()=>{creation.name=document.querySelector('#nameInput').value;creation.seed=document.querySelector('#seedInput').value||creation.seed;creation.draw++;rollCandidate();renderCreation()};document.querySelector('#seedInput').onchange=e=>{creation.seed=e.target.value||creation.seed;creation.draw=0;rollCandidate();renderCreation()};document.querySelector('#nameInput').oninput=e=>creation.name=e.target.value;document.querySelector('#nationSelect').onchange=e=>{creation.nationality=e.target.value;creation.draw=0;rollCandidate();renderCreation()};document.querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{creation.position=b.dataset.pos;creation.draw=0;rollCandidate();renderCreation()});document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>{creation.clubId=b.dataset.offer;renderCreation()});document.querySelector('#randomName').onclick=()=>{creation.name=randomName(creation.nationality,rngFor(creation.seed,`name-${creation.draw}`));renderCreation()};document.querySelector('#beginCareer').onclick=beginCareer;hydrateMedia(view)}
function randomName(country,r){const pools={中国:[['王','李','张','刘','陈','杨','黄','赵','吴','周'],['宇轩','浩然','子墨','俊杰','龙飞','泽宇','天乐','昊阳']],日本:[['佐藤','鈴木','高橋','田中','伊藤','山本'],['蓮','大翔','悠真','颯太','陽斗','湊']],韩国:[['김','이','박','최','정','강'],['민준','서준','도윤','예준','시우','주원']]};if(pools[country])return pick(pools[country][0],r)+pick(pools[country][1],r);const first=['Alex','Leo','Daniel','Mateo','Lucas','Hugo','Marco','Nico'],last=['Silva','Martín','Costa','Meyer','Rossi','Lee','Santos','García'];return `${pick(first,r)} ${pick(last,r)}`}
function beginCareer(){const c=creation.candidate,clubObj=club(creation.clubId);const name=creation.name.trim()||randomName(creation.nationality,rngFor(creation.seed,'name'));state={id:`career-${Date.now()}-${Math.floor(Math.random()*9999)}`,version:VERSION,seed:creation.seed,name,nationality:creation.nationality,position:creation.position,age:16,season:2026,month:8,faceSeed:c.faceSeed,photoWiki:'',clubId:clubObj.id,parentClubId:null,loanUntil:null,attrs:{...c.attrs},ovr:c.ovr,potential:c.potential,trait:c.trait,professionalism:c.professionalism,adaptability:c.adaptability,bigGame:c.bigGame,injuryRisk:c.injuryRisk,weakFoot:c.weakFoot,skillMoves:c.skillMoves,coachFavor:36+Math.floor(rngFor(c.faceSeed,'coach')()*23),relations:50,leadership:30,integrity:82,ambition:55,morale:70,form:58,fitness:96,reputation:6,nationalRep:0,followers:300,money:5000,value:marketValue(c.ovr,c.potential,16),salary:450+clubObj.rep*7,contractYears:3,role:'青年队',lowMinutesStreak:0,transferInterest:0,loanInterest:0,growthBank:0,seenEvents:[],feed:[],timeline:[],honours:[],stats:{apps:0,starts:0,subs:0,bench:0,notSquad:0,goals:0,assists:0,avgRating:0,ratings:[],clubs:[clubObj.id],nationalApps:0,nationalGoals:0},seasonStats:freshSeasonStats(),lastPeriod:null,careerEnded:false};updateRole();addTimeline('签下首份职业合同',`${clubObj.cn}向你提供了一份 ${state.contractYears} 年合同。球探给出的潜力上限为 ${state.potential}。`,'✍️');addFeed('职业起点',`${clubObj.cn}确认签下16岁的${state.name}。`,'⚽');saveState();route='home';renderApp();setTimeout(()=>triggerEvent(true),450)}
function marketValue(ovr,pot,age){return Math.max(20000,Math.round(Math.pow(Math.max(42,ovr)-36,3)*(1+(pot-ovr)/55)*(age<21?1.2:1)*140))}
function freshSeasonStats(){return {apps:0,starts:0,subs:0,bench:0,notSquad:0,goals:0,assists:0,ratings:[],wins:0,draws:0,losses:0}}
function addTimeline(title,text,icon='•'){state.timeline.unshift({title,text,icon,season:seasonLabel(state.season),month:state.month});state.timeline=state.timeline.slice(0,120)}
function addFeed(title,text,icon='•'){state.feed.unshift({title,text,icon,date:`${state.season}.${String(state.month).padStart(2,'0')}`});state.feed=state.feed.slice(0,40)}
function updateRole(){const c=club(state.clubId);const same=clubPlayers(c.id).filter(p=>positionGroup(p.pos)===positionGroup(state.position));const best=same.length?Math.max(...same.map(p=>p.ovr)):c.rep-2;const score=state.ovr-best+(state.coachFavor-50)*.18+(state.form-60)*.08+(state.professionalism-50)*.03-(100-state.fitness)*.05;if(state.age<18&&score<3)state.role='青年队';else if(score>=12)state.role='核心';else if(score>=6)state.role='主力';else if(score>=0)state.role='轮换';else if(score>=-6)state.role='替补';else if(score>=-11)state.role='预备队';else state.role='未进名单'}
function positionGroup(p){if(p==='GK')return'GK';if(['CB','LB','RB'].includes(p))return'DEF';if(['CDM','CM','CAM'].includes(p))return'MID';return'ATT'}
function renderApp(){if(!state)return renderWelcome();syncHeader();const pages={home:renderHome,career:renderCareer,world:renderWorld,honours:renderHonours,profile:renderProfile};(pages[route]||renderHome)();hydrateMedia(view)}
function renderHome(){const c=club(state.clubId),next=nextActionText();view.innerHTML=`<section class="screen dashboard"><article class="hero-player card"><div class="hero-photo">${state.photoWiki?wikiThumbHTML(state.photoWiki,facePath(state.faceSeed),'',state.name):faceHTML(state.faceSeed,'',state.name)}<div class="hero-rating"><b>${state.ovr}</b><small>${state.position} · POT ${state.potential}</small></div></div><div class="hero-info"><div class="hero-name"><div class="label">${seasonLabel(state.season)} · ${POSITIONS[state.position]}</div><h1>${esc(state.name)}</h1><p>${c.cn} <small>· ${c.native}</small></p></div><div class="status-row"><span class="pill ${ROLE_COLOR[state.role]}">${state.role}</span><span class="pill">教练青睐 ${state.coachFavor}</span><span class="pill">状态 ${state.form}</span><span class="pill">体能 ${state.fitness}</span></div><div class="next-card"><div><div class="label">下一步</div><h2>${next.title}</h2><p>${next.desc}</p></div><button class="primary" id="advance">${next.button}</button></div><div class="metric-row"><div class="metric"><b>${state.stats.apps}</b><small>出场</small></div><div class="metric"><b>${state.stats.goals}</b><small>进球</small></div><div class="metric"><b>${state.stats.assists}</b><small>助攻</small></div><div class="metric"><b>${state.stats.ratings.length?avg(state.stats.ratings).toFixed(1):'–'}</b><small>评分</small></div></div></div></article><aside class="side-stack"><div class="quick-menu card"><button data-panel="squad"><i>◫</i><b>阵容顺位</b><small>竞争者与对手阵容</small></button><button data-panel="contract"><i>✎</i><b>合同与租借</b><small>工资、年限和经纪人</small></button><button data-panel="development"><i>↗</i><b>能力发展</b><small>六维属性与成长</small></button><button data-panel="news"><i>◌</i><b>生涯新闻</b><small>媒体、转会和国家队</small></button></div><div class="feed-card card"><div class="section-head"><h3>最新动态</h3><small class="muted">事件库 ${EVENT_LIBRARY.length}</small></div><div class="feed-list">${state.feed.length?state.feed.slice(0,5).map(f=>`<div class="feed-item"><i>${f.icon}</i><div><b>${esc(f.title)}</b><p>${esc(f.text)}</p></div></div>`).join(''):'<div class="muted" style="font-size:11px;padding:10px">职业生涯刚刚开始。</div>'}</div></div></aside></section>`;document.querySelector('#advance').onclick=advanceCareer;document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel))}
function nextActionText(){if(state.careerEnded)return{title:'这段生涯已经结束',desc:'退役档案已永久保存。',button:'查看档案'};if(state.lastPeriod)return{title:`推进到 ${state.month===12?state.season+1:state.season} 年 ${state.month===12?1:state.month+1} 月`,desc:`上个月：${state.lastPeriod.summary}。比赛将自动模拟，只在真正需要你决定时出现事件。`,button:'模拟下个月'};return{title:'进入第一个职业月',desc:'系统会根据你的能力、队内竞争和教练青睐决定是否进入名单。',button:'开始模拟'}}
function advanceCareer(){if(state.careerEnded){route='profile';renderApp();return}simulateMonth();saveState();renderHome();setTimeout(()=>triggerEvent(false),300)}
function simulateMonth(){const r=rngFor(state.seed,`${state.season}-${state.month}-${state.stats.apps}`);updateRole();const games=3+Math.floor(r()*3);let apps=0,starts=0,goals=0,assists=0,ratings=[],bench=0,notSquad=0;const chance=ROLE_CHANCE[state.role]||.2;for(let i=0;i<games;i++){if(r()<chance){apps++;const started=r()<Math.min(.95,chance+.2);if(started)starts++;const mins=started?65+Math.floor(r()*26):12+Math.floor(r()*28);const attack=(state.attrs.sho*.37+state.attrs.dri*.2+state.attrs.pac*.12+state.form*.12)/100;const creativity=(state.attrs.pas*.42+state.attrs.dri*.17+state.form*.1)/100;if(r()<attack*(mins/90)*.43)goals++;if(r()<creativity*(mins/90)*.36)assists++;ratings.push(clamp(5.6+attack*2+r()*1.5+(goals+assists)*.13,5.2,9.8))}else{if(r()<.68)bench++;else notSquad++}}
 const avgR=ratings.length?avg(ratings):0;state.stats.apps+=apps;state.stats.starts+=starts;state.stats.subs+=apps-starts;state.stats.bench+=bench;state.stats.notSquad+=notSquad;state.stats.goals+=goals;state.stats.assists+=assists;state.stats.ratings.push(...ratings);state.seasonStats.apps+=apps;state.seasonStats.starts+=starts;state.seasonStats.subs+=apps-starts;state.seasonStats.bench+=bench;state.seasonStats.notSquad+=notSquad;state.seasonStats.goals+=goals;state.seasonStats.assists+=assists;state.seasonStats.ratings.push(...ratings);state.form=clamp(state.form+(avgR?Math.round((avgR-6.7)*4):-2)+Math.floor(r()*3)-1,30,96);state.fitness=clamp(state.fitness-7-r()*7+state.professionalism*.08,35,100);state.coachFavor=clamp(state.coachFavor+(apps?Math.round((avgR-6.4)*3):-(notSquad?3:1)),0,100);state.morale=clamp(state.morale+(apps?2:-2)+(avgR>=7.5?3:0),20,100);if(apps<=1)state.lowMinutesStreak++;else state.lowMinutesStreak=0;growPlayer(apps,avgR,r);state.lastPeriod={apps,starts,goals,assists,avg:avgR,summary:apps?`${apps}次出场，${goals}球${assists}助，平均评分 ${avgR.toFixed(1)}`:`没有获得出场，${bench}次进入替补席`};addFeed('月度比赛自动模拟',state.lastPeriod.summary,apps?'⚽':'◫');
 state.month++;if(state.month>12){endSeason(r);state.month=8}state.fitness=clamp(state.fitness+8,35,100);updateRole();if(state.lowMinutesStreak>=3)state.loanInterest=clamp((state.loanInterest||0)+4,0,10)}
function growPlayer(apps,rating,r){const ageFactor=state.age<20?1.25:state.age<24?1:state.age<28?.62:state.age<31?.22:-.45;let gain=(apps*.24+(rating?rating-6:0)+state.professionalism/100)*ageFactor;if(state.trait==='大器晚成'&&state.age>=22)gain*=1.4;if(gain>0){state.growthBank+=gain;while(state.growthBank>=2.5){state.growthBank-=2.5;const focus=pick(focusAttrs(state.position),r);if(state.attrs[focus]<state.potential)state.attrs[focus]=clamp(state.attrs[focus]+1,1,99)}}else if(r()<Math.abs(gain)*.15){const k=pick(ATTRS,r);state.attrs[k]=clamp(state.attrs[k]-1,1,99)}state.ovr=calculateOVR(state.attrs,state.position);state.value=marketValue(state.ovr,state.potential,state.age)}
function focusAttrs(pos){return {ST:['sho','phy','pac'],LW:['pac','dri','sho'],RW:['pac','dri','pas'],CAM:['pas','dri','sho'],CM:['pas','phy','dri'],CDM:['def','phy','pas'],LB:['pac','def','phy'],RB:['pac','def','pas'],CB:['def','phy','pas'],GK:['def','phy','pas']}[pos]||ATTRS}
function endSeason(r){const ss=state.seasonStats;state.age++;state.season++;state.contractYears--;const avgR=ss.ratings.length?avg(ss.ratings):0;if(ss.apps>=20&&avgR>=7.35){const award=state.age<=21?'最佳年轻球员':'赛季最佳阵容';state.honours.push({id:state.age<=21?'young':'league',title:award,year:state.season-1,detail:`${ss.apps}场 ${ss.goals}球 ${ss.assists}助，评分 ${avgR.toFixed(1)}`});addTimeline(`获得${award}`,`赛季表现得到认可：${ss.apps}次出场，${ss.goals}球。`,'🏆')}
 if(state.contractYears<=0){if(ss.apps<8&&state.ovr<club(state.clubId).rep-6){addTimeline('合同到期未获续约','出场时间不足，俱乐部决定不再续约。','⌛');findFreeClub(r)}else{state.contractYears=3;state.salary=Math.round(state.salary*(1.25+Math.max(0,state.ovr-club(state.clubId).rep)*.03));addTimeline('完成续约',`新合同为期3年，周薪提高到 ${money(state.salary)}。`,'✎')}}
 if(state.age>=36||(state.age>=33&&state.ovr<60)){retire('身体状态与市场机会让你决定结束职业生涯。');return}
 state.seasonStats=freshSeasonStats();state.lowMinutesStreak=0;state.fitness=90;state.morale=70;addTimeline(`${seasonLabel(state.season-1)}赛季结束`,`${ss.apps}场 ${ss.goals}球 ${ss.assists}助。新赛季角色：${state.role}。`,'📅')}
function findFreeClub(r){let pool=DATA.clubs.filter(c=>c.rep<=state.ovr+8&&c.rep>=state.ovr-10);if(pool.length){const next=pick(pool,r);state.clubId=next.id;state.contractYears=2;state.salary=Math.max(300,next.rep*9);state.stats.clubs.push(next.id);state.coachFavor=42;addTimeline('自由转会',`${next.cn}在合同到期后签下了你。`,'⇄')}else retire('合同到期后没有职业俱乐部提供正式报价。')}
function avg(a){return a.reduce((s,n)=>s+n,0)/Math.max(1,a.length)}
function triggerEvent(first){if(state.careerEnded)return;let eligible=EVENT_LIBRARY.filter(e=>!state.seenEvents.includes(e.id));if(state.lowMinutesStreak>=3)eligible=eligible.filter(e=>['selection','loan','agent','coach','contract'].includes(e.cat.id));else if(state.contractYears<=1)eligible=eligible.filter(e=>['contract','agent','transfer'].includes(e.cat.id));if(!eligible.length){state.seenEvents=[];eligible=EVENT_LIBRARY}const r=rngFor(state.seed,`event-${state.seenEvents.length}-${state.season}-${state.month}`);const ev=pick(eligible,r);showEvent(ev)}
function showEvent(ev){const c=club(state.clubId);eventBody.innerHTML=`<div class="event-shell" style="--event-color:${ev.cat.color}"><div class="event-icon">${ev.cat.icon}</div><div class="event-meta">${ev.cat.label.toUpperCase()} · ${state.seenEvents.length+1}/${EVENT_LIBRARY.length}</div><h1>${esc(ev.title)}</h1><p>${esc(ev.body.replace('你的身份',`${state.name}在${c.cn}的${state.role}身份`))}</p><div class="event-context"><span class="pill">${c.cn}</span><span class="pill">${state.role}</span><span class="pill">教练 ${state.coachFavor}</span><span class="pill">OVR ${state.ovr}</span></div><div class="choice-list">${ev.choices.map((ch,i)=>`<button class="choice" data-choice="${i}"><span><b>${esc(ch.label)}</b><small>${esc(ch.sub)}</small></span><em>${i===0?'稳健处理':'另一条路'}</em></button>`).join('')}</div></div>`;eventDialog.showModal();eventBody.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>resolveEvent(ev,+b.dataset.choice))}
function resolveEvent(ev,index){const ch=ev.choices[index],effects=applyEffects(ch.effect);state.seenEvents.push(ev.id);addTimeline(ev.title,`${ch.label}。${effects.join('，')||'后续影响将在未来体现'}。`,ev.cat.icon);addFeed(ev.cat.label,`${ev.title}：你选择了“${ch.label}”。`,ev.cat.icon);saveState();eventBody.innerHTML=`<div class="result-view"><div class="result-icon">${ev.cat.icon}</div><div class="label">CHOICE CONSEQUENCE</div><h2>${esc(ch.label)}</h2><p class="muted">这个结果已经写入你的生涯记录，页面将自动进入下一步。</p><div class="effect-pills">${effects.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div></div>`;setTimeout(()=>{eventDialog.close();renderApp()},1050)}
function applyEffects(fx){const out=[];for(const [k,v] of Object.entries(fx||{})){if(k==='growth'){state.growthBank+=v;out.push(`成长经验 +${v}`);continue}if(k==='salaryBoost'){state.salary=Math.round(state.salary*(1+.08*v));out.push(`周薪提高 ${8*v}%`);continue}if(k==='money'){state.money+=v;out.push(`现金 ${v>=0?'+':''}${money(v)}`);continue}if(k==='followers'){state.followers=Math.max(0,state.followers+v);out.push(`粉丝 ${v>=0?'+':''}${v}`);continue}state[k]=clamp((state[k]||0)+v,0,100);const names={coachFavor:'教练青睐',professionalism:'职业态度',morale:'士气',reputation:'声望',form:'状态',fitness:'体能',relations:'队友关系',ambition:'野心',leadership:'领导力',integrity:'职业原则',adaptability:'适应力',nationalRep:'国家队关注',loanInterest:'租借可能',transferInterest:'转会关注'};out.push(`${names[k]||k} ${v>=0?'+':''}${v}`)}updateRole();return out}

function openPanel(type){if(type==='squad')return openSquad();if(type==='contract')return openContract();if(type==='development')return openDevelopment();if(type==='news')return openNews()}
function openSheet(title,html){sheetBody.innerHTML=`<h2>${title}</h2>${html}`;sheet.showModal();hydrateMedia(sheetBody)}
function generatedRoster(c){const real=clubPlayers(c.id);const positions=['GK','RB','CB','CB','LB','CDM','CM','CAM','RW','LW','ST','GK','CB','CM','ST'];const r=rngFor(c.id,'roster');const gen=positions.slice(real.length).map((pos,i)=>({cn:`${c.cn}球员 ${i+1}`,name:`Squad Player ${i+1}`,pos,ovr:clamp(c.rep-9+Math.floor(r()*17),50,92),attrs:{pac:60,sho:60,pas:60,dri:60,def:60,phy:60},wiki:'',generated:true}));return [...real,...gen].sort((a,b)=>b.ovr-a.ovr)}
function playerRow(p,idx=0){return `<div class="player-row">${p.generated?faceHTML(`${p.name}-${idx}`,'',p.name):wikiThumbHTML(p.wiki||'',facePath(p.name),'',p.name)}<span><b>${esc(p.cn)}</b><small>${esc(p.name)} · ${p.pos}</small></span><strong>${p.ovr}</strong></div>`}
function openSquad(){const c=club(state.clubId),roster=generatedRoster(c),same=roster.filter(p=>positionGroup(p.pos)===positionGroup(state.position));const opp=pick(DATA.clubs.filter(x=>x.leagueId===c.leagueId&&x.id!==c.id),rngFor(state.seed,`opp-${state.season}-${state.month}`))||DATA.clubs[0];openSheet('阵容顺位',`<p class="intro">你的出场机会由能力、同位置竞争、教练青睐、状态和体能共同决定。</p><div class="contract-card"><div class="contract-line"><span>当前角色</span><b class="${ROLE_COLOR[state.role]}">${state.role}</b></div><div class="contract-line"><span>教练青睐</span><b>${state.coachFavor}/100</b></div><div class="contract-line"><span>同位置最高能力</span><b>${same[0]?.ovr||c.rep}</b></div><div class="contract-line"><span>预计出场概率</span><b>${Math.round((ROLE_CHANCE[state.role]||.2)*100)}%</b></div></div><h3>同位置竞争</h3><div class="roster">${same.slice(0,7).map(playerRow).join('')}</div><h3>下一位联赛对手：${opp.cn}</h3><p class="intro">${opp.native} · 球队强度 ${opp.rep}</p><div class="roster">${generatedRoster(opp).slice(0,11).map(playerRow).join('')}</div>`)}
function openContract(){const c=club(state.clubId);openSheet('合同与租借',`<p class="intro">${c.cn} · ${c.native}</p><div class="contract-card"><div class="contract-line"><span>周薪</span><b>${money(state.salary)}</b></div><div class="contract-line"><span>剩余年限</span><b>${state.contractYears} 年</b></div><div class="contract-line"><span>当前身价</span><b>${money(state.value)}</b></div><div class="contract-line"><span>租借关注</span><b>${state.loanInterest||0}/10</b></div><div class="contract-line"><span>转会关注</span><b>${state.transferInterest||0}/10</b></div></div><div style="display:flex;gap:8px;margin-top:14px"><button class="primary" id="talkContract">与经纪人谈判</button><button class="secondary" id="askLoan">申请租借</button></div>`);document.querySelector('#talkContract').onclick=()=>{sheet.close();showEvent(EVENT_LIBRARY.find(e=>e.cat.id==='contract'&&!state.seenEvents.includes(e.id))||EVENT_LIBRARY[0])};document.querySelector('#askLoan').onclick=()=>{state.loanInterest=clamp((state.loanInterest||0)+3,0,10);state.coachFavor=clamp(state.coachFavor-2,0,100);saveState();toast('经纪人已向俱乐部表达租借意愿');openContract()}}
function openDevelopment(){openSheet('能力发展',`<p class="intro">FC 26 风格六维能力。成长受年龄、潜力、职业态度、比赛时间和伤病影响。</p><div class="scout-inline"><div class="radar-box subtle-card">${radarSVG(state.attrs)}</div><div class="scout-box subtle-card"><div class="scout-row"><span>当前能力</span><b>${state.ovr}</b></div><div class="scout-row"><span>潜力上限</span><b>${state.potential}</b></div><div class="scout-row"><span>天赋</span><b>${state.trait}</b></div><div class="scout-row"><span>职业态度</span><b>${state.professionalism}</b></div><div class="scout-row"><span>弱脚 / 花式</span><b>${state.weakFoot}★ / ${state.skillMoves}★</b></div></div></div><div class="metric-row" style="margin-top:12px">${ATTRS.map(k=>`<div class="metric"><b>${state.attrs[k]}</b><small>${ATTR_CN[k]}</small></div>`).join('')}</div>`)}
function openNews(){openSheet('生涯新闻',`<p class="intro">新闻与事件均来自本存档独立时间线。</p><div class="timeline">${state.feed.map(f=>`<div class="timeline-item"><i>${f.icon}</i><div><b>${esc(f.title)}</b><p>${esc(f.text)}</p></div><time>${f.date}</time></div>`).join('')}</div>`)}

function renderCareer(){view.innerHTML=`<section class="screen page-card card"><div class="page-head"><div><h1>生涯时间线</h1><p>合同、租借、首发、伤病、转会与赛季荣誉</p></div><div class="toolbar"><button class="secondary" id="contractShortcut">合同</button><button class="secondary" id="squadShortcut">阵容</button></div></div><div class="content-scroll timeline">${state.timeline.map(t=>`<div class="timeline-item"><i>${t.icon}</i><div><b>${esc(t.title)}</b><p>${esc(t.text)}</p></div><time>${t.season}</time></div>`).join('')}</div></section>`;document.querySelector('#contractShortcut').onclick=openContract;document.querySelector('#squadShortcut').onclick=openSquad}
function renderWorld(){const leagues=DATA.leagues;view.innerHTML=`<section class="screen page-card card"><div class="page-head"><div><h1>真实足球世界</h1><p>${DATA.clubs.length} 家俱乐部 · 中文名称 + 当地官方名称</p></div><div class="toolbar"><select id="leagueFilter"><option value="">全部联赛</option>${leagues.map(l=>`<option value="${l.id}">${l.cn}</option>`).join('')}</select><input id="clubSearch" placeholder="搜索球队"></div></div><div id="clubGrid" class="content-scroll league-grid"></div></section>`;const grid=document.querySelector('#clubGrid'),filter=document.querySelector('#leagueFilter'),search=document.querySelector('#clubSearch');const draw=()=>{const q=search.value.trim().toLowerCase(),lid=filter.value;const arr=DATA.clubs.filter(c=>(!lid||c.leagueId===lid)&&(!q||c.cn.includes(q)||c.native.toLowerCase().includes(q))).slice(0,160);grid.innerHTML=arr.map(c=>`<button class="club-tile" data-club="${c.id}">${crestHTML(c)}<span><b>${c.cn}</b><small>${c.native}<br>${c.leagueCn}</small><span class="tier">${c.tier} · ${c.rep}</span></span></button>`).join('');grid.querySelectorAll('[data-club]').forEach(b=>b.onclick=()=>openClub(b.dataset.club));hydrateMedia(grid)};filter.onchange=draw;search.oninput=draw;draw()}
function openClub(id){const c=club(id),roster=generatedRoster(c);openSheet(c.cn,`<p class="intro">${c.native}<br>${c.leagueCn} · ${c.leagueNative} · ${c.country} · ${c.tier}级</p><div style="display:flex;align-items:center;gap:16px;margin-bottom:16px">${crestHTML(c,'','')}<div><b style="font-size:30px">${c.rep}</b><div class="muted" style="font-size:11px">球队综合强度</div></div></div><h3>代表球员与阵容</h3><div class="roster">${roster.slice(0,18).map(playerRow).join('')}</div>`)}
function renderHonours(){view.innerHTML=`<section class="screen page-card card"><div class="page-head"><div><h1>荣誉陈列室</h1><p>真实奖杯图片在线加载，离线时显示高分辨率本地模型</p></div><span class="pill gold">已获 ${state.honours.length}</span></div><div class="content-scroll honour-grid">${DATA.trophies.map((t,i)=>{const won=state.honours.filter(h=>h.id===t.id||h.id==='league'&&t.id==='league');return `<button class="trophy-tile" data-trophy="${t.id}">${wikiThumbHTML(t.wiki,t.fallback,'',t.cn)}<span><b>${t.cn}</b><small>${t.native}<br>${won.length?won.map(x=>x.year).join('、'):'尚未获得'}</small></span></button>`}).join('')}</div></section>`;document.querySelectorAll('[data-trophy]').forEach(b=>b.onclick=()=>openTrophy(b.dataset.trophy))}
function openTrophy(id){const t=DATA.trophies.find(x=>x.id===id),won=state.honours.filter(h=>h.id===id||h.id==='league'&&id==='league');openSheet(t.cn,`<p class="intro">${t.native}</p><div style="display:grid;place-items:center;background:var(--surface-2);border-radius:24px;padding:18px">${wikiThumbHTML(t.wiki,t.fallback,'',t.cn)}</div><h3>获得记录</h3>${won.length?`<div class="timeline">${won.map(x=>`<div class="timeline-item"><i>🏆</i><div><b>${esc(x.title)}</b><p>${esc(x.detail)}</p></div><time>${x.year}</time></div>`).join('')}</div>`:'<p class="muted">这座奖杯还没有进入你的个人荣誉室。</p>'}`)}
function renderProfile(){const c=club(state.clubId);view.innerHTML=`<section class="screen page-card card"><div class="page-head"><div><h1>球员档案</h1><p>独立存档与退役后永久记录</p></div><button class="secondary" id="newFromProfile">新生涯</button></div><div class="content-scroll"><div class="player-row" style="padding:14px">${state.photoWiki?wikiThumbHTML(state.photoWiki,facePath(state.faceSeed),'',state.name):faceHTML(state.faceSeed,'',state.name)}<span><b style="font-size:18px">${esc(state.name)}</b><small>${state.nationality} · ${POSITIONS[state.position]} · ${c.cn}<br>${state.age}岁 · OVR ${state.ovr} · POT ${state.potential}</small></span><strong>${state.ovr}</strong></div><div class="metric-row"><div class="metric"><b>${state.stats.apps}</b><small>俱乐部出场</small></div><div class="metric"><b>${state.stats.goals}</b><small>俱乐部进球</small></div><div class="metric"><b>${state.stats.nationalApps}</b><small>国家队出场</small></div><div class="metric"><b>${state.honours.length}</b><small>荣誉</small></div></div><h3>生涯存档</h3><div class="save-list">${saves.map(saveRow).join('')}</div><div style="display:flex;gap:8px;margin-top:14px"><button class="secondary" id="exportSave">导出存档</button><button class="secondary danger" id="retireBtn">宣布退役</button></div></div></section>`;document.querySelector('#newFromProfile').onclick=startCreation;document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>loadCareer(b.dataset.save));document.querySelector('#exportSave').onclick=exportSave;document.querySelector('#retireBtn').onclick=()=>{if(confirm('确定结束当前职业生涯并生成永久退役档案吗？'))retire('你主动宣布结束职业球员生涯。')}}
function exportSave(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.name}-career-${state.id}.json`;a.click();URL.revokeObjectURL(a.href)}
function retire(reason){state.careerEnded=true;addTimeline('宣布退役',reason,'🏁');const archive={...JSON.parse(JSON.stringify(state)),retiredAt:Date.now(),reason};archives.unshift(archive);archives=archives.slice(0,30);saves=saves.filter(s=>s.id!==state.id);saveAll();openSheet('退役档案已保存',`<p class="intro">${esc(reason)}</p><div class="contract-card"><div class="contract-line"><span>职业年限</span><b>${Math.max(0,state.age-16)} 年</b></div><div class="contract-line"><span>俱乐部出场</span><b>${state.stats.apps}</b></div><div class="contract-line"><span>进球 / 助攻</span><b>${state.stats.goals} / ${state.stats.assists}</b></div><div class="contract-line"><span>最高能力</span><b>${state.ovr}</b></div><div class="contract-line"><span>荣誉</span><b>${state.honours.length}</b></div></div><button class="primary" id="backWelcome" style="margin-top:14px">回到生涯档案</button>`);document.querySelector('#backWelcome').onclick=()=>{sheet.close();renderWelcome()}}
function openSettings(){openSheet('游戏设置',`<p class="intro">绿茵浮沉 ${VERSION}</p><div class="contract-card"><div class="contract-line"><span>真实俱乐部</span><b>${DATA.clubs.length}</b></div><div class="contract-line"><span>联赛与级别</span><b>${DATA.leagues.length}</b></div><div class="contract-line"><span>精选现实球员</span><b>${DATA.players.length}</b></div><div class="contract-line"><span>不重复事件组合</span><b>${EVENT_LIBRARY.length}</b></div><div class="contract-line"><span>本地真人风格头像</span><b>48</b></div></div><p class="intro" style="margin-top:14px">现实球员与队徽优先通过 Wikipedia / Wikimedia 联网解析并缓存；离线或找不到时使用本地高分辨率资源。精选球员六维数据采用 FC 26 风格，并非实时比赛数据。</p><button class="secondary danger" id="backAll">返回生涯选择</button>`);document.querySelector('#backAll').onclick=()=>{sheet.close();renderWelcome()}}

init();
if('serviceWorker' in navigator && location.protocol==='https:') navigator.serviceWorker.register('./sw.js').catch(()=>{});
