const schemaStatements=[
  `CREATE TABLE IF NOT EXISTS run_sessions (id TEXT PRIMARY KEY, player_key TEXT NOT NULL, seed_hash TEXT NOT NULL, started_at INTEGER NOT NULL, status TEXT NOT NULL, eligible INTEGER NOT NULL DEFAULT 0, last_sequence INTEGER NOT NULL DEFAULT 0, last_evidence TEXT NOT NULL, last_evidence_hash TEXT NOT NULL, last_reason TEXT, last_checkpoint_at INTEGER NOT NULL, rejection_reason TEXT)`,
  `CREATE TABLE IF NOT EXISTS leaderboard_entries (id TEXT PRIMARY KEY, run_id TEXT NOT NULL UNIQUE, player_name TEXT NOT NULL, nation TEXT NOT NULL, position TEXT NOT NULL, club_name TEXT NOT NULL, score INTEGER NOT NULL, grade TEXT NOT NULL, seasons INTEGER NOT NULL, ending TEXT NOT NULL DEFAULT '', submitted_at INTEGER NOT NULL, verified INTEGER NOT NULL DEFAULT 0, evidence_hash TEXT NOT NULL, FOREIGN KEY(run_id) REFERENCES run_sessions(id))`,
  `CREATE INDEX IF NOT EXISTS idx_leaderboard_verified_score ON leaderboard_entries(verified, score DESC, submitted_at ASC)`,
  `CREATE INDEX IF NOT EXISTS idx_run_sessions_status_checkpoint ON run_sessions(status, last_checkpoint_at)`,
  `CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, public_nickname TEXT NOT NULL DEFAULT '绿茵玩家', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS career_runs (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, server_seed TEXT NOT NULL, session_token_hash TEXT NOT NULL, game_version TEXT NOT NULL, config_version TEXT NOT NULL, difficulty TEXT NOT NULL, initial_ovr INTEGER NOT NULL, state_json TEXT NOT NULL, state_hash TEXT NOT NULL, sequence INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL, review_status TEXT NOT NULL DEFAULT 'clear', started_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS run_events (id TEXT PRIMARY KEY, run_id TEXT NOT NULL, sequence INTEGER NOT NULL, nonce TEXT NOT NULL, action_json TEXT NOT NULL, result_json TEXT NOT NULL, previous_hash TEXT NOT NULL, state_hash TEXT NOT NULL, created_at INTEGER NOT NULL, UNIQUE(run_id,sequence), UNIQUE(run_id,nonce))`,
  `CREATE TABLE IF NOT EXISTS score_snapshots (id TEXT PRIMARY KEY, run_id TEXT NOT NULL, sequence INTEGER NOT NULL, state_hash TEXT NOT NULL, score INTEGER NOT NULL, grade TEXT NOT NULL, created_at INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS anti_cheat_flags (id TEXT PRIMARY KEY, run_id TEXT NOT NULL, code TEXT NOT NULL, severity TEXT NOT NULL, details_json TEXT NOT NULL, created_at INTEGER NOT NULL, resolved_at INTEGER)`,
  `CREATE TABLE IF NOT EXISTS leaderboard_metadata (run_id TEXT PRIMARY KEY, user_id TEXT NOT NULL, public_nickname TEXT NOT NULL, game_version TEXT NOT NULL, difficulty TEXT NOT NULL, category TEXT NOT NULL, review_status TEXT NOT NULL, public_details INTEGER NOT NULL DEFAULT 1, withdrawn INTEGER NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS leaderboard_reports (id TEXT PRIMARY KEY, target_run_id TEXT NOT NULL, reason TEXT NOT NULL, created_at INTEGER NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_run_events_run_sequence ON run_events(run_id,sequence)`,
  `CREATE INDEX IF NOT EXISTS idx_flags_run_severity ON anti_cheat_flags(run_id,severity)`,
  `CREATE INDEX IF NOT EXISTS idx_metadata_filters ON leaderboard_metadata(category,game_version,difficulty,withdrawn)`
];

export class D1LeaderboardRepository{
  constructor(db){if(!db)throw new Error('未配置 D1 绑定 DB');this.db=db;this.ready=null}
  ensureSchema(){
    if(!this.ready)this.ready=this.db.batch(schemaStatements.map(sql=>this.db.prepare(sql))).then(()=>this.db.prepare('PRAGMA optimize').run());
    return this.ready;
  }
  async createSession(s){await this.ensureSchema();await this.db.prepare(`INSERT INTO run_sessions (id,player_key,seed_hash,started_at,status,eligible,last_sequence,last_evidence,last_evidence_hash,last_checkpoint_at) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(s.id,s.playerKey,s.seedHash,s.startedAt,s.status,s.eligible?1:0,0,JSON.stringify(s.lastEvidence),s.lastEvidenceHash,s.lastCheckpointAt).run()}
  async getSession(id){await this.ensureSchema();const row=await this.db.prepare('SELECT * FROM run_sessions WHERE id=?').bind(id).first();if(!row)return null;return{id:row.id,playerKey:row.player_key,seedHash:row.seed_hash,startedAt:row.started_at,status:row.status,eligible:Boolean(row.eligible),lastSequence:Number(row.last_sequence),lastEvidence:JSON.parse(row.last_evidence),lastEvidenceHash:row.last_evidence_hash,lastCheckpointAt:row.last_checkpoint_at}}
  async updateCheckpoint(id,c){await this.ensureSchema();await this.db.prepare(`UPDATE run_sessions SET last_sequence=?,last_evidence=?,last_evidence_hash=?,last_reason=?,last_checkpoint_at=?,status='tracking' WHERE id=?`).bind(c.sequence,JSON.stringify(c.evidence),c.evidenceHash,c.reason,c.at,id).run()}
  async rejectSession(id,reason,at){await this.ensureSchema();await this.db.prepare(`UPDATE run_sessions SET status='rejected',rejection_reason=?,last_checkpoint_at=? WHERE id=?`).bind(reason,at,id).run()}
  async completeSession(id,at){await this.ensureSchema();await this.db.prepare(`UPDATE run_sessions SET status='complete',last_checkpoint_at=? WHERE id=?`).bind(at,id).run()}
  async upsertEntry(e){await this.ensureSchema();await this.db.prepare(`INSERT INTO leaderboard_entries (id,run_id,player_name,nation,position,club_name,score,grade,seasons,ending,submitted_at,verified,evidence_hash) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(run_id) DO UPDATE SET player_name=excluded.player_name,nation=excluded.nation,position=excluded.position,club_name=excluded.club_name,score=excluded.score,grade=excluded.grade,seasons=excluded.seasons,ending=excluded.ending,submitted_at=excluded.submitted_at,verified=excluded.verified,evidence_hash=excluded.evidence_hash`).bind(e.id,e.runId,e.playerName,e.nation,e.position,e.clubName,e.score,e.grade,e.seasons,e.ending,e.submittedAt,1,e.evidenceHash).run()}
  async listEntries(limit){await this.ensureSchema();const result=await this.db.prepare(`SELECT player_name,nation,position,club_name,score,grade,seasons,ending,submitted_at FROM leaderboard_entries WHERE verified=1 ORDER BY score DESC, submitted_at ASC LIMIT ?`).bind(limit).all();return result.results||[]}
  async createAuthorityRun(run){
    await this.ensureSchema();
    await this.db.batch([
      this.db.prepare(`INSERT INTO users (id,public_nickname,created_at,updated_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET public_nickname=excluded.public_nickname,updated_at=excluded.updated_at`).bind(run.userId,run.state.player.publicNickname,run.startedAt,run.updatedAt),
      this.db.prepare(`INSERT INTO career_runs (id,user_id,server_seed,session_token_hash,game_version,config_version,difficulty,initial_ovr,state_json,state_hash,sequence,status,review_status,started_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(run.id,run.userId,run.serverSeed,run.sessionTokenHash,run.gameVersion,run.configVersion,run.difficulty,run.initialOvr,JSON.stringify(run.state),run.stateHash,0,run.status,run.reviewStatus,run.startedAt,run.updatedAt),
      this.db.prepare(`INSERT OR IGNORE INTO run_sessions (id,player_key,seed_hash,started_at,status,eligible,last_sequence,last_evidence,last_evidence_hash,last_checkpoint_at) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(run.id,run.userId,run.stateHash,run.startedAt,'tracking',1,0,JSON.stringify(run.state),run.stateHash,run.updatedAt)
    ]);
  }
  async getAuthorityRun(id){await this.ensureSchema();const row=await this.db.prepare('SELECT * FROM career_runs WHERE id=?').bind(id).first();if(!row)return null;return{id:row.id,userId:row.user_id,serverSeed:row.server_seed,sessionTokenHash:row.session_token_hash,gameVersion:row.game_version,configVersion:row.config_version,difficulty:row.difficulty,initialOvr:Number(row.initial_ovr),state:JSON.parse(row.state_json),stateHash:row.state_hash,sequence:Number(row.sequence),status:row.status,reviewStatus:row.review_status,startedAt:Number(row.started_at),updatedAt:Number(row.updated_at)}}
  async hasNonce(runId,nonce){await this.ensureSchema();return Boolean(await this.db.prepare('SELECT id FROM run_events WHERE run_id=? AND nonce=?').bind(runId,nonce).first())}
  async commitAuthorityAction(previous,{state,stateHash,event,now}){await this.ensureSchema();const result=await this.db.prepare(`UPDATE career_runs SET state_json=?,state_hash=?,sequence=?,updated_at=? WHERE id=? AND sequence=? AND state_hash=? AND status='active'`).bind(JSON.stringify(state),stateHash,event.sequence,now,previous.id,previous.sequence,previous.stateHash).run();if(Number(result.meta?.changes||0)!==1)return false;await this.db.prepare(`INSERT INTO run_events (id,run_id,sequence,nonce,action_json,result_json,previous_hash,state_hash,created_at) VALUES (?,?,?,?,?,?,?,?,?)`).bind(event.id,event.runId,event.sequence,event.nonce,JSON.stringify(event.action),JSON.stringify(event.result),event.previousHash,event.stateHash,event.createdAt).run();return true}
  async addScoreSnapshot(snapshot){await this.ensureSchema();await this.db.prepare(`INSERT INTO score_snapshots (id,run_id,sequence,state_hash,score,grade,created_at) VALUES (?,?,?,?,?,?,?)`).bind(snapshot.id,snapshot.runId,snapshot.sequence,snapshot.stateHash,snapshot.score,snapshot.grade,snapshot.createdAt).run()}
  async addAntiCheatFlag(flag){await this.ensureSchema();await this.db.prepare(`INSERT INTO anti_cheat_flags (id,run_id,code,severity,details_json,created_at) VALUES (?,?,?,?,?,?)`).bind(flag.id,flag.runId,flag.code,flag.severity,JSON.stringify(flag.details||{}),flag.createdAt).run()}
  async hasBlockingFlags(runId){await this.ensureSchema();const row=await this.db.prepare(`SELECT COUNT(*) AS count FROM anti_cheat_flags WHERE run_id=? AND severity IN ('high','critical') AND code NOT IN ('sequence_invalid','state_hash_mismatch','replay','concurrent_write') AND resolved_at IS NULL`).bind(runId).first();return Number(row?.count||0)>0}
  async finishAuthorityRun(runId,entry,now){await this.ensureSchema();await this.db.prepare(`UPDATE career_runs SET status='complete',updated_at=? WHERE id=? AND status='active'`).bind(now,runId).run();await this.upsertEntry(entry);await this.db.prepare(`INSERT INTO leaderboard_metadata (run_id,user_id,public_nickname,game_version,difficulty,category,review_status,public_details,withdrawn) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(run_id) DO UPDATE SET public_nickname=excluded.public_nickname,game_version=excluded.game_version,difficulty=excluded.difficulty,category=excluded.category,review_status=excluded.review_status,public_details=excluded.public_details,withdrawn=excluded.withdrawn`).bind(entry.runId,entry.userId,entry.publicNickname,entry.gameVersion,entry.difficulty,(entry.categories||[entry.category]).join(','),entry.reviewStatus,entry.publicDetails?1:0,entry.withdrawn?1:0).run()}
  async rankFor(entry){await this.ensureSchema();const row=await this.db.prepare(`SELECT COUNT(*)+1 AS rank FROM leaderboard_entries e JOIN leaderboard_metadata m ON m.run_id=e.run_id WHERE e.verified=1 AND m.withdrawn=0 AND m.review_status='clear' AND (e.score>? OR (e.score=? AND e.submitted_at<?))`).bind(entry.score,entry.score,entry.submittedAt).first();return Number(row?.rank||1)}
  async listAuthorityEntries({limit=50,offset=0,position='',gameVersion='',difficulty='',category='overall'}={}){await this.ensureSchema();const result=await this.db.prepare(`SELECT e.run_id,e.player_name,m.public_nickname,e.nation,e.position,e.club_name,e.score,e.grade,e.seasons,e.ending,e.submitted_at,m.game_version,m.difficulty,m.category,m.public_details FROM leaderboard_entries e JOIN leaderboard_metadata m ON m.run_id=e.run_id WHERE e.verified=1 AND m.withdrawn=0 AND m.review_status='clear' AND (?='' OR e.position=?) AND (?='' OR m.game_version=?) AND (?='' OR m.difficulty=?) AND instr(','||m.category||',',','||?||',')>0 ORDER BY e.score DESC,e.submitted_at ASC LIMIT ? OFFSET ?`).bind(position,position,gameVersion,gameVersion,difficulty,difficulty,category,limit,offset).all();return(result.results||[]).map((row,index)=>({runId:row.run_id,playerName:row.player_name,publicNickname:row.public_nickname,nation:row.nation,position:row.position,clubName:row.club_name,score:Number(row.score),grade:row.grade,seasons:Number(row.seasons),ending:row.ending,submittedAt:Number(row.submitted_at),gameVersion:row.game_version,difficulty:row.difficulty,categories:String(row.category||'overall').split(','),publicDetails:Boolean(row.public_details),rank:offset+index+1}))}
  async withdrawEntry(runId,userId){await this.ensureSchema();const result=await this.db.prepare(`UPDATE leaderboard_metadata SET withdrawn=1 WHERE run_id=? AND user_id=?`).bind(runId,userId).run();return Number(result.meta?.changes||0)===1}
  async updateEntryPrivacy(runId,userId,privacy){await this.ensureSchema();const result=await this.db.prepare(`UPDATE leaderboard_metadata SET public_nickname=?,public_details=? WHERE run_id=? AND user_id=?`).bind(privacy.publicNickname,privacy.publicDetails?1:0,runId,userId).run();return Number(result.meta?.changes||0)===1}
  async reportEntry(report){await this.ensureSchema();await this.db.prepare(`INSERT INTO leaderboard_reports (id,target_run_id,reason,created_at) VALUES (?,?,?,?)`).bind(report.id,report.targetRunId,report.reason,report.createdAt).run()}
}
