const metricMap={
 apps:s=>s.career.careerStats.apps,goals:s=>s.career.careerStats.goals,assists:s=>s.career.careerStats.assists,cleanSheets:s=>s.career.careerStats.cleanSheets,trophies:s=>s.career.careerStats.titles,nationalApps:s=>s.career.careerStats.nationalApps,
 fans:s=>s.fans.local+s.fans.club+s.fans.global,social:s=>s.fans.social,ovr:s=>s.player.ovr,value:s=>s.finance.marketValue,seasons:s=>s.career.season,transfers:s=>s.career.transferHistory.length,
 hatTricks:s=>s.career.careerStats.hatTricks||s.career.records.hatTricks||0,bigGames:s=>s.career.careerStats.bigGames||s.career.records.bigGames||0,goldenBoots:s=>s.career.records.goldenBoots||0,
 playerAwards:s=>s.career.records.playerAwards||0,continentalTitles:s=>s.career.records.continentalTitles||0,worldCups:s=>s.career.records.worldCups||0,ballonDors:s=>s.career.records.ballonDors||0,
 captainSeasons:s=>s.career.records.captainSeasons||0,eliteSeasons:s=>s.career.records.eliteSeasons||0
};
const ss=s=>s.career.seasonStats,c=s=>s.career.careerStats,r=s=>s.career.records||{};
const common=[
 s=>c(s).apps>=1,s=>c(s).apps>=25,s=>c(s).apps>=50,s=>c(s).apps>=100,s=>c(s).apps>=200,s=>s.player.ovr>=80,s=>s.player.ovr>=85,s=>s.player.ovr>=90,s=>c(s).titles>=1,s=>c(s).titles>=5,s=>s.status.coachTrust>=85,s=>s.player.age>=34&&s.player.ovr>=78
];
const positionChecks={
 ST:[s=>c(s).goals>=1,s=>ss(s).goals>=10,s=>c(s).hatTricks>=1,s=>ss(s).goals>=20,s=>ss(s).goals>=30,s=>r(s).goldenBoots>=1,s=>s.player.attrs.phy>=85,s=>s.player.attrs.sho>=90,s=>c(s).goals>=100,s=>c(s).goals>=300,s=>c(s).bigGames>=15,s=>c(s).apps>=400],
 LW:[s=>s.player.attrs.pac>=80,s=>s.player.attrs.dri>=85,s=>c(s).goals>=30,s=>ss(s).goals>=10&&ss(s).assists>=10,s=>s.player.foot==='双足'||s.player.attrs.sho>=86,s=>c(s).bigGames>=8,s=>r(s).assistAwards>=1,s=>ss(s).rating>=7.7,s=>c(s).assists>=100,s=>c(s).bigGames>=20,s=>c(s).apps>=350,s=>s.player.ovr>=90],
 RW:[s=>s.player.attrs.dri>=80,s=>s.player.attrs.sho>=84,s=>c(s).goals>=30,s=>c(s).assists>=50,s=>ss(s).goals>=10&&ss(s).assists>=10,s=>s.player.attrs.pas>=86,s=>c(s).bigGames>=8,s=>r(s).assistAwards>=1,s=>c(s).assists>=100,s=>c(s).bigGames>=20,s=>c(s).apps>=350,s=>s.player.ovr>=90],
 CAM:[s=>c(s).assists>=1,s=>ss(s).assists>=10,s=>s.player.attrs.dri>=85,s=>s.player.attrs.pas>=88,s=>c(s).bigGames>=8,s=>s.player.attrs.sho>=82,s=>r(s).playerAwards>=1,s=>c(s).apps>=200,s=>c(s).assists>=100,s=>ss(s).assists>=20,s=>s.player.ovr>=88,s=>s.player.ovr>=92],
 CM:[s=>c(s).apps>=1,s=>ss(s).assists>=8,s=>s.player.attrs.pas>=82,s=>s.player.attrs.phy>=78,s=>c(s).apps>=100,s=>ss(s).rating>=7.4,s=>c(s).assists>=100,s=>s.relations.teammates.respect>=80,s=>r(s).captainSeasons>=1,s=>c(s).apps>=300,s=>r(s).playerAwards>=1,s=>s.player.ovr>=90],
 CDM:[s=>c(s).apps>=1,s=>s.player.attrs.def>=75,s=>s.player.attrs.phy>=78,s=>ss(s).cleanSheets>=8,s=>c(s).apps>=100,s=>s.player.attrs.pas>=80,s=>c(s).cleanSheets>=50,s=>s.relations.coach.trust>=80,s=>r(s).captainSeasons>=1,s=>c(s).apps>=300,s=>r(s).bestDefenderAwards>=1,s=>s.player.ovr>=88],
 LB:[s=>c(s).apps>=1,s=>s.player.attrs.pac>=78,s=>s.player.attrs.def>=78,s=>ss(s).assists>=6,s=>ss(s).cleanSheets>=10,s=>c(s).apps>=100,s=>c(s).assists>=50,s=>c(s).cleanSheets>=75,s=>r(s).bestDefenderAwards>=1,s=>c(s).apps>=300,s=>r(s).captainSeasons>=1,s=>s.player.ovr>=88],
 RB:[s=>c(s).apps>=1,s=>s.player.attrs.pac>=78,s=>s.player.attrs.def>=78,s=>ss(s).assists>=6,s=>ss(s).cleanSheets>=10,s=>c(s).apps>=100,s=>c(s).assists>=50,s=>c(s).cleanSheets>=75,s=>r(s).bestDefenderAwards>=1,s=>c(s).apps>=300,s=>r(s).captainSeasons>=1,s=>s.player.ovr>=88],
 CB:[s=>c(s).apps>=1,s=>s.player.attrs.def>=78,s=>s.player.attrs.phy>=80,s=>ss(s).cleanSheets>=10,s=>c(s).cleanSheets>=50,s=>c(s).apps>=100,s=>r(s).bestDefenderAwards>=1,s=>c(s).goals>=20,s=>c(s).cleanSheets>=150,s=>r(s).captainSeasons>=2,s=>c(s).apps>=400,s=>s.player.ovr>=90],
 GK:[s=>c(s).cleanSheets>=1,s=>ss(s).cleanSheets>=8,s=>s.player.attrs.pac>=80,s=>s.player.attrs.sho>=82,s=>r(s).goldenGloves>=1,s=>c(s).cleanSheets>=50,s=>c(s).saves>=300,s=>c(s).cleanSheets>=100,s=>c(s).apps>=300,s=>c(s).cleanSheets>=200,s=>r(s).playerAwards>=1,s=>s.player.ovr>=90]
};
function specialCondition(i,s){const checks=[s.career.squadLevel==='一线队',c(s).titles>=1,c(s).titles>=3,c(s).apps>=100,ss(s).goals>=20,ss(s).assists>=15,ss(s).cleanSheets>=12,s.player.ovr>=80,s.player.ovr>=85,s.player.ovr>=90,s.career.transferHistory.length===0&&s.player.age>=30,s.career.transferHistory.length>=5,s.career.transferHistory.length>=9,s.fans.social>=100000,s.fans.social>=1000000,s.finance.marketValue>=50000000,c(s).nationalApps>=1,c(s).nationalApps>=50,c(s).goals>=100,c(s).assists>=100,c(s).cleanSheets>=100,s.player.age>=35&&s.player.ovr>=80,s.status.injury===null&&c(s).apps>=200,s.relations.coach.trust>=85,s.relations.teammates.respect>=85,s.career.clubHistory.length===1&&s.player.age>=32];return Boolean(checks[i%checks.length])}
function hiddenCondition(i,s){const checks=[s.player.nation==='中国'&&s.player.position==='CAM'&&s.player.ovr>=90,s.player.nation==='中国'&&['ST','LW','RW'].includes(s.player.position)&&s.player.ovr>=90,s.career.transferHistory.length===0&&c(s).titles>=5,s.player.age>=38&&s.career.teamRole.includes('核心'),s.career.rejectedClubs.length>=3&&r(s).ballonDors>=1,s.career.transferHistory.length>=10,s.player.potential>=94&&s.player.ovr<80&&s.player.age>=26,s.player.age>=29&&s.player.ovr>=90,c(s).apps<80&&c(s).goals>=30,s.career.history.filter(x=>x.type==='injury').length>=3&&s.player.ovr>=85,c(s).nationalApps>=100,c(s).titles===0&&s.player.ovr>=88,s.fans.social>=10000000,s.finance.cash>=10000000,s.relations.coach.conflict>=70&&c(s).titles>=3];return Boolean(checks[i%checks.length])}
export function evaluateAchievements(save,definitions){const newly=[];for(const a of definitions){if(save.achievements.unlocked.includes(a.id))continue;let ok=false;if(a.type==='metric'){const fn=metricMap[a.metric];ok=fn?fn(save)>=a.value:false}else if(a.type==='position'&&a.position===save.player.position){const checks=positionChecks[a.position]||common;ok=Boolean(checks[a.index%checks.length]?.(save))}else if(a.type==='special')ok=specialCondition(a.index||0,save);else if(a.type==='hidden')ok=hiddenCondition(a.index||0,save);if(ok){save.achievements.unlocked.push(a.id);save.achievements.score+=a.reward||0;newly.push(a)}}return newly}
export function achievementProgress(save,a){if(a.type==='metric'){const current=metricMap[a.metric]?.(save)||0;return{current,target:a.value,ratio:Math.min(1,current/a.value)}}if(a.type==='position'&&a.position===save.player.position){const checks=positionChecks[a.position]||common;const done=Boolean(checks[a.index%checks.length]?.(save));return{current:done?1:0,target:1,ratio:done?1:0}}return{current:save.achievements.unlocked.includes(a.id)?1:0,target:1,ratio:save.achievements.unlocked.includes(a.id)?1:0}}
