import {DeterministicRng} from '../../services/rng.js';
import {clamp} from '../../utils/format.js';
import {applyRelation} from '../relationship/relationshipSystem.js';
import {CAREER_SETTINGS} from '../../app/config.js';

export function marketValue(save,club){const p=save.player;const age=p.age<=21?1.5:p.age<=26?1.25:p.age<=29?1:p.age<=32?.7:.36;const pot=1+Math.max(0,p.potential-p.ovr)*.045;const exposure=.75+club.rep/180;return Math.max(80000,Math.round(Math.exp((p.ovr-52)*.102)*90000*age*pot*exposure))}
function roleFor(player,club){const gap=player.ovr-club.rep;if(gap>=4)return'核心';if(gap>=0)return'主力';if(gap>=-5)return'轮换';return player.age<=21?'未来计划':'替补'}
function offerScore(save,club,current){const p=save.player,s=save.career.seasonStats;let score=p.ovr*.34+p.potential*.16+(s.rating||6)*5+(s.apps||0)*.18+save.fans.mediaHeat*.08+save.status.form*.08;score+=(club.needs.includes(p.position)?8:-3);score-=Math.max(0,club.rep-p.ovr-7)*2.2;score-=save.status.injury?.severity?12:0;score+=(club.youthUsage-50)*.05;score-=Math.abs(club.rep-current.rep)*.05;return score}
export function isTransferWindow(save){return save.career.month===CAREER_SETTINGS.summerWindowMonth||save.career.month===CAREER_SETTINGS.winterWindowMonth}
export function generateOffers(save,repo){
 if(!isTransferWindow(save))return[];if(save.career.pending.offers?.length)return save.career.pending.offers;
 const rng=new DeterministicRng(save.rng.seed,save.rng.state);rng.counter=save.rng.counter||0;const current=repo.getClub(save.career.clubId);const p=save.player;const candidates=repo.clubs.filter(c=>c.id!==current.id&&c.finance>35&&c.rep<=p.ovr+12&&c.rep>=Math.max(48,p.ovr-11)).map(c=>({club:c,score:offerScore(save,c,current)+rng.next()*18})).filter(x=>x.score>58).sort((a,b)=>b.score-a.score).slice(0,20);
 const topScore=candidates[0]?.score||0;const count=clamp(Math.floor((topScore-55)/12)+rng.int(0,2),0,4);const offers=[];
 if(save.career.contract.years<=1&&save.career.month===CAREER_SETTINGS.summerWindowMonth){
   const renewalWage=Math.max(save.finance.weeklyWage,Math.round((900+(p.ovr-50)*680)*(current.finance/72)));
   offers.push({id:`R-${save.career.season}-${current.id}`,type:'续约',clubId:current.id,league:current.leagueCn,role:save.career.teamRole,weeklyWage:Math.round(renewalWage*(.94+rng.next()*.16)),years:rng.int(2,5),signingBonus:Math.round(renewalWage*rng.int(5,14)),releaseClause:current.tier==='S'?0:Math.round(marketValue(save,current)*rng.int(15,25)/10),appearancePromise:save.career.teamRole.includes('核心')?'核心首发':save.career.teamRole.includes('主力')?'稳定首发':'继续竞争一线队位置',developmentPlan:p.age<=21?'续约后继续重点培养':'稳定一线队发展计划',coachInterest:clamp(Math.round(55+save.status.coachTrust*.35),10,98),probability:clamp(Math.round(48+save.relations.management.trust*.35),20,96),status:'待决定',negotiationRound:0,createdSeason:save.career.season,createdMonth:save.career.month});
 }
 for(const {club,score} of candidates.slice(0,count)){const role=roleFor(p,club),baseWage=Math.round((800+(p.ovr-50)*650)*(club.finance/70));offers.push({id:`O-${save.career.season}-${save.career.month}-${club.id}`,type:save.career.contract.years<=0?'自由转会':'永久转会',clubId:club.id,league:club.leagueCn,role,weeklyWage:Math.max(500,baseWage+rng.int(-1000,2500)),years:rng.int(3,5),signingBonus:Math.round(baseWage*rng.int(8,20)),releaseClause:club.tier==='S'?0:Math.round(marketValue(save,current)*rng.int(14,25)/10),appearancePromise:role==='核心'?'核心首发':role==='主力'?'稳定首发':role==='轮换'?'每赛季不少于20次出场':'先租借或杯赛培养',developmentPlan:p.age<=21?'重点青年发展计划':'一线队即战力计划',coachInterest:clamp(Math.round(score),0,100),probability:clamp(Math.round(40+(score-58)*2),10,95),status:'待决定',negotiationRound:0,createdSeason:save.career.season,createdMonth:save.career.month});}
 save.career.pending.offers=offers;save.rng=rng.snapshot();return offers;
}
export function respondOffer(save,repo,offerId,action){const offer=save.career.pending.offers.find(x=>x.id===offerId);if(!offer)throw new Error('报价不存在');const rng=new DeterministicRng(save.rng.seed,save.rng.state);rng.counter=save.rng.counter||0;const target=repo.getClub(offer.clubId);
 if(action==='reject'){offer.status='已拒绝';save.career.rejectedClubs.push(target.id);if(offer.type==='续约'&&save.career.contract.years<=0)save.career.contract.type='合同到期';applyRelation(save,'agent',{trust:-2});}
 if(action==='defer'){offer.status='暂缓';offer.probability=clamp(offer.probability-8,5,95)}
 if(action==='accept'){offer.status='已接受';if(offer.type==='续约'){save.career.contract={type:'职业合同',years:offer.years,weeklyWage:offer.weeklyWage,releaseClause:offer.releaseClause,appearancePromise:offer.appearancePromise};save.finance.weeklyWage=offer.weeklyWage;save.finance.cash+=offer.signingBonus;save.career.pending.offers=[];applyRelation(save,'management',{trust:6,respect:4});}else{save.career.transferHistory.push({year:save.career.year,from:save.career.clubId,to:target.id,type:offer.type||'永久转会',fee:marketValue(save,repo.getClub(save.career.clubId))});save.career.clubId=target.id;save.career.clubHistory.push(target.id);save.career.squadLevel='一线队';save.career.teamRole=offer.role;save.career.contract={type:'职业合同',years:offer.years,weeklyWage:offer.weeklyWage,releaseClause:offer.releaseClause,appearancePromise:offer.appearancePromise};save.finance.weeklyWage=offer.weeklyWage;save.finance.cash+=offer.signingBonus;save.status.coachTrust=50;save.career.pending.offers=[];applyRelation(save,'management',{trust:8,respect:5});}}
 if(action==='negotiateWage'||action==='negotiateRole'||action==='loan'||action==='clause'){
  offer.negotiationRound++;const difficulty=action==='negotiateRole'?65:action==='loan'?58:60;const chance=clamp((offer.probability+save.relations.agent.trust*.25-difficulty)/100,.1,.82);if(rng.bool(chance)){if(action==='negotiateWage')offer.weeklyWage=Math.round(offer.weeklyWage*1.12);if(action==='negotiateRole')offer.role=offer.role==='未来计划'?'轮换':offer.role==='轮换'?'主力':'核心';if(action==='clause')offer.releaseClause=Math.round(offer.releaseClause*.8);if(action==='loan'){offer.type='租借';offer.years=1;offer.appearancePromise='优先保证出场时间'}offer.status='谈判成功'}else{offer.status=rng.bool(.35)?'谈判破裂':'谈判未果';offer.probability=clamp(offer.probability-15,0,95)}
 }
 save.rng=rng.snapshot();return offer}
export function submitInterest(save,repo,clubId){
 const previous=[...save.career.history].reverse().find(x=>x.type==='interest'&&x.clubId===clubId&&x.season===save.career.season&&x.month===save.career.month);if(previous)return{club:repo.getClub(clubId),status:previous.status,score:previous.score,offer:save.career.pending.offers.find(x=>x.sourceInterest===previous.id)||null};
 const club=repo.getClub(clubId),current=repo.getClub(save.career.clubId);const rng=new DeterministicRng(save.rng.seed,save.rng.state);rng.counter=save.rng.counter||0;const score=offerScore(save,club,current);let status;if(score>78&&rng.bool(.72))status='接受接触';else if(score>65&&rng.bool(.55))status=rng.pick(['要求试训','只提供租借','推迟决定']);else status=rng.pick(['位置不需要','预算不足','竞技水平暂未达到']);
 const record={id:`I-${save.career.season}-${save.career.month}-${club.id}`,type:'interest',year:save.career.year,season:save.career.season,month:save.career.month,clubId,status,score:Math.round(score)};save.career.history.push(record);let offer=null;
 if(['接受接触','只提供租借'].includes(status)&&isTransferWindow(save)){
   const role=roleFor(save.player,club),baseWage=Math.round((800+(save.player.ovr-50)*620)*(club.finance/70));offer={id:`IO-${save.career.season}-${save.career.month}-${club.id}`,sourceInterest:record.id,type:status==='只提供租借'?'租借':'永久转会',clubId:club.id,league:club.leagueCn,role,weeklyWage:Math.max(500,baseWage),years:status==='只提供租借'?1:rng.int(3,5),signingBonus:status==='只提供租借'?0:Math.round(baseWage*rng.int(6,12)),releaseClause:club.tier==='S'?0:Math.round(marketValue(save,current)*1.8),appearancePromise:status==='只提供租借'?'优先保证轮换出场':role==='主力'?'稳定首发':'竞争一线队位置',developmentPlan:save.player.age<=21?'重点成长计划':'一线队适应计划',coachInterest:clamp(Math.round(score),0,100),probability:clamp(Math.round(45+(score-60)*1.8),10,95),status:'待决定',negotiationRound:0,createdSeason:save.career.season,createdMonth:save.career.month};if(!save.career.pending.offers.some(x=>x.id===offer.id))save.career.pending.offers.push(offer)
 }
 save.rng=rng.snapshot();return{club,status,score:Math.round(score),offer}
}
