import { icon } from '../components/icons.js';
import { radarChart } from '../components/radar.js';
import { crestSvg } from '../components/clubCrest.js';
import { dataRepository } from '../services/dataRepository.js';
import { computeOverall } from '../core/playerDevelopmentEngine.js';
import { createRealFixtures } from '../core/simulationController.js';
import { generatePlayerName, generateStartingClubOffers, validatePlayerName } from '../services/playerIdentity.js';
import { playStyleEligibility, traitEligibility } from '../core/positionResolver.js';
import { PLAYER_STYLES, PLAYER_STYLE_DEFINITIONS, SECONDARY_TRAITS } from '../data/playerProfiles.js';

const positions = [
  { id: 'ST', name: '中锋', group: '前锋', x: 50, y: 12, desc: '终结、跑位、争顶', focus: '射门 · 速度 · 身体' },
  { id: 'LW', name: '左边锋', group: '边锋', x: 20, y: 24, desc: '突破、内切、创造宽度', focus: '速度 · 盘带 · 射门' },
  { id: 'RW', name: '右边锋', group: '边锋', x: 80, y: 24, desc: '一对一、传中、内切', focus: '速度 · 盘带 · 传球' },
  { id: 'CAM', name: '前腰', group: '前场', x: 50, y: 31, desc: '最后一传、创造机会', focus: '传球 · 盘带 · 射门' },
  { id: 'LM', name: '左前卫', group: '中场', x: 20, y: 45, desc: '边路组织、回防、传中', focus: '传球 · 速度 · 防守' },
  { id: 'RM', name: '右前卫', group: '中场', x: 80, y: 45, desc: '边路组织、回防、协作', focus: '传球 · 速度 · 盘带' },
  { id: 'CM', name: '中前卫', group: '中场', x: 50, y: 46, desc: '控制节奏、覆盖、反抢', focus: '传球 · 盘带 · 身体' },
  { id: 'CDM', name: '后腰', group: '中场', x: 50, y: 59, desc: '拦截、卡位、防守转换', focus: '防守 · 传球 · 身体' },
  { id: 'LB', name: '左后卫', group: '后卫', x: 18, y: 72, desc: '回防、套边、对位边锋', focus: '防守 · 速度 · 传球' },
  { id: 'RB', name: '右后卫', group: '后卫', x: 82, y: 72, desc: '回防、内收、传中', focus: '防守 · 速度 · 传球' },
  { id: 'CB', name: '中后卫', group: '后卫', x: 50, y: 76, desc: '盯人、补位、后场组织', focus: '防守 · 身体 · 传球' },
  { id: 'GK', name: '门将', group: '门将', x: 50, y: 91, desc: '扑救、出击、指挥防线', focus: '扑救 · 反应 · 站位' }
];
const styles = PLAYER_STYLES;
const countries = ['中国', '日本', '韩国', '英格兰', '西班牙', '葡萄牙', '法国', '德国', '意大利', '荷兰', '比利时', '巴西', '阿根廷', '美国', '墨西哥', '沙特阿拉伯', '土耳其', '尼日利亚', '加纳', '塞内加尔', '摩洛哥', '埃及'];
const birthplaceMap = { 中国: ['辽宁', '山东', '上海', '北京', '广东', '河南河北', '新疆', '江浙', '巴蜀'] };
const personalities = ['沉着自律', '外向自信', '低调务实', '好胜果断', '团队优先', '创造力强'];
const families = ['普通工薪家庭', '体育家庭', '单亲家庭', '小城商户家庭', '足球教练家庭', '跨国家庭'];
const academies = ['校园足球起步', '地方青训中心', '职业俱乐部梯队', '街头足球出身', '海外足球学校', '地区选拔队'];

export const playerStylesForPosition = position => playStyleEligibility.filter(position, PLAYER_STYLE_DEFINITIONS);
export const secondaryTraitsForPosition = position => traitEligibility.filter(position, SECONDARY_TRAITS);
function normalizeSelections(draft) {
  draft.style = playStyleEligibility.resolve(draft.position, draft.style, PLAYER_STYLE_DEFINITIONS);
  draft.secondaryTrait = traitEligibility.resolve(draft.position, draft.secondaryTrait, SECONDARY_TRAITS);
  return draft;
}

export function createPlayerWizard(app) {
  let step = 0;
  let locked = false;
  const state = app.store.get();
  const draft = { name: '', shirtName: '', country: '中国', birthplace: '上海', height: 178, weight: 70, foot: '右脚', number: 18, position: 'CM', style: '全能中场', secondaryTrait: '稳定发挥', lockName: false, lockCountry: false, previewSeed: state.creation?.seed || `${state.createdAt}:identity` };
  const root = document.createElement('div');
  root.className = 'wizard-shell';
  const labels = ['身份', '位置', '风格', '球员数据', '青年队'];
  const render = () => {
    const report = scoutDraft(draft);
    const identity = generatedIdentity(draft);
    root.innerHTML = `<div class="wizard"><div class="wizard-top"><div><div class="card-kicker">绿茵浮沉 · 创建球员</div><h1 class="page-title">${labels[step]}</h1></div><span class="badge blue">${step + 1}/${labels.length}</span></div><div class="stepper">${labels.map((_, index) => `<span class="step-dot ${index <= step ? 'active' : ''}"></span>`).join('')}</div><div class="wizard-body">${body(report, identity)}</div>${step === 4 ? '<div class="card-copy wizard-hint">点击球队卡片即可签约并进入生涯</div>' : `<div class="card-row wizard-actions"><button class="app-button ghost" data-prev ${step === 0 ? 'disabled' : ''}>${icon('back', 'sm')}上一步</button><button class="app-button primary" data-next>${step === 3 ? '查看球队机会' : '继续'}${icon('chevron', 'sm')}</button></div>`}</div>`;
    bind();
  };
  const body = (report, identity) => {
    if (step === 0) return `<section class="surface-card identity-step"><div class="form-grid">${field('姓名（可留空）', 'name', draft.name, 'text', identity.displayName)}${field('球衣名（可留空）', 'shirtName', draft.shirtName, 'text', identity.displayName.slice(-8))}${selectField('国家或地区', 'country', countries, draft.country)}${selectField('出生地 / 地区', 'birthplace', birthplaces(draft.country), draft.birthplace)}${field('身高（cm）', 'height', draft.height, 'number')}${field('体重（kg）', 'weight', draft.weight, 'number')}${selectField('惯用脚', 'foot', ['右脚', '左脚', '双足'], draft.foot)}${field('球衣号码', 'number', draft.number, 'number')}</div><div class="identity-preview"><div><div class="card-kicker">${draft.name.trim() ? '手动姓名' : '国家姓名预览'}</div><strong>${escapeHtml(identity.displayName)}</strong><p class="card-copy">${draft.name.trim() ? '将使用你输入的姓名' : '按所选国家的姓名顺序与文字规则生成，进入生涯后固定保存'}</p></div></div></section>`;
    if (step === 1) { const selected = positionInfo(draft.position); return `<section class="surface-card position-step position-step--wide"><div class="position-head"><div><div class="card-kicker">选择位置 · ${selected.group}</div><h2 class="card-title">${selected.name}（${selected.id}）</h2><p class="card-copy">${selected.desc} · 典型属性：${selected.focus}</p></div><span class="badge ${selected.id === 'GK' ? 'blue' : 'green'}">${selected.id === 'GK' ? '独立门将事件库' : '位置事件联动'}</span></div><div class="pitch pitch--wide ${selected.id === 'GK' ? 'pitch--keeper' : ''}">${positions.map(position => `<button class="position-node position-node--wide ${draft.position === position.id ? 'active' : ''} position-${position.group}" style="left:${position.x}%;top:${position.y}%" data-position="${position.id}" aria-label="${position.name} ${position.id}"><strong>${position.id}</strong><small>${position.name}</small></button>`).join('')}</div><div class="position-detail"><strong>${selected.name}</strong><span>${selected.desc}</span><small>${selected.id === 'GK' ? '门线、禁区和出球训练将使用门将专属内容。' : `比赛职责和事件会按${selected.name}位置筛选。`}</small></div></section>`; }
    if (step === 2) { const options = playerStylesForPosition(draft.position), selected = styles[draft.style]; return `<section class="surface-card"><div class="choice-grid style-profile-grid">${options.map(item => `<button class="choice-card style-profile-card ${draft.style === item.id ? 'active' : ''}" data-style="${item.id}">${icon(item.positions.includes('GK') ? 'goalkeeper' : item.positions.some(pos => ['CB','CDM'].includes(pos)) ? 'defending' : item.positions.some(pos => ['CAM','CM'].includes(pos)) ? 'passing' : 'shooting')}<h3>${item.id}</h3><p>${item.positions.join(' / ')} · ${item.bonus}</p><small>弱点：${item.weakness}</small><span>适配 ${styleFit(item.id, draft)}%</span></button>`).join('')}</div><div class="style-profile-detail"><div><span>核心说明</span><strong>${selected.bonus}</strong></div><div><span>推荐身体</span><strong>${selected.body}</strong></div><div><span>关键属性</span><strong>${selected.keys}</strong></div><div><span>场上行为</span><strong>${selected.behavior}</strong></div></div>${selectField('次要特质', 'secondaryTrait', secondaryTraitsForPosition(draft.position).map(item => item.name), draft.secondaryTrait)}</section>`; }
    if (step === 3) { const remaining = Math.max(0, 10 - Number(app.store.get().creation?.rerollsUsed || 0)); return `<section class="surface-card player-data-card ${report.potential >= 89 ? 'is-rare-result' : ''}"><div class="player-data-toolbar"><div><div class="card-kicker">完整随机档案</div><h2 class="card-title">球员数据</h2><p class="card-copy">剩余次数：${remaining}</p></div><button class="app-button secondary" data-reroll ${remaining ? '' : 'disabled'}>${icon('refresh','sm')}${remaining ? '重新生成' : '次数已用完'}</button></div><div class="reroll-locks"><label><input type="checkbox" data-lock="name" ${draft.lockName ? 'checked' : ''}>锁定姓名</label><label><input type="checkbox" data-lock="country" ${draft.lockCountry ? 'checked' : ''}>锁定国籍</label></div><div class="grid-2"><div class="scout-reveal"><div class="card-kicker">${icon('analytics', 'sm')} 球探可信度 ${report.confidence}%</div><div class="rarity">${report.tier}</div><p class="card-copy">${identity.displayName} · ${draft.country} · ${positionInfo(draft.position).name}</p><div class="tag-row"><span class="badge green">优势 ${cn(report.strengths[0])}</span><span class="badge green">优势 ${cn(report.strengths[1])}</span><span class="badge orange">短板 ${cn(report.weaknesses[0])}</span></div></div>${radarChart(report.stats, report.stats, report.potential, draft.position)}</div><div class="player-data-facts">${[['号码',draft.number],['身体',`${draft.height}cm · ${draft.weight}kg`],['惯用脚',draft.foot],['比赛风格',draft.style],['次要特质',draft.secondaryTrait],['性格',report.personality],['家庭背景',report.family],['青训经历',report.academy]].map(([label,value])=>`<div><span>${label}</span><strong>${escapeHtml(value)}</strong></div>`).join('')}</div></section>`; }
    const offers = academyClubs(draft, report);
    return `<section class="surface-card club-selection-step"><div class="card-row"><div><div class="card-kicker">真实球队机会 · ${draft.country}</div><h2 class="card-title">选择你的起点</h2><p class="card-copy">每张卡的青训水平、出场机会、合同和位置需求不同。</p></div><span class="badge blue">${offers.length} 个选项</span></div><div class="club-offer-grid">${offers.map(item => clubOfferCard(item)).join('')}</div></section>`;
  };
  const bind = () => {
    root.querySelectorAll('input[name], select[name]').forEach(element => element.addEventListener('input', () => { draft[element.name] = element.type === 'number' ? Number(element.value) : element.value; if (element.name === 'country') { draft.birthplace = birthplaces(draft.country)[0]; render(); } }));
    root.querySelectorAll('[data-lock]').forEach(element => element.addEventListener('change', () => { const key = element.dataset.lock; draft[`lock${key[0].toUpperCase()}${key.slice(1)}`] = element.checked; if (key === 'name' && element.checked && !draft.name.trim()) draft.name = generatedIdentity(draft).displayName; render(); }));
    root.querySelectorAll('[data-position]').forEach(element => { element.onclick = () => { draft.position = element.dataset.position; normalizeSelections(draft); navigator.vibrate?.(16); render(); }; });
    root.querySelectorAll('[data-style]').forEach(element => { element.onclick = () => { draft.style = element.dataset.style; app.feedback.emit('select', draft.style); render(); }; });
    root.querySelector('[data-reroll]')?.addEventListener('click', () => { const used = Number(app.store.get().creation?.rerollsUsed || 0); if (used >= 10) return app.feedback.emit('failure', '重新生成次数已用完'); Object.assign(draft, rerollPlayerDraft(draft, used + 1)); app.store.set(current => { current.creation.rerollsUsed = used + 1; current.creation.seed = draft.previewSeed; return current; }); const report = scoutDraft(draft); app.feedback.emit(report.potential >= 89 ? 'newTrait' : 'select', report.potential >= 89 ? `${report.tier}潜力` : `已重新生成，剩余 ${9 - used} 次`); render(); });
    root.querySelectorAll('[data-club]').forEach(element => { element.onclick = () => { if (locked || element.disabled) return; locked = true; root.classList.add('is-signing'); root.querySelectorAll('[data-club]').forEach(card => { card.disabled = true; }); app.feedback.emit('clubSelect', element.dataset.clubName); window.setTimeout(() => startCareer(element.dataset.club), 440); }; });
    root.querySelector('[data-prev]')?.addEventListener('click', () => { if (step > 0) { step -= 1; render(); } });
    root.querySelector('[data-next]')?.addEventListener('click', () => {
      if (step === 0) { const check = validatePlayerName(draft.name); if (!check.valid) return app.feedback.emit('failure', check.error); }
      if (step < 4) { step += 1; app.feedback.emit(step === 3 ? 'scoutReport' : 'select', labels[step]); render(); }
    });
  };
  const startCareer = clubId => {
    const report = scoutDraft(draft); const identity = generatedIdentity(draft); const item = academyClubs(draft, report).find(offer => offer.clubId === clubId); if (!item?.eligible) { locked = false; app.feedback.emit('failure', item ? `综合 ${item.score}，未达到签约门槛 ${item.required}` : '该球队机会已失效'); return render(); } const club = item.club;
    const seasonYear = Number(String(state.simulation?.date || '2026').slice(0, 4));
    const player = { ...draft, name: identity.displayName, displayName: identity.displayName, nameParts: identity, nameSource: draft.name.trim() ? 'manual' : 'generated', shirtName: draft.shirtName.trim() || identity.familyName || identity.givenName, nation: draft.country, country: draft.country, birthplace: draft.birthplace, positionName: positionInfo(draft.position).name, birthDate: generatedBirth(`${state.createdAt}:${identity.displayName}:${draft.country}`), club: club.cn || club.name, clubId: club.id, crestPath: club.crest || null, league: club.leagueCn || club.league, leagueLevel: Math.max(1, Math.min(5, Math.ceil(Number(club.rep || club.reputation || 60) / 20))), team: item.squad, age: 16, stats: report.stats, potential: report.potential, ovr: computeOverall(report.stats, draft.position), fatigue: 18, morale: 72, fitness: 84, coachTrust: 52, status: '健康', previousStats: { ...report.stats }, squad: dataRepository.registry?.rosterForClub(club.id, { seed: identity.displayName, seasonYear }) || [] };
    app.store.set(current => { current.player = player; current.training.facilityLevel = Math.max(1, Math.min(5, Math.ceil(Number(club.youth || club.academy || 60) / 20))); current.season.startOvr = player.ovr; current.season.startMarketValue = current.career.marketValue; current.transfer.club = club.id; current.transfer.country = club.country; current.transfer.league = club.leagueCn || club.league; current.schedule = createRealFixtures(current, dataRepository.clubs || []); current.career.history.push({ date: current.simulation.date, type: '签约', text: `加入${player.club}${item.reason ? `：${item.reason}` : ''}`, clubId: club.id, crestPath: player.crestPath }); current.news.items.unshift({ id: `welcome-${current.createdAt}`, date: current.simulation.date, type: '生涯', title: '青训生涯正式开始', copy: `${player.name} 以 16 岁身份加入${player.club}。`, read: false }); return current; });
    app.feedback.emit('promoted', `正式加入${player.club}`); app.mount();
  };
  render();
  return root;
}

export function scoutDraft(draft) { normalizeSelections(draft); const random = seeded(`${draft.previewSeed}-${draft.name}-${draft.country}-${draft.position}-${draft.style}`); const selected = styles[draft.style]; const mods = bodyAdjustments(draft); const stats = Object.fromEntries(Object.entries(selected.stats).map(([key, value]) => [key, Math.max(35, Math.min(78, Math.round(value + Number(mods[key] || 0) + (random() - .5) * 8)))])); const potential = Math.round(70 + random() * 24); return { stats, potential, tier: potential >= 93 ? '传奇迹象' : potential >= 89 ? '世代' : potential >= 86 ? '顶级' : potential >= 82 ? '精英' : potential >= 78 ? '优秀' : '普通', confidence: Math.round(72 + random() * 23), personality: pick(personalities, random), family: pick(families, random), academy: pick(academies, random), strengths: Object.entries(stats).sort((a, b) => b[1] - a[1]).slice(0, 2).map(([key]) => key), weaknesses: Object.entries(stats).sort((a, b) => a[1] - b[1]).slice(0, 2).map(([key]) => key) }; }
export function rerollPlayerDraft(draft, index) { const next = { ...draft, previewSeed: `${draft.previewSeed}:reroll:${index}` }; const random = seeded(next.previewSeed); if (!next.lockCountry) next.country = pick(countries, random); if (!next.lockName) { next.name = ''; next.shirtName = ''; } next.position = pick(positions, random).id; next.style = pick(playerStylesForPosition(next.position), random).id; next.secondaryTrait = pick(secondaryTraitsForPosition(next.position), random).id; next.birthplace = pick(birthplaces(next.country), random); const [minHeight, maxHeight] = heightRange(next.position); next.height = minHeight + Math.floor(random() * (maxHeight - minHeight + 1)); next.weight = Math.max(55, Math.min(98, Math.round(next.height - 105 + positionWeight(next.position) + (random() - .5) * 8))); next.foot = random() < .68 ? '右脚' : random() < .88 ? '左脚' : '双足'; next.number = pick(numberPool(next.position), random); return next; }
function academyClubs(draft, report) { return generateStartingClubOffers({ ...draft, nation: draft.country, ovr: computeOverall(report.stats, draft.position), potential: report.potential }, { clubs: dataRepository.clubs || [] }, `${draft.previewSeed}:${draft.country}:${draft.position}`); }
function generatedIdentity(draft) { if (draft.name.trim()) return { displayName: draft.name.trim(), givenName: '', familyName: '' }; return generatePlayerName(draft.country, draft.previewSeed, dataRepository.nameProfiles || {}); }
function clubOfferCard(item) { const club = item.club; const crest = `<span class="club-offer-crest">${crestSvg(club,{size:54,decorative:true})}</span>`; return `<button class="club-offer-card ${item.type === '家乡球队' ? 'club-offer-card--home' : ''} ${item.eligible ? '' : 'is-ineligible'}" data-club="${escapeHtml(item.clubId)}" data-club-name="${escapeHtml(club.cn || club.name)}" ${item.eligible ? '' : 'disabled'}><span class="club-offer-top">${crest}<span class="badge ${item.eligible ? item.type === '强队青训' ? 'purple' : 'blue' : 'red'}">${item.eligible ? escapeHtml(item.type) : '未达门槛'}</span></span><strong>${escapeHtml(club.cn || club.name)}</strong><small>${escapeHtml(club.country)} · ${escapeHtml(club.leagueCn || club.league || '本国联赛')}</small><span class="club-offer-copy">${escapeHtml(item.reason)}</span><span class="club-offer-metrics">综合 ${item.score} / 门槛 ${item.required} · ${escapeHtml(item.positionFit)}</span><span class="club-offer-contract">${escapeHtml(item.squad)} · ${escapeHtml(item.contract)} · 周薪 €${Number(item.weeklyWage).toLocaleString('en-US')}</span></button>`; }
function styleFit(name, draft) { const style = styles[name]; let score = playStyleEligibility.eligible(draft.position, style) ? 76 : style.positions.some(position => positionInfo(position).group === positionInfo(draft.position).group) ? 58 : 38; if (name === '支点中锋' || name === '出球后卫' || name === '清道夫门将') score += Math.round((Number(draft.height) - 178) / 2); if (name === '速度型边锋' || name === '内切攻击手') score += Math.round((178 - Number(draft.height)) / 3); return Math.max(25, Math.min(98, score)); }
function bodyAdjustments(draft) { const height = Number(draft.height || 178), weight = Number(draft.weight || 70), tall = (height - 178) / 5, strong = (weight - (height - 108)) / 4; if (draft.position === 'GK') return { speed: -Math.max(0, tall), passing: 1, defending: 4 + tall, physical: 3 + tall + strong }; if (draft.position === 'CB') return { speed: -Math.max(0, tall), passing: 1, defending: 4 + tall, physical: 4 + tall + strong }; if (draft.position === 'ST') return { speed: -Math.max(0, tall - 1), shooting: 3, dribbling: -Math.max(0, tall / 2), physical: 2 + tall + strong }; if (['LW','RW'].includes(draft.position)) return { speed: 4 - tall, shooting: 1, dribbling: 3 - Math.max(0, tall / 2), physical: strong - 2 }; if (['LB','RB'].includes(draft.position)) return { speed: 3 - tall / 2, passing: 1, defending: 2, physical: strong }; if (draft.position === 'CDM') return { passing: 2, defending: 3, physical: 3 + strong }; return { passing: 2, dribbling: 1, physical: strong }; }
function heightRange(position) { if (position === 'GK') return [184, 199]; if (position === 'CB') return [181, 197]; if (position === 'ST') return [174, 194]; if (['LW','RW'].includes(position)) return [165, 184]; if (['LB','RB'].includes(position)) return [168, 188]; return [168, 190]; }
function positionWeight(position) { return position === 'GK' || position === 'CB' ? 7 : position === 'ST' ? 4 : ['LW','RW'].includes(position) ? -3 : 0; }
function numberPool(position) { return position === 'GK' ? [1,12,13,22,25] : position === 'ST' ? [9,10,18,19,21] : ['LW','RW'].includes(position) ? [7,11,17,20,23] : ['CB','LB','RB'].includes(position) ? [2,3,4,5,15] : [6,8,10,14,16,18]; }
function pick(items, random) { return items[Math.floor(random() * items.length)] || items[0]; }
function positionInfo(id) { return positions.find(item => item.id === id) || positions[6]; }
function birthplaces(country) { return birthplaceMap[country] || [...new Set((dataRepository.clubs || []).filter(club => club.country === country && club.city).map(club => club.city))].slice(0, 8).concat(country).slice(0, 8); }
function seeded(seed) { let value = 0; for (const char of String(seed)) value = (value * 31 + char.codePointAt(0)) >>> 0; return () => ((value = Math.imul(1664525, value) + 1013904223 >>> 0) / 4294967296); }
function generatedBirth(seed) { const random = seeded(seed); return `2009-${String(1 + Math.floor(random() * 12)).padStart(2, '0')}-${String(1 + Math.floor(random() * 28)).padStart(2, '0')}`; }
function field(label, name, value, type = 'text', placeholder = '') { const id = `player-${name}`; return `<div class="field field--${type}"><label for="${id}">${label}</label><input id="${id}" class="input" name="${name}" type="${type}" value="${escapeHtml(value ?? '')}" placeholder="${escapeHtml(placeholder)}" /></div>`; }
function selectField(label, name, options, value) { return `<div class="field"><label for="player-${name}">${label}</label><select id="player-${name}" class="input" name="${name}">${options.map(option => `<option ${option === value ? 'selected' : ''}>${escapeHtml(option)}</option>`).join('')}</select></div>`; }
function styleCopy(name) { return { 爆发型: '速度和纵向冲击优先', 技术型: '控球、变向和小空间处理', 组织型: '视野、传球与节奏控制', 终结型: '跑位、射门和禁区效率', 防守型: '站位、拦截与身体对抗', 全能型: '各项均衡，适应多位置' }[name]; }
function cn(key) { return { speed: '速度', shooting: '射门', passing: '传球', dribbling: '盘带', defending: '防守', physical: '身体' }[key] || key; }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
