import {el,button,clear} from '../utils/dom.js';
import {generateMatch,resolveMatch} from '../systems/match/matchSystem.js';
import {markMatchDone} from '../systems/career/cycleSystem.js';
import {showToast} from '../components/toast.js';

export function renderMatchPage(container,ctx){
  const {store,repo,navigate}=ctx,save=store.state;clear(container);const page=el('section',{className:'page match-page'});
  if(!save.career.phase?.eventDone&&!save.career.pending.match){page.append(el('section',{className:'empty-state glass-card'},[el('div',{className:'empty-icon',text:'⚽'}),el('h2',{text:'本阶段比赛尚未解锁'}),el('p',{text:'先回到生涯页完成训练和职业事件，再进入比赛关键节点。'}),button('返回生涯',{className:'button button--primary',onClick:()=>navigate('career')})]));container.append(page);return()=>{}}
  const match=generateMatch(save,repo);const current=repo.getClub(save.career.clubId),opponent=repo.getClub(match.opponentId);
  page.append(headerCard(match,current,opponent),match.resolved?resultView(match,current,opponent):choiceView(match,current,opponent));container.append(page);
  if(!match.resolved){page.querySelectorAll('[data-match-choice]').forEach(btn=>btn.addEventListener('click',()=>{const result=resolveMatch(save,repo,btn.dataset.matchChoice);markMatchDone(save);store.update(()=>{},'match-resolved',result);ctx.refresh();showToast(`比赛结束：评分 ${result.playerResult.rating}`,{type:'success'})}))}
  return()=>{};
}
function headerCard(match,current,opponent){const result=match.score;return el('section',{className:'glass-card match-hero'},[el('div',{className:'section-heading'},[el('div',{},[el('span',{className:'eyebrow',text:match.importance}),el('h1',{text:`${current.cn} 对阵 ${opponent.cn}`})]),el('span',{className:'tag tag--accent',text:match.home?'主场':'客场'})]),el('div',{className:'scoreboard'},[clubMark(current),el('div',{className:'score-center'},[el('strong',{text:result?`${result[0]} : ${result[1]}`:'对'}),el('small',{text:`${match.weather} · ${match.starts?'首发':match.substitute?'替补待命':'未进入名单'}`})]),clubMark(opponent)])])}
function clubMark(club){return el('div',{className:'score-club'},[el('span',{className:'club-mark',text:club.code||club.cn.slice(0,1)}),el('b',{text:club.cn})])}
function choiceView(match,current,opponent){const wrap=el('div',{className:'match-layout'});const info=el('section',{className:'glass-card match-brief'},[el('h2',{text:'关键比赛节点'}),el('p',{text:scenarioText(match)}),el('div',{className:'tag-row'},[el('span',{className:'tag',text:`天气：${match.weather}`}),el('span',{className:'tag',text:`身份：${match.starts?'首发':match.substitute?'替补':'观战'}`}),el('span',{className:'tag',text:`重要性：${match.importance}`})])]);const list=el('div',{className:'match-choices'});match.keyChoices.forEach(c=>{const b=button('',{className:'match-choice'});b.dataset.matchChoice=c.id;b.append(el('strong',{text:c.text}),el('span',{text:c.hint}));list.append(b)});info.append(list);wrap.append(info,el('section',{className:'glass-card tactic-card'},[el('span',{className:'eyebrow',text:'赛前提示'}),el('h3',{text:current.tactic}),el('p',{text:`对手防守 ${opponent.defense}，进攻 ${opponent.attack}。你的体能、士气、位置属性和教练信任会共同影响关键选择。`}),el('p',{className:'muted',text:'选择一旦提交即写入存档，刷新不会改变结果。'})]));return wrap}
function resultView(match,current,opponent){const r=match.playerResult;const wrap=el('div',{className:'match-result-layout'});const summary=el('section',{className:'glass-card match-summary'},[el('span',{className:'eyebrow',text:'比赛评分'}),el('div',{className:'rating-orb',text:String(r.rating)}),el('h2',{text:r.played?'你的比赛表现':'本场未获得出场机会'}),el('div',{className:'metric-grid'},[metric('出场时间',`${r.minutes}分钟`),metric('进球',r.goals),metric('助攻',r.assists),metric('关键传球',r.keyPasses),metric('抢断',r.tackles),metric('扑救',r.saves)])]);const timeline=el('section',{className:'glass-card timeline-card'},[el('div',{className:'section-heading'},[el('div',{},[el('span',{className:'eyebrow',text:'比赛时间线'}),el('h2',{text:'关键事件'})]),el('small',{className:'muted',text:`${current.cn} ${match.score[0]}-${match.score[1]} ${opponent.cn}`})])]);const list=el('div',{className:'timeline-list'});match.timeline.forEach(t=>list.append(el('div',{className:'timeline-item'},[el('span',{className:'timeline-minute',text:`${t.minute}'`}),el('div',{},[el('strong',{text:t.type}),el('small',{text:t.text||t.team})])])));timeline.append(list);wrap.append(summary,timeline);return wrap}
function metric(label,value){return el('div',{className:'metric'},[el('small',{text:label}),el('strong',{text:String(value)})])}
function scenarioText(match){if(!match.starts&&!match.substitute)return'你没有进入本场名单。仍需观察战术执行，并等待下一次训练和比赛机会。';if(match.substitute)return`比赛进入后半段，教练准备在第 ${match.minute} 分钟左右派你登场。你需要决定上场后的第一策略。`;return'比赛进入关键阶段，球权来到你的区域。不同选择会改变个人评分、球队结果和转会关注。'}
