import {el,button,clear} from '../utils/dom.js';
import {createPlayerCard} from '../components/playerCard.js';
import {achievementProgress} from '../systems/achievement/achievementSystem.js';
import {RELATION_KEYS,RELATION_LABELS,relationshipScore} from '../systems/relationship/relationshipSystem.js';
import {formatNumber,formatMoney} from '../utils/format.js';
import {openSheet} from '../components/sheet.js';
import {showToast} from '../components/toast.js';
import {saveManager} from '../services/storage/saveManager.js';
import {getTheme,applyTheme} from '../app/theme.js';
import {POSITION_CONFIG} from '../app/config.js';

export function renderProfilePage(container,ctx){
  const {store,repo,onReturnToSlots}=ctx,save=store.state,club=repo.getClub(save.career.clubId);clear(container);const page=el('section',{className:'page'});page.append(el('div',{className:'profile-grid'},[createPlayerCard(save,club,{compact:true}),careerSummary(save,repo)]),relations(save),achievements(save,repo),settings(save,store,onReturnToSlots));container.append(page);return()=>{}
}
function careerSummary(save,repo){const c=save.career.careerStats,position=POSITION_CONFIG[save.player.position]?.name||'未知位置',notes=save.meta?.migrationNotes||[];return el('section',{className:'glass-card profile-summary'},[el('span',{className:'eyebrow',text:'生涯档案'}),el('h1',{text:save.player.name}),el('p',{text:`${save.player.nation} · ${position} · ${save.player.foot} · ${save.player.height}厘米 / ${save.player.weight}公斤`}),el('div',{className:'metric-grid'},[['总出场',c.apps],['总进球',c.goals],['总助攻',c.assists],['国家队',c.nationalApps],['奖杯',c.titles],['最高评分',c.bestRating||'—']].map(([l,v])=>metric(l,v))),el('div',{className:'detail-list'},[detail('成长模板',save.player.talent.name),detail('稀有度',save.player.talent.rarity),detail('当前身价',formatMoney(save.finance.marketValue)),detail('现金资产',formatMoney(save.finance.cash)),detail('效力球队',`${new Set(save.career.clubHistory).size}家`),detail('存档版本',save.gameVersion),notes.length?detail('最近迁移说明',notes.at(-1)):null])])}
function relations(save){const section=el('section',{className:'section-block'},[el('div',{className:'section-heading'},[el('div',{},[el('span',{className:'eyebrow',text:'关系网络'}),el('h2',{text:'职业关系'})]),el('small',{className:'muted',text:'信任、尊重、竞争、熟悉与矛盾共同作用'})])]);const grid=el('div',{className:'relation-grid'});RELATION_KEYS.forEach(key=>{const r=save.relations[key],score=relationshipScore(r);grid.append(el('article',{className:'glass-card relation-card'},[el('div',{className:'relation-score',text:String(score)}),el('div',{},[el('h3',{text:RELATION_LABELS[key]}),el('p',{text:`信任 ${r.trust} · 尊重 ${r.respect} · 熟悉 ${r.familiarity}`}),el('small',{text:`竞争 ${r.rivalry} · 矛盾 ${r.conflict}`})])]))});section.append(grid);return section}
function achievements(save,repo){let limit=36,filter='全部';const section=el('section',{className:'section-block'});const head=el('div',{className:'section-heading'},[el('div',{},[el('span',{className:'eyebrow',text:'成就系统'}),el('h2',{text:`已解锁 ${save.achievements.unlocked.length}/${repo.achievements.length}`})])]);const controls=el('div',{className:'achievement-filters'});['全部','已解锁','未解锁','隐藏'].forEach(x=>controls.append(button(x,{className:'filter-chip',onClick:e=>{filter=x;limit=36;renderList()}})));const list=el('div',{className:'achievement-grid'});const more=button('加载更多',{className:'button button--secondary',onClick:()=>{limit+=36;renderList()}});function renderList(){list.replaceChildren();const items=repo.achievements.filter(a=>filter==='全部'||filter==='已解锁'&&save.achievements.unlocked.includes(a.id)||filter==='未解锁'&&!save.achievements.unlocked.includes(a.id)&&!a.hidden||filter==='隐藏'&&a.hidden).slice(0,limit);items.forEach(a=>{const unlocked=save.achievements.unlocked.includes(a.id),progress=achievementProgress(save,a);list.append(el('article',{className:`achievement-card ${unlocked?'is-unlocked':''} ${a.hidden&&!unlocked?'is-hidden':''}`},[el('span',{className:'achievement-icon',text:unlocked?'🏆':a.hidden?'？':'◇'}),el('div',{},[el('h3',{text:a.hidden&&!unlocked?'隐藏成就':a.name}),el('p',{text:a.hidden&&!unlocked?'继续职业生涯以发现条件':a.description}),el('div',{className:'mini-progress'},[el('i',{attrs:{style:`width:${progress.ratio*100}%`}})]),el('small',{text:unlocked?`已解锁 · 成就分 ${a.reward}`:`进度 ${progress.current}/${progress.target}`})])]))});more.hidden=items.length>=repo.achievements.filter(a=>filter==='全部'||filter==='已解锁'&&save.achievements.unlocked.includes(a.id)||filter==='未解锁'&&!save.achievements.unlocked.includes(a.id)&&!a.hidden||filter==='隐藏'&&a.hidden).length}
 renderList();section.append(head,controls,list,more);return section}
function settings(save,store,onReturnToSlots){const section=el('section',{className:'section-block'},[el('div',{className:'section-heading'},[el('div',{},[el('span',{className:'eyebrow',text:'存档与外观'}),el('h2',{text:'设置'})])])]);const card=el('section',{className:'glass-card settings-card'});const theme=el('select',{className:'select-input'});[['system','跟随系统'],['light','浅色'],['dark','深色']].forEach(([v,n])=>theme.append(el('option',{text:n,attrs:{value:v,selected:getTheme()===v}})));theme.onchange=()=>{applyTheme(theme.value);save.settings.theme=theme.value;store.update(()=>{},'theme');showToast('外观设置已保存')};const input=el('input',{attrs:{type:'file',accept:'application/json'},className:'visually-hidden'});input.onchange=async()=>{try{const result=await saveManager.import(input.files[0]);showToast('存档导入成功',{type:'success'});location.reload()}catch{showToast('存档导入失败',{type:'error'})}};card.append(el('label',{className:'setting-row'},[el('div',{},[el('strong',{text:'外观模式'}),el('small',{text:'浅色、深色或跟随系统'})]),theme]),el('div',{className:'settings-actions'},[button('手动保存',{className:'button',onClick:()=>{store.saveNow();showToast('存档已保存',{type:'success'})}}),button('导出存档',{className:'button',onClick:()=>saveManager.export(save)}),button('导入存档',{className:'button',onClick:()=>input.click()}),button('存档槽位',{className:'button button--secondary',onClick:onReturnToSlots})]),input);section.append(card);return section}
function metric(label,value){return el('div',{className:'metric'},[el('small',{text:label}),el('strong',{text:String(value)})])}
function detail(label,value){return el('div',{className:'detail-row'},[el('span',{text:label}),el('strong',{text:String(value)})])}
