import { animationDirector } from '../core/animationDirector.js';
import { audioManager } from '../core/audioManager.js';

const clamp = (value, min = 0, max = 100) => Math.max(min, Math.min(max, Number(value) || 0));
const directions = ['左', '中', '右'];
const safe = (value, fallback = 50) => Number.isFinite(Number(value)) ? Number(value) : fallback;

export function createTrainingGame(game, { onComplete, onSkip, motion = 'full' } = {}) {
  const node = document.createElement('section');
  node.className = `training-game training-game--${game.mechanic}`;
  node.tabIndex = 0;
  node.innerHTML = `<header class="training-game__intro"><div><span class="eyebrow">${game.name}</span><h3>${game.target}专项</h3><p>${game.instruction}</p></div><div class="training-game__facts"><span>风险 ${game.risk}%</span><span>疲劳 ${game.fatigue > 0 ? '+' : ''}${game.fatigue}</span></div></header><div class="training-game__countdown" data-countdown>3</div><div class="training-game__area" data-area hidden></div><p class="training-game__feedback" data-feedback aria-live="polite">准备开始</p><footer class="training-game__footer"><span data-time>准备</span><button class="app-button ghost" data-skip>跳过本次训练</button></footer>`;
  const area = node.querySelector('[data-area]');
  const feedback = node.querySelector('[data-feedback]');
  const countdown = node.querySelector('[data-countdown]');
  const timeLabel = node.querySelector('[data-time]');
  const cleanups = [];
  let ended = false;
  let timer = 0;
  let interval = 0;
  let frame = 0;
  const listen = (target, type, handler, options) => { target?.addEventListener(type, handler, options); if (target) cleanups.push(() => target.removeEventListener(type, handler, options)); };
  const setFeedback = value => { if (feedback) feedback.textContent = value; };
  const clear = () => { if (timer) clearTimeout(timer); if (interval) clearInterval(interval); if (frame) cancelAnimationFrame(frame); cleanups.splice(0).forEach(fn => fn()); };
  const finish = (score, detail, extra = {}) => {
    if (ended) return;
    ended = true; clear(); const finalScore = Math.round(clamp(score));
    const grade = finalScore >= 90 ? 'S' : finalScore >= 80 ? 'A' : finalScore >= 65 ? 'B' : finalScore >= 50 ? 'C' : 'D';
    const record = { gameId: game.id, name: game.name, score: finalScore, grade, detail: detail || '训练动作已记录', ...extra };
    node.dataset.result = grade; node.classList.add(finalScore >= 65 ? 'is-success' : 'is-failure');
    setFeedback(`${grade}级 · ${finalScore}分 · ${record.detail}`); timeLabel.textContent = '已完成';
    audioManager.play(finalScore >= 90 ? 'record' : finalScore >= 65 ? 'correct' : 'wrong');
    animationDirector.pulse(node, finalScore >= 65 ? 'success-pop' : 'shake');
    window.setTimeout(() => onComplete?.(record), 280);
  };
  const skip = () => { if (ended) return; ended = true; clear(); onSkip?.({ gameId: game.id, name: game.name, score: 45, grade: 'C', detail: '已跳过，按保守表现记录', skipped: true }); };
  listen(node.querySelector('[data-skip]'), 'click', skip);
  node.destroy = () => { ended = true; clear(); };

  const timed = (seconds, onTimeout = () => finish(35, '时间耗尽')) => {
    const started = Date.now();
    const tick = () => { const left = Math.max(0, seconds - (Date.now() - started) / 1000); if (timeLabel) timeLabel.textContent = `剩余 ${left.toFixed(1)} 秒`; if (!ended) frame = requestAnimationFrame(tick); };
    frame = requestAnimationFrame(tick); timer = window.setTimeout(onTimeout, seconds * 1000);
  };
  const control = (label, attrs = '') => `<button class="training-control" type="button" ${attrs}>${label}</button>`;

  function reaction() {
    area.innerHTML = `<div class="reaction-lane"><span data-light>等待信号</span></div><button class="app-button primary" data-react disabled>起跑</button>`;
    const button = area.querySelector('[data-react]'); const wait = 520 + (game.id.length * 41) % 900; timer = setTimeout(() => { button.disabled = false; area.classList.add('signal'); area.querySelector('[data-light]').textContent = '现在起跑'; audioManager.play('whistle'); const signal = performance.now(); listen(button, 'click', () => finish(100 - Math.min(65, (performance.now() - signal) / 5), '反应时间已记录')); }, wait); timed(6, () => finish(30, '错过起跑信号'));
  }
  function rhythm() {
    let index = 0; const expected = ['左', '右', '左', '右']; area.innerHTML = `<div class="rhythm-step" data-step>跟随节奏：${expected[0]}</div><div class="training-actions">${directions.map(direction => control(direction, `data-rhythm="${direction}"`)).join('')}</div>`;
    area.querySelectorAll('[data-rhythm]').forEach(button => listen(button, 'click', () => { if (button.dataset.rhythm !== expected[index]) return finish(index * 18 + 20, '折返方向错误'); index += 1; audioManager.play('correct'); if (index === expected.length) finish(94, '四次折返全部命中', { combo: index }); else area.querySelector('[data-step]').textContent = `跟随节奏：${expected[index]}`; })); timed(8);
  }
  function aim() {
    area.innerHTML = `<div class="aim-arena"><button class="aim-target" data-aim aria-label="射门目标"></button></div><p>目标会持续移动，点击靶心。</p>`; const target = area.querySelector('[data-aim]'); let x = 12, y = 32, dx = .82, dy = .55;
    const move = () => { x += dx; y += dy; if (x > 86 || x < 8) dx *= -1; if (y > 76 || y < 14) dy *= -1; target.style.left = `${x}%`; target.style.top = `${y}%`; if (!ended) frame = requestAnimationFrame(move); }; frame = requestAnimationFrame(move); listen(target, 'click', () => finish(88, '准星命中目标区域')); timed(7);
  }
  function threeChoice() { const expected = directions(game.id.length % 3); area.innerHTML = `<div class="training-actions">${directions.map(direction => control(`${direction}侧`, `data-side="${direction}"`)).join('')}</div><label class="training-range">力度 <input type="range" min="0" max="100" value="62" data-power></label><div class="training-actions">${control('立即射门', 'data-submit')}</div>`; let side = '中'; area.querySelectorAll('[data-side]').forEach(button => listen(button, 'click', () => { side = button.dataset.side; area.querySelectorAll('[data-side]').forEach(item => item.classList.toggle('is-selected', item === button)); })); listen(area.querySelector('[data-submit]'), 'click', () => { const power = safe(area.querySelector('[data-power]').value); finish((side === expected ? 62 : 32) + Math.max(0, 38 - Math.abs(power - 64) * .7), side === expected ? '方向与力度匹配' : '门将提前判断方向'); }); timed(9); }
  function curve() { area.innerHTML = `<div class="training-sliders">${[['弧线','curve',60],['角度','angle',52],['力度','power',64]].map(([label,key,value]) => `<label>${label}<input type="range" min="0" max="100" value="${value}" data-${key}></label>`).join('')}</div><div class="curve-preview" data-curve-preview>球路预览</div>${control('踢出任意球', 'data-submit')}`; listen(area.querySelector('[data-submit]'), 'click', () => { const values = ['curve','angle','power'].map(key => safe(area.querySelector(`[data-${key}]`).value)); const score = 100 - values.reduce((sum, value, index) => sum + Math.abs(value - [62, 50, 66][index]) * .75, 0); finish(score, '弧线绕过人墙并接近目标'); }); timed(9); }
  function dodge() { let lane = 1, hits = 0, obstacle = 0; area.innerHTML = `<div class="dodge-lanes"><span data-obstacle>●</span></div><div class="training-actions">${['左路','中路','右路'].map((label, index) => control(label, `data-lane="${index}"`)).join('')}</div>`; interval = setInterval(() => { obstacle = (obstacle + 1) % 3; area.querySelector('[data-obstacle]').style.left = `${18 + obstacle * 32}%`; }, 520); area.querySelectorAll('[data-lane]').forEach(button => listen(button, 'click', () => { lane = Number(button.dataset.lane); if (lane === obstacle) { hits += 1; setFeedback(`避开障碍 ${hits}/4`); if (hits >= 4) finish(92, '连续变向完成'); } else finish(38, '撞上训练桩'); })); timed(8); }
  function movingTarget() { let count = 0; area.innerHTML = `<div class="target-board"><button class="target-dot" data-target aria-label="传球靶点"></button></div><p data-target-copy>点击移动靶点 0/3</p>`; const target = area.querySelector('[data-target]'); const move = () => { target.style.left = `${12 + (count * 31) % 70}%`; target.style.top = `${20 + (count * 23) % 58}%`; }; move(); listen(target, 'click', () => { count += 1; audioManager.play('correct'); if (count >= 3) finish(93, '三处移动靶点全部命中'); else { area.querySelector('[data-target-copy]').textContent = `点击移动靶点 ${count}/3`; move(); } }); timed(8); }
  function timingWindow() { area.innerHTML = `<div class="timing-track"><span data-runner></span><span class="timing-line" data-line></span><span class="timing-zone"></span></div>${control('现在直塞', 'data-submit')}`; let x = 4, step = 1.15; const runner = area.querySelector('[data-runner]'), line = area.querySelector('[data-line]'); const move = () => { x += step; if (x > 94 || x < 4) step *= -1; runner.style.left = `${x}%`; line.style.left = `${Math.min(88, x + 8)}%`; if (!ended) frame = requestAnimationFrame(move); }; frame = requestAnimationFrame(move); listen(area.querySelector('[data-submit]'), 'click', () => finish(100 - Math.abs(x - 58) * 1.6, x > 45 && x < 72 ? '跑位与越位线同步' : '传球稍早或稍晚')); timed(7); }
  function aerial() { area.innerHTML = `<div class="aerial-board"><span class="falling-ball" data-ball>●</span><span class="header-zone"></span></div>${control('起跳', 'data-jump')}`; let y = 8, step = 1.1; const ball = area.querySelector('[data-ball]'); const move = () => { y += step; if (y > 82 || y < 8) step *= -1; ball.style.top = `${y}%`; if (!ended) frame = requestAnimationFrame(move); }; frame = requestAnimationFrame(move); listen(area.querySelector('[data-jump]'), 'click', () => finish(100 - Math.abs(y - 56) * 1.8, y > 40 && y < 70 ? '起跳点贴合落点' : '起跳时机偏离')); timed(7); }
  function contactWindow() { area.innerHTML = `<div class="contact-window"><span data-window>观察触球窗口</span></div>${control('出脚抢断', 'data-tackle')}`; let good = false; interval = setInterval(() => { good = !good; area.classList.toggle('is-good', good); area.querySelector('[data-window]').textContent = good ? '现在可以出脚' : '等待触球'; }, 440); listen(area.querySelector('[data-tackle]'), 'click', () => finish(good ? 92 : 30, good ? '触球窗口命中' : '出脚过早，犯规风险上升')); timed(7); }
  function balance() { area.innerHTML = `<div class="balance-track"><span class="balance-zone"></span><input type="range" min="0" max="100" value="50" data-balance aria-label="对抗平衡"></div>${control('锁定重心', 'data-lock')}`; listen(area.querySelector('[data-lock]'), 'click', () => { const value = safe(area.querySelector('[data-balance]').value); finish(100 - Math.abs(value - 50) * 1.65, value > 35 && value < 65 ? '重心保持稳定' : '对抗中失去平衡'); }); timed(8); }
  function lights() { let hits = 0, active = 0; area.innerHTML = `<div class="light-grid">${Array.from({ length: 9 }, (_, index) => `<button data-light-index="${index}" aria-label="反应灯"></button>`).join('')}</div><p data-light-copy>等待亮灯</p>`; const lights = [...area.querySelectorAll('[data-light-index]')]; const next = () => { active = (active + game.id.length + hits) % lights.length; lights.forEach((item, index) => item.classList.toggle('is-lit', index === active)); }; next(); listen(area, 'click', event => { const button = event.target.closest('[data-light-index]'); if (!button) return; if (Number(button.dataset.lightIndex) !== active) return finish(32, '点击了未亮起的灯'); hits += 1; if (hits >= 5) finish(96, '五次反应灯全部命中'); else { area.querySelector('[data-light-copy]').textContent = `连续命中 ${hits}/5`; audioManager.play('combo'); next(); } }); timed(8); }
  function memory() { const selected = [1, 5, 7]; area.innerHTML = `<div class="memory-grid">${Array.from({ length: 9 }, (_, index) => `<button data-memory="${index}" aria-label="队友位置"></button>`).join('')}</div><p data-memory-copy>记住亮起的队友位置</p>`; const cells = [...area.querySelectorAll('[data-memory]')]; selected.forEach(index => cells[index].classList.add('remember')); timer = setTimeout(() => { cells.forEach(cell => cell.classList.remove('remember')); area.querySelector('[data-memory-copy]').textContent = '按顺序点出队友位置'; let index = 0; listen(area, 'click', event => { const cell = event.target.closest('[data-memory]'); if (!cell) return; if (Number(cell.dataset.memory) !== selected[index]) return finish(28, '传球顺序记忆错误'); index += 1; if (index === selected.length) finish(94, '队友位置记忆准确'); }); }, 1100); timed(8); }
  function tactical() { const correct = game.id.length % 3; area.innerHTML = `<p class="tactical-situation">比分 ${correct ? '1比1' : '领先一球'} · 剩余 ${correct ? '12' : '6'} 分钟 · 对手压上</p><div class="training-actions">${['保持控球','主动前插','稳守反击'].map((label, index) => control(label, `data-tactic="${index}"`)).join('')}</div>`; area.querySelectorAll('[data-tactic]').forEach(button => listen(button, 'click', () => finish(Number(button.dataset.tactic) === correct ? 93 : 48, Number(button.dataset.tactic) === correct ? '跑位符合比赛局势' : '选择与局势不完全匹配'))); timed(7); }
  function swipe() { area.innerHTML = `<div class="keeper-goal" data-swipe><span class="keeper-glove">手套</span><span class="ball-flight">●</span></div><p>向来球方向滑动</p>`; let start = null; const target = game.id.length % 2 ? 'right' : 'left'; listen(area, 'pointerdown', event => { start = [event.clientX, event.clientY]; }); listen(area, 'pointerup', event => { if (!start) return; const dx = event.clientX - start[0], dy = event.clientY - start[1]; start = null; const actual = Math.abs(dx) > Math.abs(dy) ? dx > 0 ? 'right' : 'left' : dy < 0 ? 'up' : 'down'; finish(actual === target ? 94 : 38, actual === target ? '侧扑方向正确' : '来球判断错误'); }); timed(7); }
  function holdRelease() { area.innerHTML = `<div class="charge-meter"><span class="charge-zone"></span><span data-charge></span></div>${control('按住出击，松开', 'data-charge-button')}`; let down = 0; const button = area.querySelector('[data-charge-button]'); listen(button, 'pointerdown', () => { down = performance.now(); button.classList.add('is-held'); }); listen(button, 'pointerup', () => { const held = performance.now() - down; button.classList.remove('is-held'); finish(100 - Math.abs(held - 620) * .1, held > 430 && held < 850 ? '出击距离合适' : '出击过早或过晚'); }); timed(7); }
  function dragTarget() { area.innerHTML = `<div class="drag-field"><span class="landing-point" data-landing></span><span class="keeper-token" data-keeper draggable="false">门将</span></div>${control('起跳摘球', 'data-jump')}`; const keeper = area.querySelector('[data-keeper]'), field = area.querySelector('.drag-field'); let x = 50, y = 70; const move = event => { const rect = field.getBoundingClientRect(); x = clamp((event.clientX - rect.left) / rect.width * 100); y = clamp((event.clientY - rect.top) / rect.height * 100); keeper.style.left = `${x}%`; keeper.style.top = `${y}%`; }; listen(keeper, 'pointerdown', event => { keeper.setPointerCapture(event.pointerId); listen(keeper, 'pointermove', move); }); listen(area.querySelector('[data-jump]'), 'click', () => { const targetX = 34 + game.id.length % 30, targetY = 34; finish(100 - Math.hypot(x - targetX, y - targetY) * 1.25, Math.abs(x - targetX) < 15 ? '移动到落点并成功摘球' : '站位偏离落点'); }); timed(8); }
  function powerTarget() { area.innerHTML = `<div class="training-actions">${directions.map(direction => control(`${direction}侧`, `data-distribution="${direction}"`)).join('')}</div><label class="training-range">力度 <input type="range" min="0" max="100" value="58" data-power></label>${control('开球', 'data-submit')}`; let side = '中'; area.querySelectorAll('[data-distribution]').forEach(button => listen(button, 'click', () => { side = button.dataset.distribution; })); listen(area.querySelector('[data-submit]'), 'click', () => finish((side === directions(game.id.length % 3) ? 62 : 30) + Math.max(0, 38 - Math.abs(safe(area.querySelector('[data-power]').value) - 58) * .8), '目标与力度匹配')); timed(8); }
  function safeRhythm() { let hits = 0, last = 0; area.innerHTML = `<div class="rehab-pulse" data-pulse></div>${control('轻触节奏', 'data-rehab')}<p>保持均匀，不要连续猛按。</p>`; listen(area.querySelector('[data-rehab]'), 'click', () => { const now = Date.now(); if (now - last < 240) return finish(28, '节奏过快，康复负荷过高'); last = now; hits += 1; setFeedback(`舒缓动作 ${hits}/4`); if (hits === 4) finish(96, '康复节奏稳定'); }); timed(8); }
  function keepZone() { area.innerHTML = `<div class="core-field"><span class="core-zone"></span><span class="core-puck" data-puck></span></div><p>拖动蓝点保持在绿色区域。</p>`; const field = area.querySelector('.core-field'), puck = area.querySelector('[data-puck]'); let x = 50, y = 50, samples = 0, good = 0; const move = event => { const rect = field.getBoundingClientRect(); x = clamp((event.clientX - rect.left) / rect.width * 100); y = clamp((event.clientY - rect.top) / rect.height * 100); puck.style.left = `${x}%`; puck.style.top = `${y}%`; }; listen(puck, 'pointerdown', event => { puck.setPointerCapture(event.pointerId); listen(puck, 'pointermove', move); }); interval = setInterval(() => { samples += 1; if (Math.hypot(x - 50, y - 50) < 20) good += 1; if (samples >= 6) finish(good / samples * 100, `稳定 ${good}/${samples} 次`); }, 650); listen(node, 'keydown', event => { const step = 7; if (event.key === 'ArrowLeft') x -= step; if (event.key === 'ArrowRight') x += step; if (event.key === 'ArrowUp') y -= step; if (event.key === 'ArrowDown') y += step; x = clamp(x); y = clamp(y); puck.style.left = `${x}%`; puck.style.top = `${y}%`; }); timed(8); }

  function start() {
    let count = 3;
    const tick = () => { count -= 1; if (count <= 0) { countdown.hidden = true; area.hidden = false; startMechanic(); audioManager.play('whistle'); return; } countdown.textContent = String(count); audioManager.play('countdown'); timer = setTimeout(tick, 620); };
    timer = setTimeout(tick, 620);
  }
  function startMechanic() {
    ({ reaction, rhythm, aim, 'three-choice': threeChoice, curve, dodge, 'moving-target': movingTarget, 'timing-window': timingWindow, aerial, 'contact-window': contactWindow, balance, lights, memory, tactical, swipe, 'hold-release': holdRelease, 'drag-target': dragTarget, 'power-target': powerTarget, 'safe-rhythm': safeRhythm, 'keep-zone': keepZone }[game.mechanic] || (() => finish(50, '按保守表现结算')) )();
  }
  start();
  return node;
}

