import { Store } from './core/store.js';
import { EventEngine } from './core/eventEngine.js';
import { CareerDirector, recordMatchResult, replaceFictionalFixtures } from './core/simulationController.js';
import { FeedbackDirector } from './core/feedbackDirector.js';
import { AnimationDirector } from './core/animationDirector.js';
import { applyGrowthToState } from './core/playerDevelopmentEngine.js';
import { createInjury, chooseTreatment, activeInjury } from './core/injuryEngine.js';
import { matchAvailability } from './core/disciplineEngine.js';
import { icon } from './components/icons.js';
import { OverlayManager, playerDetail, metric, statGrid, emptyState } from './components/ui.js';
import { radarChart } from './components/radar.js';
import { keyedRandom } from './services/rng.js';
import { resolveMatchInteraction } from './core/matchInteractions.js';
import { MATCH_INTERACTIONS } from './core/matchInteractions.js';
import { createMatchState } from './core/matchState.js';
import { HighlightDirector } from './core/highlightDirector.js';
import { MatchEventEngine } from './core/matchEventEngine.js';
import { matchStrategiesForPosition } from './core/matchStrategy.js';
import { getPositionProfile } from './core/positionResolver.js';
import { createMiniGameContext, createMiniGameSession } from './core/miniGameLibrary.js';
import { createInteractiveMatch } from './components/interactiveMatch.js';
import { createPlayerWizard } from './pages/createPlayer.js';
import { careerPage } from './pages/career.js';
import { trainingPage } from './pages/training.js';
import { matchPage } from './pages/match.js';
import { transferPage } from './pages/transfer.js';
import { clubsPage } from './pages/clubs.js';
import { morePage } from './pages/more.js';
import { CLUBS } from './data/clubs.js';
import { dataRepository } from './services/dataRepository.js';
import { completeOffSeason, createCareerShareCard, ensureHonors, retireCareer, resolveOffSeasonActivity, settleSeason, seasonReviewNext } from './systems/honors/honorsSystem.js';
import { applyTheme } from './app/theme.js';
import { trainingGameById } from './data/trainingGames.js';
import { createTrainingGame } from './components/trainingGame.js';
import { audioManager } from './core/audioManager.js';
import { addNews, ensureHomeNews } from './core/newsEngine.js';
import { pickOutcomeAnimation } from './core/outcomeAnimations.js';
import { resolveTrainingOpportunity } from './core/trainingOpportunities.js';
import { trophyMarkup } from './components/trophyIcon.js';
import { evaluateClubFit } from './services/playerIdentity.js';

const ROUTES={career:['home','生涯'],match:['match','比赛'],training:['training','训练'],transfer:['transfer','转会'],clubs:['club','俱乐部'],more:['settings','更多']};
const ATTR_CN={speed:'速度',shooting:'射门',passing:'传球',dribbling:'盘带',defending:'防守',physical:'身体'};
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const addDateDays=(value,days)=>{const date=new Date(`${value}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10);};
const DEFAULT_MATCH_TACTIC=Object.freeze({id:'balanced',mods:{rating:.2,assist:.06,goal:.04,fatigue:5}});

class App {
  constructor(){
    this.root=document.querySelector('#app');
    this.overlay=new OverlayManager(document.querySelector('#overlay-root'));
    this.store=new Store();
    this.events=new EventEngine();
    this.simulation=new CareerDirector(this.store,this.events);
    this.feedback=new FeedbackDirector(document.body);
    this.feedback.setSoundEnabled(this.store.get().settings.sound);
    audioManager.configure(this.store.get().settings.sound ? {} : { muted: true });
    this.animation=new AnimationDirector();
    this.resolvingEventKey=null;
    this.store.subscribe(()=>this.render());
  }
  mount(){
    applyTheme(this.store.get().settings.theme);
    if(!this.store.get().player){this.root.replaceChildren(createPlayerWizard(this));return;}
    this.root.innerHTML='<div class="app-shell"><div data-topbar></div><main class="app-main" data-page></main><div data-tabbar></div></div>';
    this.render();
    if(!this.store.get().news.items.length)this.store.set(state=>{ensureHomeNews(state);return state;});
    if(!this.store.get().events.pending.length && !this.store.get().events.history.length && this.store.get().settings.mode!=='fast'){this.store.set(s=>{this.events.schedule(s,{priority:'normal'});return s;});}
  }
  render(){
    applyTheme(this.store.get().settings.theme);
    this.feedback.setSoundEnabled(this.store.get().settings.sound);
    const shell=this.root.querySelector('.app-shell');
    if(!this.store.get().player){if(!this.root.querySelector('.wizard-shell'))this.root.replaceChildren(createPlayerWizard(this));return;}
    if(!shell){this.mount();return;}
    const state=this.store.get();
    shell.querySelector('[data-topbar]').innerHTML=this.topbar(state);
    const page=shell.querySelector('[data-page]'); page.replaceChildren(this.page(state));
    shell.querySelector('[data-tabbar]').innerHTML=this.tabbar(state);
    this.bindShell();
  }
  page(state){ return ({career:careerPage,match:matchPage,training:trainingPage,transfer:transferPage,clubs:clubsPage,more:morePage}[state.route]||careerPage)(this,state); }
  topbar(state){const p=state.player;return `<header class="app-topbar"><div class="identity"><div class="avatar">${p.number}</div><div class="identity-copy"><div class="identity-name">${p.name}</div><div class="identity-meta">${p.club} · ${p.age}岁 · €${Math.round(state.career.marketValue/1000)}K</div></div></div><div class="top-actions"><button class="icon-button top-save" data-top-save aria-label="保存">${icon('save')}</button></div></header>`;}
  tabbar(state){return `<nav class="glass-tabbar" aria-label="主导航">${Object.entries(ROUTES).map(([key,[ico,label]])=>`<button class="tab-item ${state.route===key?'active':''}" data-route="${key}">${icon(ico)}<span class="tab-label">${label}</span></button>`).join('')}</nav>`;}
  bindShell(){
    this.root.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>this.navigate(el.dataset.route));
    this.root.querySelector('[data-top-save]')?.addEventListener('click',()=>{this.store.save();this.feedback.emit('save','本地存档已更新');});
  }
  navigate(route){this.overlay.close();this.store.set(s=>{s.route=route;return s;});window.scrollTo({top:0,behavior:'smooth'});}

  openAcknowledgement(title,copy,{button='继续',onContinue=()=>this.navigate('career')}={}){
    this.overlay.sheet(title,`<section class="result-panel"><h3 class="card-title">${escapeHtml(title)}</h3><p class="card-copy">${escapeHtml(copy)}</p></section><button class="app-button primary" style="width:100%;margin-top:12px" data-result-ack>${escapeHtml(button)}</button>`,{dismissible:false,onMount:el=>el.querySelector('[data-result-ack]').onclick=()=>{this.overlay.close();onContinue();}});
  }

  openPlayerDetail(){const s=this.store.get();this.overlay.sheet('球员详情',playerDetail(s.player,s));}
  openCareerData(){const s=this.store.get(),next=s.schedule.find(m=>m.status==='upcoming');this.overlay.sheet('职业数据详情',`<div class="grid-2">${summaryCard('calendar','当前赛季',statGrid([['出场',s.season.appearances],['进球',s.season.goals],['助攻',s.season.assists],['评分',s.season.rating||'—']]))}${summaryCard('record','生涯状态',statGrid([['OVR',s.player.ovr],['潜力',Math.round(s.player.potential)],['身价',`€${Math.round(s.career.marketValue/1000)}K`],['合同',`${s.career.contractMonths}月`]]))}</div><div style="height:14px"></div><section class="surface-card"><div class="card-kicker">下一场赛程</div>${next?`<h3 class="card-title">${next.competition} · ${next.opponent}</h3><p class="card-copy">${next.date} · ${next.venue}</p>`:emptyState('暂无赛程','推进到下一赛季后会生成新赛程。')}</section>`);}
  openGoals(){const s=this.store.get();const goals=s.season.objectives.length?s.season.objectives:[{id:'minutes',name:'获得稳定出场',progress:Math.min(100,s.season.appearances*12),reward:'教练信任 +5'},{id:'growth',name:'总评提升2点',progress:Math.min(100,(s.player.ovr-58)*50),reward:'解锁专项路线'},{id:'health',name:'保持健康8周',progress:Math.min(100,s.season.week*12),reward:'恢复效率 +5%'}];this.overlay.sheet('赛季目标',`<p class="card-copy">最多选择2项阶段重点，目标会影响训练建议与事件权重。</p><div style="height:12px"></div><div class="stack">${goals.map(g=>`<button class="surface-card interactive" data-goal="${g.id}"><div class="card-row"><h3 class="card-title">${g.name}</h3><span class="badge ${g.progress>=100?'green':'blue'}">${g.progress}%</span></div>${metric('完成度',g.progress,{tone:g.progress>=100?'green':''})}<div class="card-footer"><span class="card-copy">奖励：${g.reward}</span>${icon('check','sm')}</div></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-goal]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{if(!st.season.objectives.some(x=>x.id===btn.dataset.goal)&&st.season.objectives.length<2)st.season.objectives.push(goals.find(x=>x.id===btn.dataset.goal));return st;});this.feedback.emit('goalProgress','阶段重点已更新');this.overlay.close();})});}
  openFacilities(){this.overlay.sheet('数据与设施中心',`<div class="action-grid">${facilityTile('analytics','数据分析','近5场、能力趋势与训练收益','analytics')}${facilityTile('medical','医疗中心','伤病、恢复和身体风险','medical')}${facilityTile('locker','更衣室','关系、气氛与首发竞争','locker')}${facilityTile('trophy','荣誉室','奖杯、纪录与里程碑','honors')}</div>`,{onMount:el=>el.onclick=e=>{const k=e.target.closest('[data-facility]')?.dataset.facility;if(k==='analytics')this.openAnalytics();if(k==='medical')this.openMedical();if(k==='locker')this.openLocker();if(k==='honors')this.openHonors();}});}
  openGrowth(){const s=this.store.get(),log=s.career.growthLog.slice(-4);this.overlay.sheet('成长中心',`${radarChart(s.player.stats,s.player.previousStats||s.player.stats,s.player.potential,s.player.position)}<div class="grid-2">${Object.entries(s.player.stats).map(([k,v])=>`<div class="surface-card"><div class="card-row"><strong>${ATTR_CN[k]}</strong><span class="badge blue">${Math.floor(v)}</span></div>${metric('下一个属性点',(v-Math.floor(v))*100)}</div>`).join('')}</div><div style="height:14px"></div><section class="surface-card"><div class="card-kicker">最近4次成长</div>${log.length?`<div class="timeline">${log.reverse().map(x=>`<div class="timeline-item"><div class="timeline-time">${x.date}</div><div class="timeline-title">${x.source}</div><div class="timeline-copy">${Object.entries(x.changes).filter(([,v])=>v>0).map(([k,v])=>`${ATTR_CN[k]} +${v.toFixed(2)}`).join(' · ')}</div></div>`).join('')}</div>`:emptyState('还没有成长记录','完成训练、比赛或成长事件后会记录变化。','growth')}</section>`);}
  openMedical(){
    const s=this.store.get(),inj=activeInjury(s.injuries);
    const content=inj?`<section class="surface-card notice-card critical"><div class="card-row"><div><div class="card-kicker">${icon('injury','sm')} ${inj.bodyPart}</div><h3 class="card-title">${inj.type}</h3><p class="card-copy">状态：${inj.status==='returning'?'恢复期':'治疗中'} · 剩余约 ${Math.ceil(inj.remainingDays)} 天</p></div><span class="badge red">复发 ${inj.relapseRisk}%</span></div>${metric('恢复进度',inj.progress,{tone:'green'})}</section><div style="height:12px"></div><div class="grid-3">${treatmentCard('light','轻量恢复','训练保守，恢复较慢，风险较低')}${treatmentCard('steady','稳妥治疗','平衡恢复速度与复发风险')}${treatmentCard('aggressive','激进复出','恢复更快，但复发风险上升')}</div>`:`${emptyState('当前没有伤病','医疗中心会持续追踪疲劳、旧伤风险与恢复记录。','medical')}<button class="app-button ghost" data-demo-injury>生成测试伤病</button>`;
    this.overlay.sheet('医疗中心',content,{onMount:el=>{
      el.querySelectorAll('[data-treatment]').forEach(btn=>btn.onclick=()=>{
        this.store.set(st=>{const i=st.injuries.findIndex(x=>x.id===inj.id);st.injuries[i]=chooseTreatment(st.injuries[i],btn.dataset.treatment);st.career.injuryLog.push({date:st.simulation.date,type:'治疗路线',text:btn.dataset.treatment});return st;});
        this.feedback.emit('recovered','治疗路线已更新');this.openAcknowledgement('治疗路线已确认',`${inj.type}将按所选方案恢复。`,{onContinue:()=>this.navigate('career')});
      });
      el.querySelector('[data-demo-injury]')?.addEventListener('click',()=>{this.store.set(st=>{st.injuries.push(createInjury({date:st.simulation.date}));return st;});this.feedback.emit('worsened','已创建一项轻伤用于体验恢复系统');this.openMedical();});
    }});
  }
  openEventCenter(){const s=this.store.get();const list=s.events.pending;this.overlay.sheet('事件与待办',list.length?`<div class="stack">${list.map(e=>`<button class="surface-card interactive" data-event="${e.id}"><div class="card-row"><div class="icon-tile">${icon(eventIcon(e.category))}</div><span class="badge ${e.priority==='important'?'orange':'blue'}">${interactionLabel(e.interaction)}</span></div><h3 class="card-title">${e.title}</h3><p class="card-copy">${e.location||'职业现场'} · ${formatParticipants(e)}</p></button>`).join('')}</div>`:emptyState('待办已清空','普通通知会进入消息中心，只有关键事件会中断推进。','todo'),{onMount:el=>el.querySelectorAll('[data-event]').forEach(btn=>btn.onclick=()=>this.openEvent(list.find(x=>x.id===btn.dataset.event)))});}
  openEvent(event){
    if(!event)return;
    this.resolvingEventKey=null;
    const choices=(Array.isArray(event.choices)?event.choices:[]).filter(choice=>choice?.id&&choice?.label).slice(0,4);
    const description=event.conflict||event.description||event.trigger||'职业生涯出现了需要你亲自决定的新情况。';
    const content=`<section class="event-background"><div class="event-art"><img src="${event.art||'./assets/scenes/scene-mixed-zone.svg'}" loading="lazy" alt="${event.sceneName||'事件场景'}"><span class="badge ${event.rarity==='legendary'?'gold':event.rarity==='crisis'?'red':'blue'}">${rarityLabel(event.rarity)}</span></div><div class="card-kicker">${icon(eventIcon(event.category),'sm')} ${event.category||'职业事件'}${event.location?` · ${event.location}`:''}</div><h3 class="card-title">${event.title||'未命名事件'}</h3><p class="card-copy">${description}</p></section><div class="event-divider"></div><section class="event-choice-section"><div class="card-kicker">决策区</div><h3 class="card-title">你准备怎么处理？</h3><p class="card-copy">先选一个方向，实际结果会在处理后揭晓。</p>${choices.length?`<div class="stack">${choices.map(c=>`<button class="surface-card decision-card interactive" data-choice="${c.id}"><div class="card-row"><strong>${c.label}</strong></div><p class="card-copy">${c.hint||'结果会结合当前状态判定。'}</p></button>`).join('')}</div>`:'<div class="empty-event-state">该事件缺少可用选项，已保护当前生涯不被卡住。</div>'}</section>`;
    this.overlay.sheet(event.title||'职业事件',content,{onMount:el=>{
      const buttons=[...el.querySelectorAll('[data-choice]')];
      buttons.forEach(btn=>btn.onclick=()=>{
        if(this.resolvingEventKey)return;
        const choiceId=btn.dataset.choice,key=`${event.id||''}:${choiceId||''}`;
        this.resolvingEventKey=key;
        buttons.forEach(item=>{item.disabled=item!==btn;item.classList.toggle('is-processing',item===btn);item.setAttribute('aria-disabled',String(item!==btn));});
        this.feedback.emit('select','选择已锁定');
        window.setTimeout(()=>{if(this.resolvingEventKey!==key)return;const settled=this.resolveEvent(event,choiceId,key);if(!settled)buttons.forEach(item=>{item.disabled=false;item.classList.remove('is-processing');item.removeAttribute('aria-disabled');});},320);
      });
    }});
  }
  resolveEvent(event,choiceId,lockedKey=null){const key=`${event?.id||''}:${choiceId||''}`;if(!event||!choiceId||(lockedKey&&lockedKey!==key)||(!lockedKey&&this.resolvingEventKey))return false;this.resolvingEventKey=key;let result;try{this.store.set(s=>{if(!s.events.pending.some(item=>item.id===event.id))throw new Error('事件已处理');result=this.events.resolve(s,event.id,choiceId);this.applyEffectsToState(s,result.effects,`事件：${result.title}`);s.ui.lastOutcome=result;return s;});}catch(error){this.resolvingEventKey=null;this.feedback.emit('failure','事件处理失败，请重新打开待办');return false;}this.feedback.emit(result.outcome==='success'?'select':'failure',result.outcome==='success'?'处理成功':'需要复盘');if(result.followUp)this.feedback.emit('todo','后续剧情已进入职业安排');this.overlay.sheet('事件结果',resultPanel(result),{dismissible:false,onClose:()=>{if(this.resolvingEventKey===key)this.resolvingEventKey=null;},onMount:el=>{el.querySelector('[data-result-back]')?.addEventListener('click',()=>{this.resolvingEventKey=null;this.overlay.close();});el.querySelector('[data-result-next]')?.addEventListener('click',()=>{const next=this.store.get().events.pending[0];next?this.openEvent(next):(this.resolvingEventKey=null,this.overlay.close());});el.querySelector('[data-result-continue]')?.addEventListener('click',()=>{this.resolvingEventKey=null;this.overlay.close();this.navigate('career');});}});return true;}
  applyEffectsToState(s,effects,source){if(!s.player)return;const gains={};for(const k of [...Object.keys(ATTR_CN),'potential'])if(effects[k])gains[k]=effects[k];if(Object.keys(gains).length){const out=applyGrowthToState(s,gains,{source,fatigue:s.player.fatigue,injured:!!activeInjury(s.injuries),facility:76,coachQuality:74,mode:s.settings.mode});if(out.breakthroughs.length)setTimeout(()=>this.feedback.emit('attributeUp',out.breakthroughs.map(k=>ATTR_CN[k]).join('、')),0);}
    s.player.fatigue=clamp(s.player.fatigue+Number(effects.fatigue||0),0,100);s.player.fitness=clamp(100-s.player.fatigue*.7,10,100);s.player.morale=clamp(s.player.morale+Number(effects.morale||0),0,100);s.player.coachTrust=clamp(s.player.coachTrust+Number(effects.trust||0),0,100);s.relationships.coach=s.player.coachTrust;s.relationships.teammates=clamp(s.relationships.teammates+Number(effects.relationship||0),0,100);s.relationships.rivalry=clamp(s.relationships.rivalry+Number(effects.rivalry||0),0,100);s.relationships.fans=Math.max(0,s.relationships.fans+Number(effects.fans||0));s.relationships.media=clamp(s.relationships.media+Number(effects.media||0),0,100);s.career.marketValue=Math.max(0,s.career.marketValue+Number(effects.marketValue||0));if(effects.trait&&!s.career.achievements.includes(effects.trait)){s.career.achievements.push(effects.trait);setTimeout(()=>this.feedback.emit('newTrait',effects.trait),0);}if(Number(effects.risk||0)>8&&!activeInjury(s.injuries)&&keyedRandom(s.simulation.date,'event-injury',s.events.history.length).bool(.18))s.injuries.push(createInjury({date:s.simulation.date,rng:keyedRandom(s.simulation.date,'event-injury-detail',s.events.history.length)}));}

  async runSimulation(action){this.overlay.close();this.feedback.emit('loading','正在结算训练、比赛与生涯事件');const result=await this.simulation.advance(action);if(action==='seasonEnd'&&result.stopReason==='target'&&result.processed)this.store.set(state=>{const settled=settleSeason(state);if(settled.trophies.length||settled.personalAwards.length)this.feedback.emit('newRecord',`赛季荣誉 ${settled.trophies.length+settled.personalAwards.length} 项`);return state;});if(result.event)this.feedback.emit('newEvent',result.event.title);if(result.match){this.feedback.emit('matchReady',`${result.match.opponent} · 比赛节点`);if(result.stopReason==='match')this.navigate('match');}if(result.processed)this.feedback.emit('seasonSummary',`已完成 ${result.processed} 个推进单元，停止原因：${result.stopReason}`);}

  openTrainingStrategy(){const s=this.store.get();this.overlay.sheet('自动训练策略',`<div class="choice-grid">${[['balanced','平衡成长','均衡能力与疲劳'],['weakness','补齐短板','优先最低属性'],['strength','放大优势','强化最高属性'],['recovery','健康优先','伤病与疲劳优先']].map(([id,name,copy])=>`<button class="choice-card ${s.training.autoStrategy===id?'active':''}" data-strategy="${id}"><h3>${name}</h3><p>${copy}</p></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-strategy]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{st.training.autoStrategy=btn.dataset.strategy;return st;});this.feedback.emit('trainingSuggested',btn.textContent.trim());this.overlay.close();})});}

  resolveMatchAfterInteraction(match,tactic=DEFAULT_MATCH_TACTIC,interactionId='shooting',input=null){
    const tacticStyle=tactic.style||tactic.id,s=this.store.get(),seed=new Date(match.date).getUTCDate()+s.player.ovr+s.season.appearances*7;
    const interaction=resolveMatchInteraction({id:interactionId,player:s.player,seed,input});
    const played=60+(seed%31),rating=Number(clamp(6.1+(s.player.ovr-55)/30+tactic.mods.rating+interaction.ratingBonus+((seed%7)-3)/10,5.5,9.6).toFixed(1));
    const goals=(seed%9===0||rating>8.4||(interaction.goalChance>0&&seed%10<Math.round(interaction.goalChance*10)))?1:0;
    const assists=(seed%7===0||tacticStyle==='creative'&&seed%3===0||interaction.option.id==='passing'&&interaction.success)?1:0;
    const teamGoals=goals+1+(seed%3),oppGoals=seed%3,liveHighlight=input?.matchState?.highlights?.at(-1),card=liveHighlight?.card;
    const timeline=[{time:'12′',title:'第一次高位压迫',copy:'迫使对手边后卫回传，教练在场边鼓掌。'},{time:'41′',title:tacticStyle==='creative'?'穿透中场的直塞':'稳定完成攻守转换',copy:'你的战术选择改变了球队推进方向。'},{time:`${liveHighlight?.minute||72}′`,title:liveHighlight?.title||interaction.option.name+(interaction.success?'成功':'未能完成'),copy:liveHighlight?.title?`${liveHighlight.title}${interaction.success?'处理成功':'处理出现波动'}，比赛动量已更新。`:interaction.success?`${interaction.option.name}质量 ${interaction.score}，关键镜头转化为比赛优势。`:`${interaction.option.name}质量 ${interaction.score}，对手获得了反击空间。`}];
    let dev;
    this.store.set(st=>{
      const gains=tacticStyle==='creative'?{passing:.30,dribbling:.16}:tacticStyle==='aggressive'?{physical:.22,defending:.18,speed:.12}:{passing:.16,defending:.12,physical:.12};
      gains[interaction.option.stat]=(gains[interaction.option.stat]||0)+(interaction.success?.16:.04);
      dev=applyGrowthToState(st,gains,{source:`比赛表现：${interaction.option.name}`,fatigue:st.player.fatigue,facility:76,coachQuality:75,mode:st.settings.mode,injured:!!activeInjury(st.injuries)});
      st.player.fatigue=clamp(st.player.fatigue+tactic.mods.fatigue,0,100);st.player.fitness=clamp(100-st.player.fatigue*.72,10,100);st.player.morale=clamp(st.player.morale+(teamGoals>=oppGoals?5:-4),0,100);st.player.coachTrust=clamp(st.player.coachTrust+Math.round((rating-6.5)*2),0,100);
      const group=st.player.position==='GK'?'keeper':['CB','LB','RB','LWB','RWB','DM','CDM'].includes(st.player.position)?'defense':['CM','CAM','AM','LM','RM'].includes(st.player.position)?'midfield':'attack';
      const stats={shots:group==='keeper'?0:Math.max(goals,group==='attack'?2+seed%4:group==='midfield'?1+seed%3:seed%3),keyPasses:group==='midfield'?2+seed%3:group==='keeper'?seed%2:seed%3,tackles:group==='defense'?3+seed%4:group==='midfield'?1+seed%3:seed%2,interceptions:group==='defense'?2+seed%4:group==='midfield'?seed%3:0,saves:group==='keeper'?3+seed%5:0,cleanSheets:oppGoals===0&&['keeper','defense'].includes(group)?1:0};
      recordMatchResult(st,match,{played:true,starts:true,minutes:played,goals,assists,rating,...stats,score:`${teamGoals}-${oppGoals}`,card,history:{interaction:interaction.option.name,strategy:tactic.name||'平衡执行',timeline,matchState:input?.matchState||null,card}});
      st.career.marketValue+=Math.round((rating-6)*35000+goals*90000+assists*65000);
      st.news.items.unshift({id:`match-${match.id}`,date:st.simulation.date,type:'比赛',title:`${interaction.option.name}${interaction.success?'处理成功':'出现波动'}`,copy:`${match.competition}结束，${st.player.club} ${teamGoals}-${oppGoals} ${match.opponent}，评分 ${rating}${card?`，${card==='red'?'红牌':'黄牌'}`:''}。`,read:false});st.news.items=st.news.items.slice(0,30);st.ui.matchState=null;return st;
    });
    this.feedback.emit('matchEnd',`${teamGoals}-${oppGoals} · ${interaction.option.name} ${interaction.success?'成功':'波动'} · 评分 ${rating}`);this.feedback.emitMiniGame(interaction.option.mechanic,interaction.success,`${interaction.option.name} · ${interaction.score}分`);if(goals)this.feedback.emit('newRecord','本场取得进球');
    const next=this.simulation.nextNode(this.store.get());this.overlay.sheet('比赛结果',matchResultHtml(this.store.get(),match,{teamGoals,oppGoals,rating,goals,assists,played,timeline,dev,interaction:interaction.option.name,interactionSuccess:interaction.success,matchState:liveHighlight},next),{dismissible:false,onMount:el=>{el.querySelector('[data-home]').onclick=()=>{this.overlay.close();this.navigate('career');};el.querySelector('[data-next-step]').onclick=()=>this.continueAfterMatch(next);}});
  }

  continueAfterMatch(){this.overlay.close();this.navigate('career');}

  openMatchStrategy(match){if(!match)return;const state=this.store.get(),profile=getPositionProfile(state.player.position),strategies=matchStrategiesForPosition(state.player.position);this.overlay.sheet('本场个人策略',`<section class="surface-card"><div class="card-kicker">${icon('tactics','sm')} ${profile.label}职责</div><h3 class="card-title">选择本场执行重点</h3><p class="card-copy">策略会改变场景出现倾向，但比赛仍会产生意外。</p></section><div style="height:12px"></div><div class="stack">${strategies.map(strategy=>`<button class="surface-card decision-card interactive" data-match-strategy="${strategy.id}"><div class="card-row"><strong>${strategy.name}</strong><span class="badge ${strategy.style==='aggressive'?'orange':strategy.style==='creative'?'purple':'blue'}">${strategy.style==='aggressive'?'主动':strategy.style==='creative'?'创造':'稳健'}</span></div><p class="card-copy">${strategy.copy}</p></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-match-strategy]').forEach(button=>button.onclick=()=>{const strategy=strategies.find(item=>item.id===button.dataset.matchStrategy);if(!strategy)return;this.feedback.emit('select',strategy.name);this.overlay.close();this.playMatch(match,strategy);})});}

  playMatch(match,tactic=DEFAULT_MATCH_TACTIC,interactionId=null){
    const state=this.store.get(),unavailable=matchAvailability(state);if(unavailable){this.feedback.emit('failure',unavailable.copy);return false;}const seed=Date.parse(`${match.date}T00:00:00Z`)+state.player.ovr+state.season.appearances*7;const matchState=createMatchState({match,player:state.player,seed,tactic:tactic.id});const director=new HighlightDirector({seed});const matchEvent=new MatchEventEngine(dataRepository.positionEvents||[]).next(matchState,{tactic});let highlight=matchEvent||director.next(matchState);const selectedId=interactionId||highlight.interactionId;const option=MATCH_INTERACTIONS.find(item=>item.id===selectedId)||MATCH_INTERACTIONS[0];const miniGameContext=createMiniGameContext({gameId:selectedId,player:state.player,opponent:{defense:match.opponentDefense||60},match:{pressure:matchState.pressure,importanceValue:match.competition?.includes('杯')?65:50}});const miniGame={...miniGameContext.game,difficulty:miniGameContext.difficulty,...createMiniGameSession(miniGameContext.game.id,'interactiveMatch')};matchState.miniGame=miniGame;matchState.currentEvent=matchEvent?{id:matchEvent.id,templateId:matchEvent.templateId,title:matchEvent.title,interactionId:selectedId}:null;highlight={...highlight,miniGame};
    this.store.set(current=>{current.ui.matchState=matchState;return current;});
    this.overlay.sheet(`比赛模式 · ${match.opponent}`,`<div data-interactive-match-host></div>`,{wide:true,onMount:overlay=>{
      const host=overlay.querySelector('[data-interactive-match-host]');
      const game=createInteractiveMatch({option,player:this.store.get().player,seed,matchState,highlight,onComplete:result=>{this.overlay.close();this.resolveMatchAfterInteraction(match,tactic,selectedId,result);},onSkip:result=>{this.overlay.close();this.resolveMatchAfterInteraction(match,tactic,selectedId,result);}});
      host?.append(game);
      this.overlay.onClose?.(()=>game.destroy?.());
    }});
  }
  openLastMatch(){const last=this.store.get().career.history.filter(x=>x.type==='比赛').at(-1);if(!last)return;this.overlay.sheet(last.summary,`<div class="timeline">${last.timeline.map(x=>`<div class="timeline-item"><div class="timeline-time">${x.time}</div><div class="timeline-title">${x.title}</div><div class="timeline-copy">${x.copy}</div></div>`).join('')}</div>`);}

  requestAgentReport(){const s=this.store.get(),clubs=dataRepository.clubs?.length?dataRepository.clubs:CLUBS,candidates=clubs.filter(c=>c.id!==s.player.clubId&&c.name!==s.player.club&&(c.opportunity??0)>72).slice((s.season.week%5),s.season.week%5+3);this.store.set(st=>{st.transfer.watchlist=[...new Set([...st.transfer.watchlist,...candidates.map(c=>c.id)])];return st;});this.feedback.emit('transferOffer',`经纪人筛选了 ${candidates.map(c=>c.name||c.cn).join('、')}`);}
  handleClubAction(action,club){
    if(!club)return;
    const snapshot=this.store.get(),player=snapshot.player,current=club.id===player.clubId||(club.cn||club.name)===player.club,key=`${club.id}:${action}`,until=snapshot.clubInteractions.cooldowns[key];
    if(until&&until>snapshot.simulation.date)return this.feedback.emit('failure',`该互动冷却至 ${until}`);
    const externalOpen=['compare','interest','agent','contact','expected-contract'];
    if(!current&&!externalOpen.includes(action))return this.feedback.emit('failure','该操作只适用于当前俱乐部');
    const fit=evaluateClubFit({...player,country:player.country||player.nation,recentRating:snapshot.season.rating||6.5},club);
    if(!current&&['interest','agent','contact','expected-contract'].includes(action)&&!fit.eligible)return this.feedback.emit('failure',`当前综合 ${fit.score}，未达到球队门槛 ${fit.required}`);
    const labels={compare:'加入比较',interest:'表达兴趣',agent:'经纪人接触',contact:'请求沟通','expected-contract':'查看预期合同',coach:'与主教练沟通',minutes:'询问出场机会',position:'讨论场上位置',training:'调整训练',loan:'请求外租',stay:'表达留队意愿','transfer-request':'提交转会申请',teammate:'与队友互动',captain:'与队长交流',management:'与管理层沟通',renew:'请求续约'};
    this.store.set(state=>{
      state.clubInteractions.cooldowns[key]=addDateDays(state.simulation.date,current?7:14);
      state.clubInteractions.history.unshift({date:state.simulation.date,clubId:club.id,action,label:labels[action]||action});
      state.clubInteractions.history=state.clubInteractions.history.slice(0,80);
      if(action==='compare'||action==='interest')state.transfer.watchlist=[...new Set([...state.transfer.watchlist,club.id])];
      if(action==='coach'||action==='minutes'||action==='stay')state.player.coachTrust=clamp(state.player.coachTrust+2,0,100);
      if(action==='teammate')state.relationships.teammates=clamp(state.relationships.teammates+2,0,100);
      if(action==='captain')state.relationships.captain=clamp(state.relationships.captain+2,0,100);
      if(action==='training')state.training.autoStrategy='weakness';
      if(action==='position')state.player.morale=clamp(state.player.morale+1,0,100);
      if(action==='loan'||action==='transfer-request')state.transfer.offers.push({id:`request-${state.simulation.date}-${action}`,clubId:club.id,status:'requested',type:action});
      if(action==='renew')state.ui.todos.push({id:`renew-${state.simulation.date}`,type:'合同',title:'续约沟通已预约',date:state.simulation.date});
      if(!current&&action==='contact'&&!state.transfer.offers.some(offer=>offer.clubId===club.id&&offer.status==='inquiry'))state.transfer.offers.push({id:`offer-${state.simulation.date}-${club.id}`,clubId:club.id,status:'inquiry',salary:Math.round((club.finance||60)*350),role:fit.role});
      return state;
    });
    this.feedback.emit(action==='contact'?'transferOffer':'select',`${club.cn||club.name} · ${labels[action]||'互动已记录'}`);
    if(!current&&(action==='contact'||action==='expected-contract'))this.openTransferOffer({...club,fit});
  }
  openTransferOffer(club){
    const wage=Math.round((club.salary||club.finance*350||1800)/100)*100,role=club.fit?.role||(club.opportunity>80?'轮换承诺':'竞争位置'),clubName=club.cn||club.name;
    this.overlay.sheet(`${clubName} · 经纪人沟通`,`<section class="surface-card"><div class="card-kicker">${icon('contract','sm')} 非正式方案</div><h3 class="card-title">周薪 €${wage.toLocaleString('en-US')} · ${role}</h3><p class="card-copy">青训 ${club.academy||club.youth||'—'} · 机会 ${club.opportunity||club.youthUsage||'—'} · 战术 ${club.style||club.tactic||'均衡'}</p></section><div style="height:12px"></div><div class="grid-2">${['接受意向','拒绝','请求更多信息','谈判','请求租借','继续比较'].map((x,i)=>`<button class="app-button ${i===0?'primary':'ghost'}" data-offer="${x}">${x}</button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-offer]').forEach(btn=>btn.onclick=()=>{
      const action=btn.dataset.offer;
      if(action==='继续比较'){this.overlay.close();return;}
      if(action==='谈判')this.feedback.emit('counterOffer','已提出首发承诺与奖金要求');else if(action==='拒绝')this.feedback.emit('failure','报价已礼貌拒绝');else this.feedback.emit('negotiation',action);
      this.openAcknowledgement('经纪人沟通结果',`${clubName}：${action}已记录。`,{onContinue:()=>this.navigate('transfer')});
    })});
  }

  openAnalytics(){const s=this.store.get(),matches=s.career.history.filter(x=>x.type==='比赛').slice(-5);this.overlay.sheet('数据分析',`<div class="grid-2">${summaryCard('analytics','近5场评分',matches.length?`<div class="stat-value">${(matches.reduce((a,b)=>a+b.rating,0)/matches.length).toFixed(2)}</div><p class="card-copy">${matches.map(x=>x.rating).join(' · ')}</p>`:emptyState('样本不足','完成比赛后生成趋势。'))}${summaryCard('growth','训练投入与收益',`<div class="stat-value">${s.career.growthLog.length}</div><p class="card-copy">成长记录 · 当前 OVR ${s.player.ovr}</p>`)}</div><div style="height:14px"></div>${radarChart(s.player.stats,s.player.previousStats||s.player.stats,s.player.potential,s.player.position)}<section class="surface-card"><div class="card-kicker">位置适配</div>${metric(s.player.position,Math.min(96,55+s.player.ovr*.45))}${metric('战术理解',s.player.coachTrust,{tone:'green'})}${metric('状态稳定性',100-s.player.fatigue,{tone:'orange'})}</section>`);}
  openLocker(){const s=this.store.get();this.overlay.sheet('更衣室',`<div class="grid-2">${relationCard('coach','教练组',s.relationships.coach,'首发与培养方向')}${relationCard('teammate','队友',s.relationships.teammates,'训练搭档与场上默契')}${relationCard('fans','球迷',Math.min(100,s.relationships.fans/30),'支持度与舆论')}${relationCard('risk','竞争压力',s.relationships.rivalry,'同位置竞争')}</div><div style="height:14px"></div><div class="choice-grid">${[['安抚队友','关系 +2'],['参加聚餐','士气 +3'],['邀请加练','信任 +2 / 疲劳 +4']].map(([a,b])=>`<button class="choice-card" data-locker="${a}"><h3>${a}</h3><p>${b}</p></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-locker]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{if(btn.dataset.locker==='安抚队友')st.relationships.teammates=clamp(st.relationships.teammates+2,0,100);if(btn.dataset.locker==='参加聚餐')st.player.morale=clamp(st.player.morale+3,0,100);if(btn.dataset.locker==='邀请加练'){st.player.coachTrust=clamp(st.player.coachTrust+2,0,100);st.player.fatigue=clamp(st.player.fatigue+4,0,100);}return st;});this.feedback.emit('teammateRelation',btn.dataset.locker);this.overlay.close();})});}
  openHonors(){const s=this.store.get(),honors=ensureHonors(s),items=[...honors.trophies,...honors.personalAwards],seasonRows=honors.seasons.slice(0,8),legend=honors.legendProfile;this.overlay.sheet('荣誉室',`<div class="card-row"><div><div class="card-kicker">奖杯与个人荣誉</div><h3 class="card-title">${items.length} 项荣誉</h3></div><span class="badge gold">${honors.trophies.length} 团队 · ${honors.personalAwards.length} 个人</span></div><div style="height:12px"></div>${legend?`<section class="result-panel"><div class="card-kicker">传奇档案</div><h3 class="card-title">${legend.tier} · ${legend.score}/100</h3><p class="card-copy">退役后生成的生涯评级，仅基于本存档模拟履历。</p></section><div style="height:12px"></div>`:''}${items.length?`<div class="grid-2">${items.map(item=>`<section class="surface-card honor-card"><div class="card-row"><div class="icon-tile">${trophyMarkup(item,'small')}</div><span class="badge blue">${item.season}</span></div><h3 class="card-title">${item.name}</h3><p class="card-copy">${item.club} · ${item.category==='team'?'团队奖杯':'个人奖项'} · 游戏模拟结算</p></section>`).join('')}</div>`:emptyState('奖杯柜还在等待第一束灯光','赛季结束后，球队成绩和个人表现会在这里形成可回顾的荣誉记录。','trophy')}<div style="height:14px"></div><section class="surface-card"><div class="card-kicker">逐赛季职业履历</div>${seasonRows.length?`<div class="timeline">${seasonRows.map(row=>`<div class="timeline-item"><div class="timeline-time">${row.year}</div><div class="timeline-title">${row.club} · ${row.appearances} 场 · ${row.goals} 球 · ${row.assists} 助攻</div><div class="timeline-copy">评分 ${row.rating||'—'} · 荣誉 ${row.trophies.length+row.personalAwards.length} 项</div></div>`).join('')}</div>`:'<p class="card-copy">完成第一个赛季后，这里会生成你的职业时间线。</p>'}</section>`);}
  openSeasonReview(record){const state=this.store.get(),next=seasonReviewNext(state),keeper=getPositionProfile(record.position).code==='GK',stats=keeper?[['出场',record.appearances],['零封',record.cleanSheets],['扑救',record.saves],['评分',record.rating?.toFixed?.(2)||'—']]:[['出场',record.appearances],['进球',record.goals],['助攻',record.assists],['评分',record.rating?.toFixed?.(2)||'—']],honors=[...record.trophies,...record.personalAwards];this.overlay.sheet('赛季总结',`<section class="surface-card"><div class="card-kicker">${record.year} 赛季总结</div><h3 class="card-title">${state.player.name} · ${record.club}</h3><p class="card-copy">${record.age} 岁 · ${record.position} · ${record.grade} 评级</p></section><div style="height:12px"></div>${statGrid(stats)}<div style="height:12px"></div><section class="surface-card"><div class="card-row"><div><div class="card-kicker">综合能力</div><h3 class="card-title">${record.startOvr} → ${record.endOvr}</h3></div><span class="badge ${record.ovrChange>=0?'green':'orange'}">${record.ovrChange>=0?'+':''}${record.ovrChange}</span></div>${radarChart(record.endStats,record.startStats,state.player.potential,record.position)}</section><div style="height:12px"></div><div class="grid-2">${summaryCard('finance','身价变化',`<strong>€${Math.round(record.startValue/1000)}K → €${Math.round(record.endValue/1000)}K</strong>`)}${summaryCard('trophy','赛季荣誉',honors.length?`<p class="card-copy">${honors.join(' · ')}</p>`:'<p class="card-copy">本季未获得正式荣誉，履历已记录。</p>')}</div><section class="surface-card" style="margin-top:12px"><div class="card-kicker">下一步</div><h3 class="card-title">${next.title}</h3><p class="card-copy">${next.copy}</p></section><button class="app-button primary" style="width:100%;margin-top:12px" data-season-next>${icon('chevron','sm')} ${next.button}</button>`,{dismissible:false,onMount:el=>el.querySelector('[data-season-next]').onclick=()=>{this.overlay.close();this.navigate(next.type==='transfer'||next.type==='contract'?'transfer':'career');}});}
  openCareerShare(){const card=createCareerShareCard(this.store.get());const html=`<section class="surface-card share-card"><div class="card-kicker">生涯档案 · ${escapeHtml(card.club)}</div><h2 class="card-title">${escapeHtml(card.player)}</h2><div class="share-card__legend"><strong>${escapeHtml(card.legend.tier)}</strong><span>${card.legend.score}/100</span></div>${statGrid([['出场',card.totals.appearances],['进球',card.totals.goals],['助攻',card.totals.assists],['赛季',card.seasons],['奖杯',card.trophies],['个人荣誉',card.personalAwards]])}<p class="card-copy">${escapeHtml(card.text).replaceAll('\n','<br>')}</p></section><div class="card-row" style="margin-top:14px"><button class="app-button primary" data-copy-share>${icon('save','sm')}复制生涯卡</button><button class="app-button ghost" data-native-share>${icon('share','sm')}系统分享</button></div>`;const overlay=this.overlay.sheet('生涯分享卡',html,{onMount:sheet=>{sheet.querySelector('[data-copy-share]').onclick=async()=>{try{await navigator.clipboard?.writeText(card.text);this.feedback.emit('save','生涯分享卡已复制')}catch{this.feedback.emit('saveConflict','当前浏览器不允许复制，请手动选择文字')}};sheet.querySelector('[data-native-share]').onclick=async()=>{if(!navigator.share)return this.feedback.emit('empty','当前设备不支持系统分享');try{await navigator.share({title:`${card.player}的生涯`,text:card.text})}catch(error){if(error?.name!=='AbortError')this.feedback.emit('networkFail','系统分享未完成')}}}});return overlay;}
  openLeaderboard(){const s=this.store.get();const rows=[['你',s.player.ovr,s.season.goals,s.season.assists],['青年新星 A',72,8,5],['青年新星 B',69,4,9],['青年新星 C',67,7,3]];this.overlay.sheet('生涯排行榜',`<div class="stack">${rows.sort((a,b)=>b[1]-a[1]).map((r,i)=>`<div class="surface-card"><div class="card-row"><div class="card-row" style="justify-content:flex-start"><span class="badge ${i===0?'gold':'blue'}">#${i+1}</span><strong>${r[0]}</strong></div><span>OVR ${r[1]}</span></div><p class="card-copy">${r[2]}球 · ${r[3]}助攻</p></div>`).join('')}</div>`);}
  openCareerHub(){
    const s=this.store.get();
    this.overlay.sheet('我的生涯',`<div class="action-grid">${facilityTile('calendar','生涯总结',`${s.season.appearances}场 · ${s.season.goals}球`,'summary')}${facilityTile('teammate','关系','教练、队友与球迷','relations')}${facilityTile('trophy','荣誉室',`${(s.career.honors?.trophies?.length||0)+(s.career.honors?.personalAwards?.length||0)} 项荣誉`,'honors')}${facilityTile('save','存档设置','导入、导出与重置','save')}</div><div style="height:14px"></div><button class="app-button danger" data-retire>提前退役</button>`,{onMount:el=>{el.onclick=e=>{
      const k=e.target.closest('[data-facility]')?.dataset.facility;
      if(k==='relations')this.openLocker();if(k==='honors')this.openHonors();if(k==='save')this.openSettings();if(k==='summary')this.feedback.emit('seasonSummary',`${s.season.appearances}场比赛`);
      if(e.target.closest('[data-retire]'))this.overlay.dialog('确认提前退役','<p class="card-copy">当前存档会保留，可在生涯回顾中查看。</p><button class="app-button danger" data-confirm-retire>确认退役</button>').querySelector('[data-confirm-retire]').onclick=()=>{
        let retirement;this.store.set(state=>{retirement=retireCareer(state);return state;});this.feedback.emit('careerEnd','生涯进入回顾模式');this.overlay.close();this.openAcknowledgement('退役档案已生成',retirement.summary,{button:'查看生涯回顾',onContinue:()=>this.openCareerHub()});
      };
    }}});
  }
  openContract(){const s=this.store.get();this.overlay.sheet('合同详情',`<section class="surface-card"><div class="card-kicker">${icon('contract','sm')} ${s.player.club}</div><h3 class="card-title">周薪 €${s.career.weeklySalary}</h3><p class="card-copy">剩余 ${s.career.contractMonths} 个月 · 当前身价 €${Math.round(s.career.marketValue/1000)}K</p>${statGrid([['角色','青年队核心'],['出场承诺','竞争'],['奖金','按出场'],['解约金','未设置']])}</section><div style="height:12px"></div><button class="app-button primary" data-renew>请求谈新合同</button>`,{onMount:el=>el.querySelector('[data-renew]').onclick=()=>{this.feedback.emit('negotiation','经纪人已预约体育总监');this.overlay.close();}});}
  openSettings(){const s=this.store.get();const levels=audioManager.settings;this.overlay.sheet('设置与存档',`<div class="stack"><section class="surface-card"><div class="card-kicker">体验设置</div>${settingToggle('sound','音效',s.settings.sound)}${settingToggle('haptics','触控反馈',s.settings.haptics)}${settingToggle('autoSkipLow','自动跳过低优先事件',s.settings.autoSkipLow)}${settingToggle('autoPauseCritical','关键事件自动暂停',s.settings.autoPauseCritical)}<div class="audio-mixer">${[['master','总音量'],['music','音乐音量'],['ambience','环境音量'],['effects','效果音量']].map(([key,label])=>`<label>${label}<input type="range" min="0" max="1" step=".01" value="${levels[key]}" data-audio="${key}"></label>`).join('')}</div></section><section class="surface-card"><div class="card-kicker">存档管理</div><div class="card-row" style="margin-top:12px"><button class="app-button ghost" data-export>导出存档</button><label class="app-button ghost">导入存档<input type="file" data-import accept="application/json" hidden></label><button class="app-button danger" data-reset>重置</button></div></section></div>`,{onMount:el=>{el.querySelectorAll('[data-setting]').forEach(x=>x.onchange=()=>{this.store.set(st=>{st.settings[x.dataset.setting]=x.checked;return st;});if(x.dataset.setting==='sound')audioManager.setMuted(!x.checked);});el.querySelectorAll('[data-audio]').forEach(x=>x.oninput=()=>audioManager.setLevel(x.dataset.audio,x.value));el.querySelector('[data-export]').onclick=()=>{const blob=new Blob([this.store.export()],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='football-career-save.json';a.click();URL.revokeObjectURL(a.href);this.feedback.emit('save','存档文件已导出');};el.querySelector('[data-import]').onchange=async e=>{try{this.store.import(await e.target.files[0].text());this.feedback.emit('save','存档已导入');this.overlay.close();}catch{this.feedback.emit('saveConflict','文件无法读取');}};el.querySelector('[data-reset]').onclick=()=>{if(confirm('确定重置全部生涯数据？')){this.store.reset();this.overlay.close();this.mount();}};}});}
}

App.prototype.openThemeSettings=function(){const current=this.store.get().settings.theme;this.overlay.sheet('主题外观',`<div class="choice-grid">${[['system','跟随系统','根据设备外观自动切换'],['dark','深色','深色背景与低亮度表面'],['light','浅色','明亮背景与清晰层级']].map(([id,label,copy])=>`<button class="choice-card ${current===id?'active':''}" data-theme-mode="${id}"><h3>${label}</h3><p>${copy}</p></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-theme-mode]').forEach(btn=>btn.onclick=()=>{this.store.set(state=>{state.settings.theme=btn.dataset.themeMode;return state;});applyTheme(btn.dataset.themeMode);this.overlay.close();})});};
App.prototype.openNewsCenter=function(){const items=this.store.get().news.items;this.store.set(state=>{state.news.items.forEach(item=>{item.read=true});state.news.unread=0;return state;});this.overlay.sheet('新闻中心',items.length?`<div class="news-list">${items.map(item=>`<article class="surface-card news-item"><div class="card-row"><span class="badge ${item.type==='比赛'?'blue':item.type==='训练'?'green':'purple'}">${item.type}</span><time class="card-copy">${item.date}</time></div><h3 class="card-title">${item.title}</h3><p class="card-copy">${item.copy}</p></article>`).join('')}</div>`:emptyState('暂无新闻','推进比赛或训练后，新的足球动态会安静地出现在这里。','message'));};
function summaryCard(iconName,title,body){return `<section class="surface-card"><div class="card-kicker">${icon(iconName,'sm')} ${title}</div><div style="height:10px"></div>${body}</section>`;}
function facilityTile(iconName,title,copy,key){return `<button class="action-tile" data-facility="${key}"><div class="icon-tile">${icon(iconName)}</div><h3>${title}</h3><p>${copy}</p></button>`;}
function treatmentCard(id,title,copy){return `<button class="surface-card interactive" data-treatment="${id}"><div class="icon-tile">${icon(id==='aggressive'?'fast':id==='light'?'recovery':'medical')}</div><h3 class="card-title">${title}</h3><p class="card-copy">${copy}</p></button>`;}
function relationCard(iconName,title,value,copy){return `<section class="surface-card"><div class="card-row"><div class="icon-tile">${icon(iconName)}</div><span class="badge blue">${Math.round(value)}</span></div><h3 class="card-title">${title}</h3><p class="card-copy">${copy}</p>${metric('状态',value,{tone:value>65?'green':value<35?'red':''})}</section>`;}
function eventIcon(category){return {训练:'training',关系:'teammate',媒体:'media',医疗:'medical',转会:'transfer',比赛:'match',合同:'contract',生活:'fans',成长:'growth',家庭:'home',争议判罚:'referee','重大剧情':'risk'}[category]||'message';}
function interactionLabel(value){return {rhythm:'节奏互动',observation:'观察判断',interview:'多轮采访',risk:'风险决策',envelope:'转会信封',tactics:'战术路线',negotiation:'合同谈判',balance:'关系平衡',sequence:'顺序安排',dice:'不确定判定',wheel:'活动转盘',flip:'训练卡牌',timeline:'职业路线',unlock:'隐藏条件',keymoment:'关键时刻',branch:'分支选择'}[value]||'职业决策';}
function rarityLabel(value){return {common:'普通',rare:'稀有',hidden:'隐藏',crisis:'危机',opportunity:'机会',legendary:'传奇'}[value]||'普通';}
function riskLabel(value){const risk=Number(value)||20;return risk>=60?'高风险':risk>=35?'中风险':'低风险';}
function formatParticipants(event){return Array.isArray(event?.participants)&&event.participants.length?event.participants.join('、'):'暂无指定参与者';}
function interactionPanel(e){const observations=Array.isArray(e.observations)&&e.observations.length?e.observations:['当前事件没有额外线索，结果将根据你的状态与选择结算。'];const list=`<div class="surface-card" style="box-shadow:none;background:rgba(91,108,135,.05)"><div class="card-kicker">可观察信息</div><div class="timeline">${observations.map((x,i)=>`<div class="timeline-item"><div class="timeline-time">线索 ${i+1}</div><div class="timeline-copy">${x}</div></div>`).join('')}</div></div>`;const special={dice:`<div class="result-panel"><b>骰子判定</b><p class="card-copy">选项会与潜力、士气和当前状态共同决定结果。</p></div>`,wheel:`<div class="result-panel"><b>活动转盘</b><p class="card-copy">随机挑战会改变粉丝、媒体与心态。</p></div>`,risk:`<div class="result-panel"><b>风险滑杆</b><input type="range" min="0" max="100" value="45" style="width:100%"><p class="card-copy">风险越高，短期收益与复发概率越高。</p></div>`,tactics:`<div class="pitch" style="aspect-ratio:2.2"><span class="position-node active" style="left:52%;top:54%">你</span><span class="position-node" style="left:72%;top:26%">空当</span></div>`,negotiation:`<div class="result-panel"><b>合同筹码</b><div class="tag-row"><span class="badge blue">薪资</span><span class="badge green">出场</span><span class="badge orange">奖金</span><span class="badge purple">解约金</span></div></div>`,flip:`<div class="result-panel"><b>两张反扣卡</b><p class="card-copy">选择后会翻开训练内容并立即结算。</p></div>`,interview:`<div class="result-panel"><b>多轮采访</b><p class="card-copy">记者会记住你的措辞，后续问题受本次回答影响。</p></div>`,timeline:`<div class="timeline"><div class="timeline-item"><div class="timeline-title">出场路线</div></div><div class="timeline-item"><div class="timeline-title">荣誉路线</div></div><div class="timeline-item"><div class="timeline-title">商业路线</div></div></div>`,envelope:`<div class="result-panel"><b>神秘信封已拆封</b><p class="card-copy">三家俱乐部的条件不会同时完整公开。</p></div>`,sequence:`<div class="result-panel"><b>顺序安排</b><p class="card-copy">前后顺序会改变训练稳定性和录像评价。</p></div>`,balance:`<div class="result-panel"><b>关系平衡</b><p class="card-copy">帮助一方可能改变另一方对你的看法。</p></div>`,keymoment:`<div class="pitch" style="aspect-ratio:2.2"><span class="position-node active" style="left:54%;top:48%">持球</span><span class="position-node" style="left:76%;top:32%">前锋</span></div>`,unlock:`<div class="result-panel"><b>隐藏条件</b><p class="card-copy">只有部分属性或关系达到要求时，额外选项才会出现。</p></div>`,branch:`<div class="result-panel"><b>分支时间线</b><p class="card-copy">本次选择会在医疗、转会和比赛系统中产生延迟后果。</p></div>`,observation:list,rhythm:`<div class="result-panel"><b>训练节奏互动</b><p class="card-copy">精确、爆发或提前收操将产生不同负荷。</p></div>`};return special[e.interaction]||list;}
function resultPanel(result){const effects=Object.entries(result.effects||{});return `<div class="result-panel" data-result-animation="${pickOutcomeAnimation(result.outcome==='success'?'success':'failure',result.eventId||result.choiceId)}"><div class="card-kicker">${icon(result.outcome==='success'?'check':'close','sm')} ${result.outcome==='success'?'路线兑现':'风险落地'} · ${rarityLabel(result.rarity)}</div><h3 class="card-title">${result.choiceLabel}</h3><div class="change-grid"><div class="change-item"><b>${result.outcome==='success'?'处理成功':'需要复盘'}</b><span>判定同时参考当前位置、体能、士气、关系和随机种子</span></div>${effects.length?effects.map(([k,v])=>`<div class="change-item"><b>${effectName(k)} ${typeof v==='number'&&v>0?'+':''}${v}</b><span>${effectHint(k)}</span></div>`).join(''):`<div class="change-item"><b>状态已记录</b><span>影响会在后续剧情中出现</span></div>`}</div><div class="card-footer"><span class="card-copy">${result.followUp?`后续回访：${result.followUp.dueDate}`:'隐藏影响已写入角色记忆与后续事件权重'}</span></div></div><div class="grid-3" style="margin-top:12px"><button class="app-button ghost" data-result-back>返回页面</button><button class="app-button secondary" data-result-next>下一待办</button><button class="app-button primary" data-result-continue>返回生涯首页</button></div>`;}
function effectName(k){return {...ATTR_CN,fatigue:'疲劳',morale:'士气',trust:'教练信任',relationship:'队友关系',fans:'粉丝',media:'媒体形象',marketValue:'身价',risk:'伤病风险',recovery:'恢复进度',transferInterest:'转会兴趣',potential:'潜力',trait:'新特质',rivalry:'竞争关系'}[k]||k;}
function effectHint(k){return ['speed','shooting','passing','dribbling','defending','physical'].includes(k)?'内部浮点成长':'将影响后续状态与事件';}
function modeName(m){return {standard:'标准',fast:'快速',legend:'传奇',ultra:'极速'}[m];}
function modeCopy(m){return {standard:'平衡事件密度与比赛反馈',fast:'折叠低价值内容，保留关键节点',legend:'更多剧情与高波动职业抉择',ultra:'快速推进，仅危机和关键职业事件暂停'}[m];}
function settingToggle(key,label,checked){return `<label class="card-row" style="min-height:54px;border-top:1px solid var(--line)"><span>${label}</span><input type="checkbox" data-setting="${key}" ${checked?'checked':''}></label>`;}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function matchNextStep(next){if(next?.blocked)return next.type==='event'?{title:'处理职业事件',copy:'新的职业事件正在等待你的决定。',button:'返回生涯首页'}:{title:'完成关键训练',copy:'训练机会已到达，选择方案后继续赛季。',button:'返回生涯首页'};if(next?.type==='match')return{title:next.label,copy:`下一场关键比赛：${next.match?.opponent||'等待赛程确认'}`,button:'返回生涯首页'};if(next?.type==='season')return{title:'进入赛季总结',copy:'本赛季已到收官节点，接下来结算荣誉与履历。',button:'返回生涯首页'};return{title:'继续模拟赛季',copy:'普通比赛会自动结算，只在重要节点暂停。',button:'返回生涯首页'};}
function matchResultHtml(s,match,r,next){const step=matchNextStep(next);return `<div class="card-row"><div><div class="card-kicker">${match.competition}</div><h3 class="card-title">${s.player.club} ${r.teamGoals}-${r.oppGoals} ${match.opponent}</h3><p class="card-copy">${r.played}分钟 · 个人评分 ${r.rating}</p></div><span class="badge ${r.teamGoals>=r.oppGoals?'green':'orange'}">${r.teamGoals>=r.oppGoals?'不败':'失利'}</span></div><div style="height:12px"></div><div class="result-panel"><strong>${r.interaction}：${r.interactionSuccess?'成功':'波动'}</strong><p class="card-copy">关键镜头会同时影响比赛结果、成长和后续新闻。</p></div><div style="height:12px"></div><div class="grid-2">${summaryCard('analytics','比赛表现',statGrid([['评分',r.rating],['时间',`${r.played}′`],['进球',r.goals],['助攻',r.assists]]))}${summaryCard('match','关键动作',`<p class="card-copy">${r.timeline.at(-1).title}<br>${r.timeline.at(-1).copy}</p>`)}${summaryCard('coach','教练评价',`<p class="card-copy">${r.rating>=7.5?'很好地执行了战术要求，首发竞争明显升温。':'完成基础任务，仍需提高无球参与。'}</p>`)}${summaryCard('growth','成长与状态',`<p class="card-copy">${Object.entries(r.dev.changes).filter(([,v])=>v>0).map(([k,v])=>`${ATTR_CN[k]} +${v.toFixed(2)}`).join(' · ')||'保持稳定'}</p>`)}</div><div style="height:14px"></div><div class="timeline">${r.timeline.map(x=>`<div class="timeline-item"><div class="timeline-time">${x.time}</div><div class="timeline-title">${x.title}</div><div class="timeline-copy">${x.copy}</div></div>`).join('')}</div><section class="surface-card" style="margin-top:15px"><div class="card-kicker">${icon('fast','sm')} 下一步</div><h3 class="card-title">${step.title}</h3><p class="card-copy">${step.copy}</p></section><div class="card-row" style="margin-top:12px"><button class="app-button ghost" data-home>返回生涯首页</button><button class="app-button primary" data-next-step>${icon('chevron','sm')} ${step.button}</button></div>`;}

const app=new App();
app.runSimulation=async function(action){
  this.overlay.close();
  const result=await this.simulation.advance(action);
  if(result.status==='paused')return this.feedback.emit('pause','请先恢复推进');
  if(result.status==='needs-training'||result.trainingOpportunity){this.feedback.emit('trainingSuggested','关键训练机会已生成');return this.navigate('training');}
  if(action==='seasonEnd'&&result.stopReason==='target'&&result.processed){
    let settled;this.store.set(state=>{settled=settleSeason(state);if(settled.trophies.length||settled.personalAwards.length)this.feedback.emit('newRecord',`赛季荣誉 ${settled.trophies.length+settled.personalAwards.length} 项`);return state;});
    if(!settled.alreadySettled)return this.openSeasonReview(settled.record);
    return this.navigate('career');
  }
  if(result.event)this.feedback.emit('newEvent',result.event.title);
  if(result.match)this.feedback.emit('matchReady',`${result.match.opponent} · ${result.match.date}`);
  if(result.processed)this.feedback.emit('seasonSummary',`已推进 ${result.processed} 天，下一节点已准备`);
};
app.startTraining=function(plan){
  const current=this.store.get().training.currentOpportunity;
  if(!plan||!current?.choices?.some(item=>item.id===plan.id))return this.feedback.emit('empty','当前没有这个训练机会');
  const game=plan.game||trainingGameById(plan.gameId);
  let gameNode=null;
  this.overlay.sheet(`${plan.name} · 训练实战`,'<div data-training-game-host></div>',{wide:true,onClose:()=>gameNode?.destroy?.(),onMount:sheet=>{
    gameNode=createTrainingGame(game,{motion:this.store.get().settings.motion,onComplete:result=>{this.overlay.close();this.completeTraining(plan,result);},onSkip:result=>{this.overlay.close();this.completeTraining(plan,result);}});
    sheet.querySelector('[data-training-game-host]')?.append(gameNode);gameNode?.focus?.();
  }});
};
app.completeTraining=function(plan,gameResult={score:72,grade:'B',detail:'保守结算'}){
  let outcome, resolved=plan;
  const score=Math.max(0,Math.min(100,Number(gameResult.score)||50));
  const factor=.72+score/100*.62;
  this.store.set(state=>{
    resolved=resolveTrainingOpportunity(state,plan.id)||plan;
    const gains=Object.fromEntries(Object.entries(resolved.gains||{}).map(([key,value])=>[key,Number(value)*factor]));
    if(resolved.goalkeepingGains)gains.goalkeeping=Object.fromEntries(Object.entries(resolved.goalkeepingGains).map(([key,value])=>[key,Number(value)*factor]));
    outcome=applyGrowthToState(state,gains,{source:`训练：${resolved.name} · ${gameResult.grade||'B'}级`,fatigue:state.player.fatigue,injured:!!activeInjury(state.injuries),facility:78+state.training.facilityLevel*2,coachQuality:75+state.training.coachBonus,mode:state.settings.mode});
    const fatigue=Number(gameResult.skipped?Math.max(0,resolved.fatigue*.65):resolved.fatigue);
    state.player.fatigue=clamp(state.player.fatigue+fatigue,0,100);state.player.fitness=clamp(100-state.player.fatigue*.72,10,100);
    state.player.coachTrust=clamp(state.player.coachTrust+Math.round(score>=80?3:2),0,100);state.training.completedWeek=state.season.week;state.training.selectedPlan=resolved.id;
    state.training.plansUsed.push({week:state.season.week,plan:resolved.id,gameId:gameResult.gameId,score});
    const beforeFatigue=state.player.fatigue-fatigue;
    state.training.lastResult={date:state.simulation.date,plan:resolved.id,gameId:gameResult.gameId,score,grade:gameResult.grade,detail:gameResult.detail,changes:outcome.changes};
    state.training.sessions.push({date:state.simulation.date,week:state.season.week,gameId:gameResult.gameId,plan:resolved.id,score,grade:gameResult.grade,detail:gameResult.detail,changes:outcome.changes,ovr:outcome.player.ovr,fatigueBefore:beforeFatigue,fatigueAfter:state.player.fatigue});
    state.training.sessions=state.training.sessions.slice(-60);state.training.bestScores[gameResult.gameId]=Math.max(score,Number(state.training.bestScores[gameResult.gameId]||0));state.training.streak=score>=65?state.training.streak+1:0;
    if(score>=80)state.training.challenge.progress+=1;
    addNews(state,{id:`training-${state.simulation.date}-${resolved.id}`,date:state.simulation.date,type:'训练',title:`${resolved.name}完成 · ${gameResult.grade||'B'}级`,copy:`${gameResult.detail||'训练反馈已记录'}，本次成长已写入生涯。`,read:false});
    state.route='career';return state;
  });
  this.feedback.emit('trainingComplete',`${resolved.name} · ${gameResult.grade||'B'}级 · ${score}分`);this.feedback.emitMiniGame(resolved.mechanic,score>=65,`${resolved.name} · ${score}分`);
  if(outcome.breakthroughs.length)this.feedback.emit('attributeUp',outcome.breakthroughs.map(key=>ATTR_CN[key]).join('、'));
  const current=this.store.get();
  this.overlay.sheet('训练结算',`<div class="result-panel training-result" data-result-animation="${pickOutcomeAnimation(score>=65?'success':'failure',resolved.id)}"><div class="card-kicker">${icon('training','sm')} ${resolved.name}</div><div class="card-row"><div><h3 class="card-title">${gameResult.grade||'B'}级 · ${score}分</h3><p class="card-copy">${gameResult.detail||'训练反馈已记录'}</p></div><span class="badge ${score>=80?'green':score>=60?'blue':'orange'}">${score>=90?'新纪录':score>=80?'高评价':'已记录'}</span></div><div class="change-grid">${Object.entries(outcome.changes).filter(([,value])=>value).map(([key,value])=>`<div class="change-item"><b>${ATTR_CN[key]} ${value>0?'+':''}${value.toFixed(2)}</b><span>成长已写入属性进度</span></div>`).join('')}<div class="change-item"><b>综合能力 ${outcome.overallChange>=0?'+':''}${outcome.overallChange}</b><span>体能 ${Math.round(current.player.fitness)} · 疲劳 ${Math.round(current.player.fatigue)}</span></div></div></div>${radarChart(current.player.stats,current.player.previousStats||current.player.stats,current.player.potential,current.player.position)}<div class="card-row"><span class="card-copy">训练记录已保存，确认后返回生涯首页。</span><button class="app-button primary" data-training-result-close>继续</button></div>`,{dismissible:false,onMount:el=>el.querySelector('[data-training-result-close]').onclick=()=>{this.overlay.close();this.navigate('career');}});
};
app.openSimulation=function(){const state=this.store.get(),node=this.simulation.nextNode(state),blocked=Boolean(node.blocked),detail=blocked?'存在必须先处理的待办，完成后才能推进。':node.type==='match'?`${node.target} · ${node.match?.opponent||''}`:`推进到 ${node.target||state.simulation.date}`;this.overlay.sheet('继续生涯',`<section class="continue-node ${blocked?'is-blocked':''}"><div class="card-kicker">${icon(blocked?'todo':node.type==='match'?'match':'fast','sm')} 下一关键节点</div><h3 class="card-title">${node.label}</h3><p class="card-copy">${detail}</p>${blocked?'<span class="badge red">强制待办</span>':'<span class="badge green">空白日期将自动跳过</span>'}</section><div style="height:14px"></div><button class="app-button ${blocked?'danger':'primary'}" style="width:100%" data-continue>${blocked?'现在处理待办':'继续'}</button><div style="height:14px"></div><section class="surface-card"><div class="card-kicker">节奏模式</div><div class="choice-grid">${[['fast','快速','少量关键节点，成长倍率更高'],['standard','标准','训练、比赛和事件平衡'],['legend','传奇','内容更密集，决策风险更高']].map(([id,name,copy])=>`<button class="choice-card ${state.settings.mode===id?'active':''}" data-mode="${id}"><h3>${name}</h3><p>${copy}</p></button>`).join('')}</div></section>`,{onMount:el=>{el.querySelector('[data-continue]').onclick=()=>{this.overlay.close();if(blocked){const event=this.store.get().events.pending[0];event?this.openEvent(event):this.navigate('training');}else this.runSimulation(node.action);};el.querySelectorAll('[data-mode]').forEach(btn=>btn.onclick=()=>{this.store.set(current=>{current.settings.mode=btn.dataset.mode;current.simulation.speed={fast:2,standard:1,legend:1}[btn.dataset.mode];return current;});this.feedback.emit('select',btn.textContent.trim());this.overlay.close();});}});};
app.openOffSeason=function(){const phase=this.store.get().career?.offSeason;if(!phase||phase.status!=='active')return this.navigate('career');const remaining=phase.activities.filter(item=>!phase.completed.includes(item.id));const cards=remaining.map(item=>'<button class="choice-card" data-off-season="'+item.id+'"><h3>'+escapeHtml(item.title)+'</h3><p>'+escapeHtml(item.copy)+'</p></button>').join('');const body='<section class="surface-card"><div class="card-kicker">赛季之间</div><h3 class="card-title">安排你的休赛期</h3><p class="card-copy">没有比赛和强制训练。选择 0 至 2 项场外安排，再开始新赛季。</p></section><div style="height:12px"></div>'+(cards?'<div class="choice-grid">'+cards+'</div>':'<section class="result-panel"><b>安排已完成</b><p class="card-copy">你已完成本次休赛期选择，可以开启新赛季。</p></section>')+'<button class="app-button primary" style="width:100%;margin-top:12px" data-off-season-complete>开始新赛季</button>';this.overlay.sheet('休赛期',body,{onMount:el=>{el.querySelectorAll('[data-off-season]').forEach(button=>button.onclick=()=>{let activity;this.store.set(state=>{activity=resolveOffSeasonActivity(state,button.dataset.offSeason);return state;});if(activity){this.feedback.emit(activity.id==='recovery'?'recovered':'select',activity.title);this.openOffSeason();}});el.querySelector('[data-off-season-complete]').onclick=()=>{this.store.set(state=>{completeOffSeason(state);return state;});this.overlay.close();this.navigate('career');};}});};
const openSimulation = app.openSimulation;
app.openSimulation=function(){const state=this.store.get();if(state.route!=='career'){this.feedback.emit('todo','请在生涯首页推进时间');return this.navigate('career');}if(state.career?.offSeason?.status==='active')return this.openOffSeason();return openSimulation.call(this);};
dataRepository.init().then(()=>app.store.set(state=>{replaceFictionalFixtures(state,dataRepository.clubs);return state;})).catch(error=>console.warn('world data unavailable, using local fallback',error)).finally(()=>app.mount());
if('serviceWorker' in navigator) addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
