import { Store } from './core/store.js';
import { EventEngine } from './core/eventEngine.js';
import { SimulationController } from './core/simulationController.js';
import { FeedbackDirector } from './core/feedbackDirector.js';
import { AnimationDirector } from './core/animationDirector.js';
import { applyGrowthToState } from './core/playerDevelopmentEngine.js';
import { createInjury, chooseTreatment, activeInjury } from './core/injuryEngine.js';
import { icon } from './components/icons.js';
import { OverlayManager, playerDetail, metric, statGrid, emptyState } from './components/ui.js';
import { radarChart } from './components/radar.js';
import { createPlayerWizard } from './pages/createPlayer.js';
import { careerPage } from './pages/career.js';
import { trainingPage } from './pages/training.js';
import { matchPage } from './pages/match.js';
import { transferPage } from './pages/transfer.js';
import { morePage } from './pages/more.js';
import { CLUBS } from './data/clubs.js';
import { keyedRandom } from './services/rng.js';

const ROUTES={career:['home','??'],match:['match','??'],training:['training','??'],transfer:['transfer','??'],more:['settings','??']};
const ATTR_CN={speed:'??',shooting:'??',passing:'??',dribbling:'??',defending:'??',physical:'??'};
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));

class App {
  constructor(){
    this.root=document.querySelector('#app');
    this.overlay=new OverlayManager(document.querySelector('#overlay-root'));
    this.store=new Store();
    this.events=new EventEngine();
    this.simulation=new SimulationController(this.store,this.events);
    this.feedback=new FeedbackDirector(document.body);
    this.animation=new AnimationDirector();
    this.store.subscribe(()=>this.render());
  }
  mount(){
    if(!this.store.get().player){this.root.replaceChildren(createPlayerWizard(this));return;}
    this.root.innerHTML='<div class="app-shell"><div data-topbar></div><main class="app-main" data-page></main><div data-tabbar></div></div>';
    this.render();
    if(!this.store.get().events.pending.length && !this.store.get().events.history.length){this.store.set(s=>{this.events.schedule(s,{priority:'normal'});return s;});}
  }
  render(){
    const shell=this.root.querySelector('.app-shell');
    if(!this.store.get().player){if(!this.root.querySelector('.wizard-shell'))this.root.replaceChildren(createPlayerWizard(this));return;}
    if(!shell){this.mount();return;}
    const state=this.store.get();
    shell.querySelector('[data-topbar]').innerHTML=this.topbar(state);
    const page=shell.querySelector('[data-page]'); page.replaceChildren(this.page(state));
    shell.querySelector('[data-tabbar]').innerHTML=this.tabbar(state);
    this.bindShell();
  }
  page(state){ return ({career:careerPage,match:matchPage,training:trainingPage,transfer:transferPage,more:morePage}[state.route]||careerPage)(this,state); }
  topbar(state){const p=state.player;return `<header class="app-topbar"><div class="identity"><div class="avatar">${p.number}</div><div class="identity-copy"><div class="identity-name">${p.name}</div><div class="identity-meta">${p.club} ? ${p.age}? ? ?${Math.round(state.career.marketValue/1000)}K</div></div></div><div class="top-actions"><button class="icon-button ${state.simulation.paused?'active':''}" data-top-pause aria-label="${state.simulation.paused?'??':'??'}">${icon(state.simulation.paused?'play':'pause')}</button><button class="app-button ghost" data-top-speed>${icon('fast','sm')}${state.simulation.paused?'??':`${state.simulation.speed}?`}</button><button class="icon-button top-save" data-top-save aria-label="??">${icon('save')}</button></div></header>`;}
  tabbar(state){return `<nav class="glass-tabbar" aria-label="???">${Object.entries(ROUTES).map(([key,[ico,label]])=>`<button class="tab-item ${state.route===key?'active':''}" data-route="${key}">${icon(ico)}<span class="tab-label">${label}</span></button>`).join('')}</nav>`;}
  bindShell(){
    this.root.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>this.navigate(el.dataset.route));
    this.root.querySelector('[data-top-pause]')?.addEventListener('click',()=>{const paused=this.store.get().simulation.paused;paused?this.simulation.resume():this.simulation.pause();this.feedback.emit(paused?'resume':'pause',paused?'???????':'????????????????');});
    this.root.querySelector('[data-top-speed]')?.addEventListener('click',()=>this.openSimulation());
    this.root.querySelector('[data-top-save]')?.addEventListener('click',()=>{this.store.save();this.feedback.emit('save','???????');});
  }
  navigate(route){this.overlay.close();this.store.set(s=>{s.route=route;return s;});window.scrollTo({top:0,behavior:'smooth'});}

  openPlayerDetail(){const s=this.store.get();this.overlay.sheet('????',playerDetail(s.player,s));}
  openCareerData(){const s=this.store.get(),next=s.schedule.find(m=>m.status==='upcoming');this.overlay.sheet('??????',`<div class="grid-2">${summaryCard('calendar','????',statGrid([['??',s.season.appearances],['??',s.season.goals],['??',s.season.assists],['??',s.season.rating||'?']]))}${summaryCard('record','????',statGrid([['OVR',s.player.ovr],['??',Math.round(s.player.potential)],['??',`?${Math.round(s.career.marketValue/1000)}K`],['??',`${s.career.contractMonths}?`]]))}</div><div style="height:14px"></div><section class="surface-card"><div class="card-kicker">?????</div>${next?`<h3 class="card-title">${next.competition} ? ${next.opponent}</h3><p class="card-copy">${next.date} ? ${next.venue}</p>`:emptyState('????','???????????????')}</section>`);}
  openGoals(){const s=this.store.get();const goals=s.season.objectives.length?s.season.objectives:[{id:'minutes',name:'??????',progress:Math.min(100,s.season.appearances*12),reward:'???? +5'},{id:'growth',name:'????2?',progress:Math.min(100,(s.player.ovr-58)*50),reward:'??????'},{id:'health',name:'????8?',progress:Math.min(100,s.season.week*12),reward:'???? +5%'}];this.overlay.sheet('????',`<p class="card-copy">????2?????????????????????</p><div style="height:12px"></div><div class="stack">${goals.map(g=>`<button class="surface-card interactive" data-goal="${g.id}"><div class="card-row"><h3 class="card-title">${g.name}</h3><span class="badge ${g.progress>=100?'green':'blue'}">${g.progress}%</span></div>${metric('???',g.progress,{tone:g.progress>=100?'green':''})}<div class="card-footer"><span class="card-copy">???${g.reward}</span>${icon('check','sm')}</div></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-goal]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{if(!st.season.objectives.some(x=>x.id===btn.dataset.goal)&&st.season.objectives.length<2)st.season.objectives.push(goals.find(x=>x.id===btn.dataset.goal));return st;});this.feedback.emit('goalProgress','???????');this.overlay.close();})});}
  openFacilities(){this.overlay.sheet('???????',`<div class="action-grid">${facilityTile('analytics','????','?5???????????','analytics')}${facilityTile('medical','????','??????????','medical')}${facilityTile('locker','???','??????????','locker')}${facilityTile('trophy','???','?????????','honors')}</div>`,{onMount:el=>el.onclick=e=>{const k=e.target.closest('[data-facility]')?.dataset.facility;if(k==='analytics')this.openAnalytics();if(k==='medical')this.openMedical();if(k==='locker')this.openLocker();if(k==='honors')this.openHonors();}});}
  openGrowth(){const s=this.store.get(),log=s.career.growthLog.slice(-4);this.overlay.sheet('????',`${radarChart(s.player.stats,s.player.previousStats||s.player.stats,s.player.potential)}<div class="grid-2">${Object.entries(s.player.stats).map(([k,v])=>`<div class="surface-card"><div class="card-row"><strong>${ATTR_CN[k]}</strong><span class="badge blue">${Math.floor(v)}</span></div>${metric('??????',(v-Math.floor(v))*100)}</div>`).join('')}</div><div style="height:14px"></div><section class="surface-card"><div class="card-kicker">??4???</div>${log.length?`<div class="timeline">${log.reverse().map(x=>`<div class="timeline-item"><div class="timeline-time">${x.date}</div><div class="timeline-title">${x.source}</div><div class="timeline-copy">${Object.entries(x.changes).filter(([,v])=>v>0).map(([k,v])=>`${ATTR_CN[k]} +${v.toFixed(2)}`).join(' ? ')}</div></div>`).join('')}</div>`:emptyState('???????','???????????????????','growth')}</section>`);}
  openMedical(){const s=this.store.get(),inj=activeInjury(s.injuries);const content=inj?`<section class="surface-card notice-card critical"><div class="card-row"><div><div class="card-kicker">${icon('injury','sm')} ${inj.bodyPart}</div><h3 class="card-title">${inj.type}</h3><p class="card-copy">???${inj.status==='returning'?'???':'???'} ? ??? ${Math.ceil(inj.remainingDays)} ?</p></div><span class="badge red">?? ${inj.relapseRisk}%</span></div>${metric('????',inj.progress,{tone:'green'})}</section><div style="height:12px"></div><div class="grid-3">${treatmentCard('light','????','??????????????')}${treatmentCard('steady','????','???????????')}${treatmentCard('aggressive','????','????????????')}</div>`:`${emptyState('??????','??????????????????????','medical')}<button class="app-button ghost" data-demo-injury>??????</button>`;this.overlay.sheet('????',content,{onMount:el=>{el.querySelectorAll('[data-treatment]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{const i=st.injuries.findIndex(x=>x.id===inj.id);st.injuries[i]=chooseTreatment(st.injuries[i],btn.dataset.treatment);st.career.injuryLog.push({date:st.simulation.date,type:'????',text:btn.dataset.treatment});return st;});this.feedback.emit('recovered','???????');this.overlay.close();});el.querySelector('[data-demo-injury]')?.addEventListener('click',()=>{this.store.set(st=>{st.injuries.push(createInjury({date:st.simulation.date}));return st;});this.feedback.emit('worsened','???????????????');this.overlay.close();});}});}
  openEventCenter(){const s=this.store.get();const list=s.events.pending;this.overlay.sheet('?????',list.length?`<div class="stack">${list.map(e=>`<button class="surface-card interactive" data-event="${e.id}"><div class="card-row"><div class="icon-tile">${icon(eventIcon(e.category))}</div><span class="badge ${e.priority==='important'?'orange':'blue'}">${e.interaction}</span></div><h3 class="card-title">${e.title}</h3><p class="card-copy">${e.location} ? ${e.participants.join('?')}</p></button>`).join('')}</div>`:emptyState('?????','????????????????????????','todo'),{onMount:el=>el.querySelectorAll('[data-event]').forEach(btn=>btn.onclick=()=>this.openEvent(list.find(x=>x.id===btn.dataset.event)))});}
  openEvent(event){
    const interaction=interactionPanel(event);
    const content=`<div class="card-kicker">${icon(eventIcon(event.category),'sm')} ${event.category} ? ${event.createdAt}</div><h3 class="card-title">${event.title}</h3><p class="card-copy">???${event.location}<br>???${event.participants.join('?')}<br><br><b>?????</b>${event.trigger}<br><b>?????</b>${event.conflict}</p><div style="height:12px"></div>${interaction}<div style="height:12px"></div><div class="stack">${event.choices.map(c=>`<button class="surface-card decision-card interactive" data-choice="${c.id}"><div class="card-row"><strong>${c.label}</strong>${icon('chevron','sm')}</div><p class="card-copy">${c.hint}</p></button>`).join('')}</div>`;
    this.overlay.sheet(event.title,content,{onMount:el=>el.querySelectorAll('[data-choice]').forEach(btn=>btn.onclick=()=>this.resolveEvent(event,btn.dataset.choice))});
  }
  resolveEvent(event,choiceId){let result;this.store.set(s=>{result=this.events.resolve(s,event.id,choiceId);this.applyEffectsToState(s,result.effects,`???${result.title}`);return s;});this.feedback.emit(event.interaction==='dice'?'diceResult':event.interaction==='wheel'?'wheelResult':event.interaction==='flip'?'cardFlip':'select',result.choiceLabel);this.overlay.sheet('????',resultPanel(result),{onMount:el=>{el.querySelector('[data-result-back]')?.addEventListener('click',()=>this.overlay.close());el.querySelector('[data-result-next]')?.addEventListener('click',()=>{const next=this.store.get().events.pending[0];next?this.openEvent(next):this.overlay.close();});el.querySelector('[data-result-continue]')?.addEventListener('click',()=>{this.overlay.close();this.openSimulation();});}});}
  applyEffectsToState(s,effects,source){if(!s.player)return;const gains={};for(const k of Object.keys(ATTR_CN))if(effects[k])gains[k]=effects[k];if(Object.keys(gains).length){const out=applyGrowthToState(s,gains,{source,fatigue:s.player.fatigue,injured:!!activeInjury(s.injuries),facility:76,coachQuality:74});if(out.breakthroughs.length)setTimeout(()=>this.feedback.emit('attributeUp',out.breakthroughs.map(k=>ATTR_CN[k]).join('?')),0);}
    s.player.fatigue=clamp(s.player.fatigue+Number(effects.fatigue||0),0,100);s.player.fitness=clamp(100-s.player.fatigue*.7,10,100);s.player.morale=clamp(s.player.morale+Number(effects.morale||0),0,100);s.player.coachTrust=clamp(s.player.coachTrust+Number(effects.trust||0),0,100);s.relationships.coach=s.player.coachTrust;s.relationships.teammates=clamp(s.relationships.teammates+Number(effects.relationship||0),0,100);s.relationships.rivalry=clamp(s.relationships.rivalry+Number(effects.rivalry||0),0,100);s.relationships.fans=Math.max(0,s.relationships.fans+Number(effects.fans||0));s.relationships.media=clamp(s.relationships.media+Number(effects.media||0),0,100);s.career.marketValue=Math.max(0,s.career.marketValue+Number(effects.marketValue||0));if(effects.trait&&!s.career.achievements.includes(effects.trait)){s.career.achievements.push(effects.trait);setTimeout(()=>this.feedback.emit('newTrait',effects.trait),0);}if(Number(effects.risk||0)>8&&!activeInjury(s.injuries)&&keyedRandom(s.simulation.date,'risk',source).bool(.18))s.injuries.push(createInjury({date:s.simulation.date}));}

  openSimulation(){const s=this.store.get(),actions=['nextEvent','nextMatch','week','month','halfSeason','window','seasonEnd'];const cards=actions.map(a=>{const d=this.simulation.describe(a,s);return `<button class="sim-option" data-sim="${a}"><strong>${d.label}</strong><small>??? ${d.target} ? ?${Math.max(0,d.days)}?<br>?????${d.pause}${d.summary?' ? ????':''}</small></button>`;}).join('');this.overlay.sheet('??????',`<div class="card-row"><div><div class="card-kicker">?? SimulationController</div><h3 class="card-title">${s.simulation.paused?'?????':'?????'}</h3></div><button class="app-button ${s.simulation.paused?'success':'danger'}" data-sim-pause>${icon(s.simulation.paused?'play':'pause','sm')}${s.simulation.paused?'??':'??'}</button></div><div style="height:12px"></div><div class="sim-grid">${cards}</div><div style="height:14px"></div><section class="surface-card"><div class="card-kicker">????</div><div class="choice-grid">${['standard','fast','legend','ultra'].map(m=>`<button class="choice-card ${s.settings.mode===m?'active':''}" data-mode="${m}"><h3>${modeName(m)}</h3><p>${modeCopy(m)}</p></button>`).join('')}</div></section>`,{onMount:el=>{el.querySelector('[data-sim-pause]').onclick=()=>{s.simulation.paused?this.simulation.resume():this.simulation.pause();this.feedback.emit(s.simulation.paused?'resume':'pause');this.overlay.close();};el.querySelectorAll('[data-mode]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{st.settings.mode=btn.dataset.mode;st.simulation.speed={standard:1,fast:2,legend:1,ultra:4}[btn.dataset.mode];return st;});this.feedback.emit('select',modeName(btn.dataset.mode));this.overlay.close();});el.querySelectorAll('[data-sim]').forEach(btn=>btn.onclick=()=>this.runSimulation(btn.dataset.sim));}});}
  async runSimulation(action){this.overlay.close();this.feedback.emit('loading','???????????????');const result=await this.simulation.advance(action);if(result.status==='paused')return this.feedback.emit('pause','??????');if(result.event)this.feedback.emit('newEvent',result.event.title);if(result.match)this.feedback.emit('matchReady',`${result.match.opponent} ? ${result.match.date}`);if(result.processed)this.feedback.emit('seasonSummary',`??? ${result.processed} ???????${result.stopReason}`);}

  openTrainingStrategy(){const s=this.store.get();this.overlay.sheet('??????',`<div class="choice-grid">${[['balanced','????','???????'],['weakness','????','??????'],['strength','????','??????'],['recovery','????','???????']].map(([id,name,copy])=>`<button class="choice-card ${s.training.autoStrategy===id?'active':''}" data-strategy="${id}"><h3>${name}</h3><p>${copy}</p></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-strategy]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{st.training.autoStrategy=btn.dataset.strategy;return st;});this.feedback.emit('trainingSuggested',btn.textContent.trim());this.overlay.close();})});}
  completeTraining(plan){let outcome;this.store.set(s=>{outcome=applyGrowthToState(s,plan.gains,{source:`???${plan.name}`,fatigue:s.player.fatigue,injured:!!activeInjury(s.injuries),facility:78,coachQuality:75});s.player.fatigue=clamp(s.player.fatigue+plan.fatigue,0,100);s.player.fitness=clamp(100-s.player.fatigue*.72,10,100);s.player.coachTrust=clamp(s.player.coachTrust+2,0,100);s.training.completedWeek=s.season.week;s.training.selectedPlan=plan.id;s.training.plansUsed.push({week:s.season.week,plan:plan.id});s.training.lastResult={date:s.simulation.date,plan:plan.id,changes:outcome.changes};if(plan.id==='recovery')s.injuries=s.injuries.map(i=>({...i,remainingDays:Math.max(0,i.remainingDays-2),progress:Math.min(100,i.progress+8)}));if(!s.events.pending.length&&keyedRandom(s.simulation.date,'training',plan.id).bool(.45))this.events.schedule(s,{priority:'normal'});return s;});this.feedback.emit('trainingComplete',plan.name);if(outcome.breakthroughs.length)this.feedback.emit('attributeUp',outcome.breakthroughs.map(k=>ATTR_CN[k]).join('?'));this.overlay.sheet('????',`<div class="result-panel"><div class="card-kicker">${icon('training','sm')} ${plan.name}</div><h3 class="card-title">???????</h3><div class="change-grid">${Object.entries(outcome.changes).filter(([,v])=>v>0).map(([k,v])=>`<div class="change-item"><b>${ATTR_CN[k]} +${v.toFixed(2)}</b><span>????? ${Math.round((1-(this.store.get().player.stats[k]%1))*100)}%</span></div>`).join('')}<div class="change-item"><b>?? ${plan.fatigue>0?'+':''}${plan.fatigue}</b><span>?? ${this.store.get().player.fatigue}</span></div><div class="change-item"><b>???? +2</b><span>????????</span></div></div></div>`);}

  playMatch(match,tactic){const s=this.store.get();const seed=new Date(match.date).getUTCDate()+s.player.ovr+s.season.appearances*7;const played=60+(seed%31),rating=Number(clamp(6.1+(s.player.ovr-55)/30+tactic.mods.rating+((seed%7)-3)/10,5.5,9.4).toFixed(1)),goals=(seed%9===0||rating>8.4)?1:0,assists=(seed%7===0||tactic.id==='creative'&&seed%3===0)?1:0,teamGoals=goals+1+(seed%3),oppGoals=seed%3;const timeline=[{time:'12?',title:'???????',copy:'??????????????????'},{time:'41?',title:tactic.id==='creative'?'???????':'????????',copy:'??????????????'},{time:'72?',title:goals?'???????':assists?'??????':'????????',copy:goals?'?????????':assists?'??????????':'??????????'}];let dev;this.store.set(st=>{const gains=tactic.id==='creative'?{passing:.30,dribbling:.16}:tactic.id==='aggressive'?{physical:.22,defending:.18,speed:.12}:{passing:.16,defending:.12,physical:.12};dev=applyGrowthToState(st,gains,{source:'????',fatigue:st.player.fatigue,facility:76,coachQuality:75,injured:!!activeInjury(st.injuries)});st.player.fatigue=clamp(st.player.fatigue+tactic.mods.fatigue,0,100);st.player.fitness=clamp(100-st.player.fatigue*.72,10,100);st.player.morale=clamp(st.player.morale+(teamGoals>=oppGoals?5:-4),0,100);st.player.coachTrust=clamp(st.player.coachTrust+Math.round((rating-6.5)*2),0,100);st.season.appearances++;st.season.goals+=goals;st.season.assists+=assists;st.season.rating=Number(((st.season.rating*(st.season.appearances-1)+rating)/st.season.appearances).toFixed(2));const m=st.schedule.find(x=>x.id===match.id);m.status='played';m.score=`${teamGoals}-${oppGoals}`;m.rating=rating;st.career.marketValue+=Math.round((rating-6)*35000+goals*90000+assists*65000);st.career.history.push({date:st.simulation.date,type:'??',summary:`${st.player.club} ${teamGoals}-${oppGoals} ${match.opponent}`,rating,goals,assists,minutes:played,timeline});return st;});this.feedback.emit('matchEnd',`${teamGoals}-${oppGoals} ? ?? ${rating}`);if(goals)this.feedback.emit('newRecord','??????');this.overlay.sheet('????',matchResultHtml(this.store.get(),match,{teamGoals,oppGoals,rating,goals,assists,played,timeline,dev}),{onMount:el=>{el.querySelector('[data-home]').onclick=()=>{this.overlay.close();this.navigate('career');};el.querySelector('[data-next-match]').onclick=()=>{this.overlay.close();this.runSimulation('nextMatch');};}});}
  openLastMatch(){const last=this.store.get().career.history.filter(x=>x.type==='??').at(-1);if(!last)return;this.overlay.sheet(last.summary,`<div class="timeline">${last.timeline.map(x=>`<div class="timeline-item"><div class="timeline-time">${x.time}</div><div class="timeline-title">${x.title}</div><div class="timeline-copy">${x.copy}</div></div>`).join('')}</div>`);}

  requestAgentReport(){const s=this.store.get(),candidates=CLUBS.filter(c=>c.opportunity>72).slice((s.season.week%5),s.season.week%5+3);this.store.set(st=>{st.transfer.watchlist=[...new Set([...st.transfer.watchlist,...candidates.map(c=>c.id)])];return st;});this.feedback.emit('transferOffer',`?????? ${candidates.map(c=>c.name).join('?')}`);}
  handleClubAction(action,club){if(!club)return;if(action==='compare'){this.store.set(s=>{if(!s.transfer.watchlist.includes(club.id))s.transfer.watchlist.push(club.id);return s;});this.feedback.emit('select',`${club.name} ?????`);}if(action==='trial'){this.feedback.emit('todo',`??${club.name}??????`);}if(action==='contact'){this.store.set(s=>{s.transfer.offers.push({id:`offer-${Date.now()}`,clubId:club.id,status:'inquiry',salary:club.salary,role:club.opportunity>80?'????':'????'});return s;});this.feedback.emit('transferOffer',`${club.name} ???????`);this.openTransferOffer(club);}}
  openTransferOffer(club){this.overlay.sheet(`${club.name} ? ?????`,`<section class="surface-card"><div class="card-kicker">${icon('contract','sm')} ?????</div><h3 class="card-title">${club.salary} ? ${club.opportunity>80?'????':'????'}</h3><p class="card-copy">?? ${club.academy} ? ???? ${club.competition} ? ?? ${club.style}</p></section><div style="height:12px"></div><div class="grid-2">${['????','??','??????','??','????','????'].map((x,i)=>`<button class="app-button ${i===0?'primary':'ghost'}" data-offer="${x}">${x}</button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-offer]').forEach(btn=>btn.onclick=()=>{const action=btn.dataset.offer;if(action==='??')this.feedback.emit('counterOffer','????????????');else if(action==='??')this.feedback.emit('failure','???????');else this.feedback.emit('negotiation',action);this.overlay.close();})});}

  openAnalytics(){const s=this.store.get(),matches=s.career.history.filter(x=>x.type==='??').slice(-5);this.overlay.sheet('????',`<div class="grid-2">${summaryCard('analytics','?5???',matches.length?`<div class="stat-value">${(matches.reduce((a,b)=>a+b.rating,0)/matches.length).toFixed(2)}</div><p class="card-copy">${matches.map(x=>x.rating).join(' ? ')}</p>`:emptyState('????','??????????'))}${summaryCard('growth','???????',`<div class="stat-value">${s.career.growthLog.length}</div><p class="card-copy">???? ? ?? OVR ${s.player.ovr}</p>`)}</div><div style="height:14px"></div>${radarChart(s.player.stats,s.player.previousStats||s.player.stats,s.player.potential)}<section class="surface-card"><div class="card-kicker">????</div>${metric(s.player.position,Math.min(96,55+s.player.ovr*.45))}${metric('????',s.player.coachTrust,{tone:'green'})}${metric('?????',100-s.player.fatigue,{tone:'orange'})}</section>`);}
  openLocker(){const s=this.store.get();this.overlay.sheet('???',`<div class="grid-2">${relationCard('coach','???',s.relationships.coach,'???????')}${relationCard('teammate','??',s.relationships.teammates,'?????????')}${relationCard('fans','??',Math.min(100,s.relationships.fans/30),'??????')}${relationCard('risk','????',s.relationships.rivalry,'?????')}</div><div style="height:14px"></div><div class="choice-grid">${[['????','?? +2'],['????','?? +3'],['????','?? +2 / ?? +4']].map(([a,b])=>`<button class="choice-card" data-locker="${a}"><h3>${a}</h3><p>${b}</p></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-locker]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{if(btn.dataset.locker==='????')st.relationships.teammates=clamp(st.relationships.teammates+2,0,100);if(btn.dataset.locker==='????')st.player.morale=clamp(st.player.morale+3,0,100);if(btn.dataset.locker==='????'){st.player.coachTrust=clamp(st.player.coachTrust+2,0,100);st.player.fatigue=clamp(st.player.fatigue+4,0,100);}return st;});this.feedback.emit('teammateRelation',btn.dataset.locker);this.overlay.close();})});}
  openHonors(){const s=this.store.get();this.overlay.sheet('???',s.career.achievements.length?`<div class="grid-2">${s.career.achievements.map(a=>`<div class="surface-card"><div class="icon-tile">${icon('trophy')}</div><h3 class="card-title">${a}</h3><p class="card-copy">?????</p></div>`).join('')}</div>`:emptyState('????????????','???????????????????????????','trophy'));}
  openLeaderboard(){const s=this.store.get();const rows=[['?',s.player.ovr,s.season.goals,s.season.assists],['???? A',72,8,5],['???? B',69,4,9],['???? C',67,7,3]];this.overlay.sheet('?????',`<div class="stack">${rows.sort((a,b)=>b[1]-a[1]).map((r,i)=>`<div class="surface-card"><div class="card-row"><div class="card-row" style="justify-content:flex-start"><span class="badge ${i===0?'gold':'blue'}">#${i+1}</span><strong>${r[0]}</strong></div><span>OVR ${r[1]}</span></div><p class="card-copy">${r[2]}? ? ${r[3]}??</p></div>`).join('')}</div>`);}
  openCareerHub(){const s=this.store.get();this.overlay.sheet('????',`<div class="action-grid">${facilityTile('calendar','????',`${s.season.appearances}? ? ${s.season.goals}?`,'summary')}${facilityTile('teammate','??','????????','relations')}${facilityTile('trophy','??',`${s.career.achievements.length}????`,'honors')}${facilityTile('save','????','????????','save')}</div><div style="height:14px"></div><button class="app-button danger" data-retire>????</button>`,{onMount:el=>{el.onclick=e=>{const k=e.target.closest('[data-facility]')?.dataset.facility;if(k==='relations')this.openLocker();if(k==='honors')this.openHonors();if(k==='save')this.openSettings();if(k==='summary')this.feedback.emit('seasonSummary',`${s.season.appearances}???`);if(e.target.closest('[data-retire]'))this.overlay.dialog('??????','<p class="card-copy">??????????????????</p><button class="app-button danger" data-confirm-retire>????</button>').querySelector('[data-confirm-retire]').onclick=()=>{this.feedback.emit('careerEnd','????????');this.overlay.close();};};}});}
  openContract(){const s=this.store.get();this.overlay.sheet('????',`<section class="surface-card"><div class="card-kicker">${icon('contract','sm')} ${s.player.club}</div><h3 class="card-title">?? ?${s.career.weeklySalary}</h3><p class="card-copy">?? ${s.career.contractMonths} ?? ? ???? ?${Math.round(s.career.marketValue/1000)}K</p>${statGrid([['??','?????'],['????','??'],['??','???'],['???','???']])}</section><div style="height:12px"></div><button class="app-button primary" data-renew>??????</button>`,{onMount:el=>el.querySelector('[data-renew]').onclick=()=>{this.feedback.emit('negotiation','??????????');this.overlay.close();}});}
  openSettings(){const s=this.store.get();this.overlay.sheet('?????',`<div class="stack"><section class="surface-card"><div class="card-kicker">????</div>${settingToggle('sound','??',s.settings.sound)}${settingToggle('haptics','????',s.settings.haptics)}${settingToggle('autoSkipLow','?????????',s.settings.autoSkipLow)}${settingToggle('autoPauseCritical','????????',s.settings.autoPauseCritical)}</section><section class="surface-card"><div class="card-kicker">????</div><div class="card-row" style="margin-top:12px"><button class="app-button ghost" data-export>????</button><label class="app-button ghost">????<input type="file" data-import accept="application/json" hidden></label><button class="app-button danger" data-reset>??</button></div></section></div>`,{onMount:el=>{el.querySelectorAll('[data-setting]').forEach(x=>x.onchange=()=>this.store.set(st=>{st.settings[x.dataset.setting]=x.checked;return st;}));el.querySelector('[data-export]').onclick=()=>{const blob=new Blob([this.store.export()],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='football-career-save.json';a.click();URL.revokeObjectURL(a.href);this.feedback.emit('save','???????');};el.querySelector('[data-import]').onchange=async e=>{try{this.store.import(await e.target.files[0].text());this.feedback.emit('save','?????');this.overlay.close();}catch{this.feedback.emit('saveConflict','??????');}};el.querySelector('[data-reset]').onclick=()=>{if(confirm('???????????')){this.store.reset();this.overlay.close();this.mount();}};}});}
}

function summaryCard(iconName,title,body){return `<section class="surface-card"><div class="card-kicker">${icon(iconName,'sm')} ${title}</div><div style="height:10px"></div>${body}</section>`;}
function facilityTile(iconName,title,copy,key){return `<button class="action-tile" data-facility="${key}"><div class="icon-tile">${icon(iconName)}</div><h3>${title}</h3><p>${copy}</p></button>`;}
function treatmentCard(id,title,copy){return `<button class="surface-card interactive" data-treatment="${id}"><div class="icon-tile">${icon(id==='aggressive'?'fast':id==='light'?'recovery':'medical')}</div><h3 class="card-title">${title}</h3><p class="card-copy">${copy}</p></button>`;}
function relationCard(iconName,title,value,copy){return `<section class="surface-card"><div class="card-row"><div class="icon-tile">${icon(iconName)}</div><span class="badge blue">${Math.round(value)}</span></div><h3 class="card-title">${title}</h3><p class="card-copy">${copy}</p>${metric('??',value,{tone:value>65?'green':value<35?'red':''})}</section>`;}
function eventIcon(category){return {'训练':'training','关系':'teammate','媒体':'media','医疗':'medical','转会':'transfer','比赛':'match','合同':'contract','生活':'fans','成长':'growth','重大剧情':'risk'}[category]||'message';}
function interactionPanel(e){const list=`<div class="surface-card" style="box-shadow:none;background:rgba(91,108,135,.05)"><div class="card-kicker">?????</div><div class="timeline">${e.observations.map((x,i)=>`<div class="timeline-item"><div class="timeline-time">?? ${i+1}</div><div class="timeline-copy">${x}</div></div>`).join('')}</div></div>`;const special={dice:`<div class="result-panel"><b>????</b><p class="card-copy">?????????????????????</p></div>`,wheel:`<div class="result-panel"><b>????</b><p class="card-copy">????????????????</p></div>`,risk:`<div class="result-panel"><b>????</b><input type="range" min="0" max="100" value="45" style="width:100%"><p class="card-copy">?????????????????</p></div>`,tactics:`<div class="pitch" style="aspect-ratio:2.2"><span class="position-node active" style="left:52%;top:54%">?</span><span class="position-node" style="left:72%;top:26%">??</span></div>`,negotiation:`<div class="result-panel"><b>????</b><div class="tag-row"><span class="badge blue">??</span><span class="badge green">??</span><span class="badge orange">??</span><span class="badge purple">???</span></div></div>`,flip:`<div class="result-panel"><b>?????</b><p class="card-copy">????????????????</p></div>`,interview:`<div class="result-panel"><b>????</b><p class="card-copy">??????????????????????</p></div>`,timeline:`<div class="timeline"><div class="timeline-item"><div class="timeline-title">????</div></div><div class="timeline-item"><div class="timeline-title">????</div></div><div class="timeline-item"><div class="timeline-title">????</div></div></div>`,envelope:`<div class="result-panel"><b>???????</b><p class="card-copy">?????????????????</p></div>`,sequence:`<div class="result-panel"><b>????</b><p class="card-copy">??????????????????</p></div>`,balance:`<div class="result-panel"><b>????</b><p class="card-copy">?????????????????</p></div>`,keymoment:`<div class="pitch" style="aspect-ratio:2.2"><span class="position-node active" style="left:54%;top:48%">??</span><span class="position-node" style="left:76%;top:32%">??</span></div>`,unlock:`<div class="result-panel"><b>????</b><p class="card-copy">????????????????????????</p></div>`,branch:`<div class="result-panel"><b>?????</b><p class="card-copy">????????????????????????</p></div>`,observation:list,rhythm:`<div class="result-panel"><b>??????</b><p class="card-copy">??????????????????</p></div>`};return special[e.interaction]||list;}
function resultPanel(result){const effects=Object.entries(result.effects||{});return `<div class="result-panel"><div class="card-kicker">${icon('check','sm')} ????</div><h3 class="card-title">${result.choiceLabel}</h3><div class="change-grid">${effects.length?effects.map(([k,v])=>`<div class="change-item"><b>${effectName(k)} ${typeof v==='number'&&v>0?'+':''}${v}</b><span>${effectHint(k)}</span></div>`).join(''):`<div class="change-item"><b>?????</b><span>???????????</span></div>`}</div><div class="card-footer"><span class="card-copy">??????????????????</span></div></div><div class="grid-3" style="margin-top:12px"><button class="app-button ghost" data-result-back>????</button><button class="app-button secondary" data-result-next>????</button><button class="app-button primary" data-result-continue>????</button></div>`;}
function effectName(k){return {...ATTR_CN,fatigue:'??',morale:'??',trust:'????',relationship:'????',fans:'??',media:'????',marketValue:'??',risk:'????',recovery:'????',transferInterest:'????',potential:'??',trait:'???',rivalry:'????'}[k]||k;}
function effectHint(k){return ['speed','shooting','passing','dribbling','defending','physical'].includes(k)?'??????':'??????????';}
function modeName(m){return {standard:'??',fast:'??',legend:'??',ultra:'??'}[m];}
function modeCopy(m){return {standard:'???????????',fast:'??????????????',legend:'????????????',ultra:'?????????????????'}[m];}
function settingToggle(key,label,checked){return `<label class="card-row" style="min-height:54px;border-top:1px solid var(--line)"><span>${label}</span><input type="checkbox" data-setting="${key}" ${checked?'checked':''}></label>`;}
function matchResultHtml(s,match,r){return `<div class="card-row"><div><div class="card-kicker">${match.competition}</div><h3 class="card-title">${s.player.club} ${r.teamGoals}-${r.oppGoals} ${match.opponent}</h3><p class="card-copy">${r.played}?? ? ???? ${r.rating}</p></div><span class="badge ${r.teamGoals>=r.oppGoals?'green':'orange'}">${r.teamGoals>=r.oppGoals?'??':'??'}</span></div><div style="height:12px"></div><div class="grid-2">${summaryCard('analytics','????',statGrid([['??',r.rating],['??',`${r.played}?`],['??',r.goals],['??',r.assists]]))}${summaryCard('match','????',`<p class="card-copy">${r.timeline.at(-1).title}<br>${r.timeline.at(-1).copy}</p>`)}${summaryCard('coach','????',`<p class="card-copy">${r.rating>=7.5?'????????????????????':'????????????????'}</p>`)}${summaryCard('growth','?????',`<p class="card-copy">${Object.entries(r.dev.changes).filter(([,v])=>v>0).map(([k,v])=>`${ATTR_CN[k]} +${v.toFixed(2)}`).join(' ? ')||'????'}</p>`)}</div><div style="height:14px"></div><div class="timeline">${r.timeline.map(x=>`<div class="timeline-item"><div class="timeline-time">${x.time}</div><div class="timeline-title">${x.title}</div><div class="timeline-copy">${x.copy}</div></div>`).join('')}</div><div class="card-row" style="margin-top:15px"><button class="app-button ghost" data-home>??????</button><button class="app-button primary" data-next-match>??????</button></div>`;}

const app=new App();
app.mount();
if('serviceWorker' in navigator) addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
