import { Store } from './core/store.js';
import { EventEngine } from './core/eventEngine.js';
import { SimulationController } from './core/simulationController.js';
import { FeedbackDirector } from './core/feedbackDirector.js';
import { AnimationDirector } from './core/animationDirector.js';
import { applyGrowthToState } from './core/playerDevelopmentEngine.js';
import { createInjury, chooseTreatment, activeInjury } from './core/injuryEngine.js';
import { icon } from './components/icons.js';
import { OverlayManager, playerDetail, metric, statGrid, emptyState } from './components/ui.js';
import { radarChart } from './components/radar.js';
import { keyedRandom } from './services/rng.js';
import { createPlayerWizard } from './pages/createPlayer.js';
import { careerPage } from './pages/career.js';
import { trainingPage } from './pages/training.js';
import { matchPage } from './pages/match.js';
import { transferPage } from './pages/transfer.js';
import { morePage } from './pages/more.js';
import { CLUBS } from './data/clubs.js';
import { dataRepository } from './services/dataRepository.js';
import { createCareerShareCard, ensureHonors, retireCareer, settleSeason } from './systems/honors/honorsSystem.js';
import { applyTheme } from './app/theme.js';
import { worldPage } from './pages/world.js';

const ROUTES={career:['home','生涯'],match:['match','比赛'],training:['training','训练'],transfer:['transfer','转会'],world:['map','世界'],more:['settings','更多']};
const ATTR_CN={speed:'速度',shooting:'射门',passing:'传球',dribbling:'盘带',defending:'防守',physical:'身体'};
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));

class App {
  constructor(){
    this.root=document.querySelector('#app');
    this.overlay=new OverlayManager(document.querySelector('#overlay-root'));
    this.store=new Store();
    this.events=new EventEngine();
    this.simulation=new SimulationController(this.store,this.events);
    this.feedback=new FeedbackDirector(document.body);
    this.animation=new AnimationDirector();
    this.store.subscribe(()=>this.render());
  }
  mount(){
    if(!this.store.get().player){this.root.replaceChildren(createPlayerWizard(this));return;}
    this.root.innerHTML='<div class="app-shell"><div data-topbar></div><main class="app-main" data-page></main><div data-tabbar></div></div>';
    this.render();
    if(!this.store.get().events.pending.length && !this.store.get().events.history.length){this.store.set(s=>{this.events.schedule(s,{priority:'normal'});return s;});}
  }
  render(){
    applyTheme(this.store.get().settings.theme);
    const shell=this.root.querySelector('.app-shell');
    if(!this.store.get().player){if(!this.root.querySelector('.wizard-shell'))this.root.replaceChildren(createPlayerWizard(this));return;}
    if(!shell){this.mount();return;}
    const state=this.store.get();
    shell.querySelector('[data-topbar]').innerHTML=this.topbar(state);
    const page=shell.querySelector('[data-page]'); page.replaceChildren(this.page(state));
    shell.querySelector('[data-tabbar]').innerHTML=this.tabbar(state);
    this.bindShell();
  }
  page(state){ return ({career:careerPage,match:matchPage,training:trainingPage,transfer:transferPage,world:worldPage,more:morePage}[state.route]||careerPage)(this,state); }
  topbar(state){const p=state.player;return `<header class="app-topbar"><div class="identity"><div class="avatar">${p.number}</div><div class="identity-copy"><div class="identity-name">${p.name}</div><div class="identity-meta">${p.club} · ${p.age}岁 · €${Math.round(state.career.marketValue/1000)}K</div></div></div><div class="top-actions"><button class="icon-button ${state.simulation.paused?'active':''}" data-top-pause aria-label="${state.simulation.paused?'继续':'暂停'}">${icon(state.simulation.paused?'play':'pause')}</button><button class="app-button ghost" data-top-speed>${icon('fast','sm')}${state.simulation.paused?'暂停':`${state.simulation.speed}×`}</button><button class="icon-button top-save" data-top-save aria-label="保存">${icon('save')}</button></div></header>`;}
  tabbar(state){return `<nav class="glass-tabbar" aria-label="主导航">${Object.entries(ROUTES).map(([key,[ico,label]])=>`<button class="tab-item ${state.route===key?'active':''}" data-route="${key}">${icon(ico)}<span class="tab-label">${label}</span></button>`).join('')}</nav>`;}
  bindShell(){
    this.root.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>this.navigate(el.dataset.route));
    this.root.querySelector('[data-top-pause]')?.addEventListener('click',()=>{const paused=this.store.get().simulation.paused;paused?this.simulation.resume():this.simulation.pause();this.feedback.emit(paused?'resume':'pause',paused?'日期与结算继续':'日期、比赛、事件与动画队列已停止');});
    this.root.querySelector('[data-top-speed]')?.addEventListener('click',()=>this.openSimulation());
    this.root.querySelector('[data-top-save]')?.addEventListener('click',()=>{this.store.save();this.feedback.emit('save','本地存档已更新');});
  }
  navigate(route){this.overlay.close();this.store.set(s=>{s.route=route;return s;});window.scrollTo({top:0,behavior:'smooth'});}

  openPlayerDetail(){const s=this.store.get();this.overlay.sheet('球员详情',playerDetail(s.player,s));}
  openCareerData(){const s=this.store.get(),next=s.schedule.find(m=>m.status==='upcoming');this.overlay.sheet('职业数据详情',`<div class="grid-2">${summaryCard('calendar','当前赛季',statGrid([['出场',s.season.appearances],['进球',s.season.goals],['助攻',s.season.assists],['评分',s.season.rating||'—']]))}${summaryCard('record','生涯状态',statGrid([['OVR',s.player.ovr],['潜力',Math.round(s.player.potential)],['身价',`€${Math.round(s.career.marketValue/1000)}K`],['合同',`${s.career.contractMonths}月`]]))}</div><div style="height:14px"></div><section class="surface-card"><div class="card-kicker">下一场赛程</div>${next?`<h3 class="card-title">${next.competition} · ${next.opponent}</h3><p class="card-copy">${next.date} · ${next.venue}</p>`:emptyState('暂无赛程','推进到下一赛季后会生成新赛程。')}</section>`);}
  openGoals(){const s=this.store.get();const goals=s.season.objectives.length?s.season.objectives:[{id:'minutes',name:'获得稳定出场',progress:Math.min(100,s.season.appearances*12),reward:'教练信任 +5'},{id:'growth',name:'总评提升2点',progress:Math.min(100,(s.player.ovr-58)*50),reward:'解锁专项路线'},{id:'health',name:'保持健康8周',progress:Math.min(100,s.season.week*12),reward:'恢复效率 +5%'}];this.overlay.sheet('赛季目标',`<p class="card-copy">最多选择2项阶段重点，目标会影响训练建议与事件权重。</p><div style="height:12px"></div><div class="stack">${goals.map(g=>`<button class="surface-card interactive" data-goal="${g.id}"><div class="card-row"><h3 class="card-title">${g.name}</h3><span class="badge ${g.progress>=100?'green':'blue'}">${g.progress}%</span></div>${metric('完成度',g.progress,{tone:g.progress>=100?'green':''})}<div class="card-footer"><span class="card-copy">奖励：${g.reward}</span>${icon('check','sm')}</div></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-goal]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{if(!st.season.objectives.some(x=>x.id===btn.dataset.goal)&&st.season.objectives.length<2)st.season.objectives.push(goals.find(x=>x.id===btn.dataset.goal));return st;});this.feedback.emit('goalProgress','阶段重点已更新');this.overlay.close();})});}
  openFacilities(){this.overlay.sheet('数据与设施中心',`<div class="action-grid">${facilityTile('analytics','数据分析','近5场、能力趋势与训练收益','analytics')}${facilityTile('medical','医疗中心','伤病、恢复和身体风险','medical')}${facilityTile('locker','更衣室','关系、气氛与首发竞争','locker')}${facilityTile('trophy','荣誉室','奖杯、纪录与里程碑','honors')}</div>`,{onMount:el=>el.onclick=e=>{const k=e.target.closest('[data-facility]')?.dataset.facility;if(k==='analytics')this.openAnalytics();if(k==='medical')this.openMedical();if(k==='locker')this.openLocker();if(k==='honors')this.openHonors();}});}
  openGrowth(){const s=this.store.get(),log=s.career.growthLog.slice(-4);this.overlay.sheet('成长中心',`${radarChart(s.player.stats,s.player.previousStats||s.player.stats,s.player.potential)}<div class="grid-2">${Object.entries(s.player.stats).map(([k,v])=>`<div class="surface-card"><div class="card-row"><strong>${ATTR_CN[k]}</strong><span class="badge blue">${Math.floor(v)}</span></div>${metric('下一个属性点',(v-Math.floor(v))*100)}</div>`).join('')}</div><div style="height:14px"></div><section class="surface-card"><div class="card-kicker">最近4次成长</div>${log.length?`<div class="timeline">${log.reverse().map(x=>`<div class="timeline-item"><div class="timeline-time">${x.date}</div><div class="timeline-title">${x.source}</div><div class="timeline-copy">${Object.entries(x.changes).filter(([,v])=>v>0).map(([k,v])=>`${ATTR_CN[k]} +${v.toFixed(2)}`).join(' · ')}</div></div>`).join('')}</div>`:emptyState('还没有成长记录','完成训练、比赛或成长事件后会记录变化。','growth')}</section>`);}
  openMedical(){const s=this.store.get(),inj=activeInjury(s.injuries);const content=inj?`<section class="surface-card notice-card critical"><div class="card-row"><div><div class="card-kicker">${icon('injury','sm')} ${inj.bodyPart}</div><h3 class="card-title">${inj.type}</h3><p class="card-copy">状态：${inj.status==='returning'?'恢复期':'治疗中'} · 剩余约 ${Math.ceil(inj.remainingDays)} 天</p></div><span class="badge red">复发 ${inj.relapseRisk}%</span></div>${metric('恢复进度',inj.progress,{tone:'green'})}</section><div style="height:12px"></div><div class="grid-3">${treatmentCard('light','轻量恢复','训练保守，恢复较慢，风险较低')}${treatmentCard('steady','稳妥治疗','平衡恢复速度与复发风险')}${treatmentCard('aggressive','激进复出','恢复更快，但复发风险上升')}</div>`:`${emptyState('当前没有伤病','医疗中心会持续追踪疲劳、旧伤风险与恢复记录。','medical')}<button class="app-button ghost" data-demo-injury>生成测试伤病</button>`;this.overlay.sheet('医疗中心',content,{onMount:el=>{el.querySelectorAll('[data-treatment]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{const i=st.injuries.findIndex(x=>x.id===inj.id);st.injuries[i]=chooseTreatment(st.injuries[i],btn.dataset.treatment);st.career.injuryLog.push({date:st.simulation.date,type:'治疗路线',text:btn.dataset.treatment});return st;});this.feedback.emit('recovered','治疗路线已更新');this.overlay.close();});el.querySelector('[data-demo-injury]')?.addEventListener('click',()=>{this.store.set(st=>{st.injuries.push(createInjury({date:st.simulation.date}));return st;});this.feedback.emit('worsened','已创建一项轻伤用于体验恢复系统');this.overlay.close();});}});}
  openEventCenter(){const s=this.store.get();const list=s.events.pending;this.overlay.sheet('事件与待办',list.length?`<div class="stack">${list.map(e=>`<button class="surface-card interactive" data-event="${e.id}"><div class="card-row"><div class="icon-tile">${icon(eventIcon(e.category))}</div><span class="badge ${e.priority==='important'?'orange':'blue'}">${e.interaction}</span></div><h3 class="card-title">${e.title}</h3><p class="card-copy">${e.location} · ${e.participants.join('、')}</p></button>`).join('')}</div>`:emptyState('待办已清空','普通通知会进入消息中心，只有关键事件会中断推进。','todo'),{onMount:el=>el.querySelectorAll('[data-event]').forEach(btn=>btn.onclick=()=>this.openEvent(list.find(x=>x.id===btn.dataset.event)))});}
  openEvent(event){
    const interaction=interactionPanel(event);
    const content=`<div class="card-kicker">${icon(eventIcon(event.category),'sm')} ${event.category} · ${event.createdAt}</div><h3 class="card-title">${event.title}</h3><p class="card-copy">地点：${event.location}<br>参与：${event.participants.join('、')}<br><br><b>触发原因：</b>${event.trigger}<br><b>当前冲突：</b>${event.conflict}</p><div style="height:12px"></div>${interaction}<div style="height:12px"></div><div class="stack">${event.choices.map(c=>`<button class="surface-card decision-card interactive" data-choice="${c.id}"><div class="card-row"><strong>${c.label}</strong>${icon('chevron','sm')}</div><p class="card-copy">${c.hint}</p></button>`).join('')}</div>`;
    this.overlay.sheet(event.title,content,{onMount:el=>el.querySelectorAll('[data-choice]').forEach(btn=>btn.onclick=()=>this.resolveEvent(event,btn.dataset.choice))});
  }
  resolveEvent(event,choiceId){let result;this.store.set(s=>{result=this.events.resolve(s,event.id,choiceId);this.applyEffectsToState(s,result.effects,`事件：${result.title}`);return s;});this.feedback.emit(event.interaction==='dice'?'diceResult':event.interaction==='wheel'?'wheelResult':event.interaction==='flip'?'cardFlip':'select',result.choiceLabel);this.overlay.sheet('事件结果',resultPanel(result),{onMount:el=>{el.querySelector('[data-result-back]')?.addEventListener('click',()=>this.overlay.close());el.querySelector('[data-result-next]')?.addEventListener('click',()=>{const next=this.store.get().events.pending[0];next?this.openEvent(next):this.overlay.close();});el.querySelector('[data-result-continue]')?.addEventListener('click',()=>{this.overlay.close();this.openSimulation();});}});}
  applyEffectsToState(s,effects,source){if(!s.player)return;const gains={};for(const k of [...Object.keys(ATTR_CN),'potential'])if(effects[k])gains[k]=effects[k];if(Object.keys(gains).length){const out=applyGrowthToState(s,gains,{source,fatigue:s.player.fatigue,injured:!!activeInjury(s.injuries),facility:76,coachQuality:74});if(out.breakthroughs.length)setTimeout(()=>this.feedback.emit('attributeUp',out.breakthroughs.map(k=>ATTR_CN[k]).join('、')),0);}
    s.player.fatigue=clamp(s.player.fatigue+Number(effects.fatigue||0),0,100);s.player.fitness=clamp(100-s.player.fatigue*.7,10,100);s.player.morale=clamp(s.player.morale+Number(effects.morale||0),0,100);s.player.coachTrust=clamp(s.player.coachTrust+Number(effects.trust||0),0,100);s.relationships.coach=s.player.coachTrust;s.relationships.teammates=clamp(s.relationships.teammates+Number(effects.relationship||0),0,100);s.relationships.rivalry=clamp(s.relationships.rivalry+Number(effects.rivalry||0),0,100);s.relationships.fans=Math.max(0,s.relationships.fans+Number(effects.fans||0));s.relationships.media=clamp(s.relationships.media+Number(effects.media||0),0,100);s.career.marketValue=Math.max(0,s.career.marketValue+Number(effects.marketValue||0));if(effects.trait&&!s.career.achievements.includes(effects.trait)){s.career.achievements.push(effects.trait);setTimeout(()=>this.feedback.emit('newTrait',effects.trait),0);}if(Number(effects.risk||0)>8&&!activeInjury(s.injuries)&&keyedRandom(s.simulation.date,'event-injury',s.events.history.length).bool(.18))s.injuries.push(createInjury({date:s.simulation.date,rng:keyedRandom(s.simulation.date,'event-injury-detail',s.events.history.length)}));}

  openSimulation(){const s=this.store.get(),actions=['nextEvent','nextMatch','week','month','halfSeason','window','seasonEnd'];const cards=actions.map(a=>{const d=this.simulation.describe(a,s);return `<button class="sim-option" data-sim="${a}"><strong>${d.label}</strong><small>推进至 ${d.target} · 约${Math.max(0,d.days)}天<br>停止条件：${d.pause}${d.summary?' · 生成总结':''}</small></button>`;}).join('');this.overlay.sheet('时间推进控制',`<div class="card-row"><div><div class="card-kicker">统一 SimulationController</div><h3 class="card-title">${s.simulation.paused?'当前已暂停':'当前可推进'}</h3></div><button class="app-button ${s.simulation.paused?'success':'danger'}" data-sim-pause>${icon(s.simulation.paused?'play':'pause','sm')}${s.simulation.paused?'继续':'暂停'}</button></div><div style="height:12px"></div><div class="sim-grid">${cards}</div><div style="height:14px"></div><section class="surface-card"><div class="card-kicker">模式差异</div><div class="choice-grid">${['standard','fast','legend','ultra'].map(m=>`<button class="choice-card ${s.settings.mode===m?'active':''}" data-mode="${m}"><h3>${modeName(m)}</h3><p>${modeCopy(m)}</p></button>`).join('')}</div></section>`,{onMount:el=>{el.querySelector('[data-sim-pause]').onclick=()=>{s.simulation.paused?this.simulation.resume():this.simulation.pause();this.feedback.emit(s.simulation.paused?'resume':'pause');this.overlay.close();};el.querySelectorAll('[data-mode]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{st.settings.mode=btn.dataset.mode;st.simulation.speed={standard:1,fast:2,legend:1,ultra:4}[btn.dataset.mode];return st;});this.feedback.emit('select',modeName(btn.dataset.mode));this.overlay.close();});el.querySelectorAll('[data-sim]').forEach(btn=>btn.onclick=()=>this.runSimulation(btn.dataset.sim));}});}
  async runSimulation(action){this.overlay.close();this.feedback.emit('loading','正在结算日期、训练、伤病与赛程');const result=await this.simulation.advance(action);if(result.status==='paused')return this.feedback.emit('pause','请先恢复推进');if(action==='seasonEnd'&&result.stopReason==='target'&&result.processed)this.store.set(state=>{const settled=settleSeason(state);if(settled.trophies.length||settled.personalAwards.length)this.feedback.emit('newRecord',`赛季荣誉 ${settled.trophies.length+settled.personalAwards.length} 项`);return state;});if(result.event)this.feedback.emit('newEvent',result.event.title);if(result.match)this.feedback.emit('matchReady',`${result.match.opponent} · ${result.match.date}`);if(result.processed)this.feedback.emit('seasonSummary',`已推进 ${result.processed} 天，停止原因：${result.stopReason}`);}

  openTrainingStrategy(){const s=this.store.get();this.overlay.sheet('自动训练策略',`<div class="choice-grid">${[['balanced','平衡成长','均衡能力与疲劳'],['weakness','补齐短板','优先最低属性'],['strength','放大优势','强化最高属性'],['recovery','健康优先','伤病与疲劳优先']].map(([id,name,copy])=>`<button class="choice-card ${s.training.autoStrategy===id?'active':''}" data-strategy="${id}"><h3>${name}</h3><p>${copy}</p></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-strategy]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{st.training.autoStrategy=btn.dataset.strategy;return st;});this.feedback.emit('trainingSuggested',btn.textContent.trim());this.overlay.close();})});}
  completeTraining(plan){let outcome;this.store.set(s=>{outcome=applyGrowthToState(s,plan.gains,{source:`训练：${plan.name}`,fatigue:s.player.fatigue,injured:!!activeInjury(s.injuries),facility:78,coachQuality:75});s.player.fatigue=clamp(s.player.fatigue+plan.fatigue,0,100);s.player.fitness=clamp(100-s.player.fatigue*.72,10,100);s.player.coachTrust=clamp(s.player.coachTrust+2,0,100);s.training.completedWeek=s.season.week;s.training.selectedPlan=plan.id;s.training.plansUsed.push({week:s.season.week,plan:plan.id});s.training.lastResult={date:s.simulation.date,plan:plan.id,changes:outcome.changes};if(plan.id==='recovery')s.injuries=s.injuries.map(i=>({...i,remainingDays:Math.max(0,i.remainingDays-2),progress:Math.min(100,i.progress+8)}));if(!s.events.pending.length&&keyedRandom(s.simulation.date,'training-event',s.training.plansUsed.length).bool(.45))this.events.schedule(s,{priority:'normal'});return s;});this.feedback.emit('trainingComplete',plan.name);if(outcome.breakthroughs.length)this.feedback.emit('attributeUp',outcome.breakthroughs.map(k=>ATTR_CN[k]).join('、'));this.overlay.sheet('训练结算',`<div class="result-panel"><div class="card-kicker">${icon('training','sm')} ${plan.name}</div><h3 class="card-title">本周训练已完成</h3><div class="change-grid">${Object.entries(outcome.changes).filter(([,v])=>v>0).map(([k,v])=>`<div class="change-item"><b>${ATTR_CN[k]} +${v.toFixed(2)}</b><span>距离下一点 ${Math.round((1-(this.store.get().player.stats[k]%1))*100)}%</span></div>`).join('')}<div class="change-item"><b>疲劳 ${plan.fatigue>0?'+':''}${plan.fatigue}</b><span>当前 ${this.store.get().player.fatigue}</span></div><div class="change-item"><b>教练信任 +2</b><span>战术适配获得记录</span></div></div></div>`);}

  playMatch(match,tactic){const s=this.store.get();const seed=new Date(match.date).getUTCDate()+s.player.ovr+s.season.appearances*7;const played=60+(seed%31),rating=Number(clamp(6.1+(s.player.ovr-55)/30+tactic.mods.rating+((seed%7)-3)/10,5.5,9.4).toFixed(1)),goals=(seed%9===0||rating>8.4)?1:0,assists=(seed%7===0||tactic.id==='creative'&&seed%3===0)?1:0,teamGoals=goals+1+(seed%3),oppGoals=seed%3;const timeline=[{time:'12′',title:'第一次高位压迫',copy:'迫使对手边后卫回传，教练在场边鼓掌。'},{time:'41′',title:tactic.id==='creative'?'穿透中场的直塞':'稳定完成攻守转换',copy:'你的选择改变了球队推进方向。'},{time:'72′',title:goals?'禁区内完成终结':assists?'送出关键助攻':'完成关键防守回追',copy:goals?'低射穿过门将腋下。':assists?'队友前插后推射得分。':'阻止了对手形成单刀。'}];let dev;this.store.set(st=>{const gains=tactic.id==='creative'?{passing:.30,dribbling:.16}:tactic.id==='aggressive'?{physical:.22,defending:.18,speed:.12}:{passing:.16,defending:.12,physical:.12};dev=applyGrowthToState(st,gains,{source:'比赛表现',fatigue:st.player.fatigue,facility:76,coachQuality:75,injured:!!activeInjury(st.injuries)});st.player.fatigue=clamp(st.player.fatigue+tactic.mods.fatigue,0,100);st.player.fitness=clamp(100-st.player.fatigue*.72,10,100);st.player.morale=clamp(st.player.morale+(teamGoals>=oppGoals?5:-4),0,100);st.player.coachTrust=clamp(st.player.coachTrust+Math.round((rating-6.5)*2),0,100);st.season.appearances++;st.season.goals+=goals;st.season.assists+=assists;st.season.rating=Number(((st.season.rating*(st.season.appearances-1)+rating)/st.season.appearances).toFixed(2));const m=st.schedule.find(x=>x.id===match.id);m.status='played';m.score=`${teamGoals}-${oppGoals}`;m.rating=rating;st.career.marketValue+=Math.round((rating-6)*35000+goals*90000+assists*65000);st.career.history.push({date:st.simulation.date,type:'比赛',summary:`${st.player.club} ${teamGoals}-${oppGoals} ${match.opponent}`,rating,goals,assists,minutes:played,timeline});return st;});this.feedback.emit('matchEnd',`${teamGoals}-${oppGoals} · 评分 ${rating}`);if(goals)this.feedback.emit('newRecord','本场取得进球');this.overlay.sheet('比赛结果',matchResultHtml(this.store.get(),match,{teamGoals,oppGoals,rating,goals,assists,played,timeline,dev}),{onMount:el=>{el.querySelector('[data-home]').onclick=()=>{this.overlay.close();this.navigate('career');};el.querySelector('[data-next-match]').onclick=()=>{this.overlay.close();this.runSimulation('nextMatch');};}});}
  openLastMatch(){const last=this.store.get().career.history.filter(x=>x.type==='比赛').at(-1);if(!last)return;this.overlay.sheet(last.summary,`<div class="timeline">${last.timeline.map(x=>`<div class="timeline-item"><div class="timeline-time">${x.time}</div><div class="timeline-title">${x.title}</div><div class="timeline-copy">${x.copy}</div></div>`).join('')}</div>`);}

  requestAgentReport(){const s=this.store.get(),clubs=dataRepository.clubs?.length?dataRepository.clubs:CLUBS,candidates=clubs.filter(c=>(c.opportunity??0)>72).slice((s.season.week%5),s.season.week%5+3);this.store.set(st=>{st.transfer.watchlist=[...new Set([...st.transfer.watchlist,...candidates.map(c=>c.id)])];return st;});this.feedback.emit('transferOffer',`经纪人筛选了 ${candidates.map(c=>c.name||c.cn).join('、')}`);}
  handleClubAction(action,club){if(!club)return;if(action==='compare'){this.store.set(s=>{if(!s.transfer.watchlist.includes(club.id))s.transfer.watchlist.push(club.id);return s;});this.feedback.emit('select',`${club.name} 已加入比较`);}if(action==='trial'){this.feedback.emit('todo',`已向${club.name}提交试训意向`);}if(action==='contact'){this.store.set(s=>{s.transfer.offers.push({id:`offer-${Date.now()}`,clubId:club.id,status:'inquiry',salary:club.salary,role:club.opportunity>80?'轮换承诺':'竞争位置'});return s;});this.feedback.emit('transferOffer',`${club.name} 已进入沟通阶段`);this.openTransferOffer(club);}}
  openTransferOffer(club){this.overlay.sheet(`${club.name} · 经纪人沟通`,`<section class="surface-card"><div class="card-kicker">${icon('contract','sm')} 非正式方案</div><h3 class="card-title">${club.salary} · ${club.opportunity>80?'轮换承诺':'竞争位置'}</h3><p class="card-copy">青训 ${club.academy} · 阵容竞争 ${club.competition} · 战术 ${club.style}</p></section><div style="height:12px"></div><div class="grid-2">${['接受意向','拒绝','请求更多信息','谈判','请求租借','继续比较'].map((x,i)=>`<button class="app-button ${i===0?'primary':'ghost'}" data-offer="${x}">${x}</button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-offer]').forEach(btn=>btn.onclick=()=>{const action=btn.dataset.offer;if(action==='谈判')this.feedback.emit('counterOffer','已提出首发承诺与奖金要求');else if(action==='拒绝')this.feedback.emit('failure','报价已礼貌拒绝');else this.feedback.emit('negotiation',action);this.overlay.close();})});}

  openAnalytics(){const s=this.store.get(),matches=s.career.history.filter(x=>x.type==='比赛').slice(-5);this.overlay.sheet('数据分析',`<div class="grid-2">${summaryCard('analytics','近5场评分',matches.length?`<div class="stat-value">${(matches.reduce((a,b)=>a+b.rating,0)/matches.length).toFixed(2)}</div><p class="card-copy">${matches.map(x=>x.rating).join(' · ')}</p>`:emptyState('样本不足','完成比赛后生成趋势。'))}${summaryCard('growth','训练投入与收益',`<div class="stat-value">${s.career.growthLog.length}</div><p class="card-copy">成长记录 · 当前 OVR ${s.player.ovr}</p>`)}</div><div style="height:14px"></div>${radarChart(s.player.stats,s.player.previousStats||s.player.stats,s.player.potential)}<section class="surface-card"><div class="card-kicker">位置适配</div>${metric(s.player.position,Math.min(96,55+s.player.ovr*.45))}${metric('战术理解',s.player.coachTrust,{tone:'green'})}${metric('状态稳定性',100-s.player.fatigue,{tone:'orange'})}</section>`);}
  openLocker(){const s=this.store.get();this.overlay.sheet('更衣室',`<div class="grid-2">${relationCard('coach','教练组',s.relationships.coach,'首发与培养方向')}${relationCard('teammate','队友',s.relationships.teammates,'训练搭档与场上默契')}${relationCard('fans','球迷',Math.min(100,s.relationships.fans/30),'支持度与舆论')}${relationCard('risk','竞争压力',s.relationships.rivalry,'同位置竞争')}</div><div style="height:14px"></div><div class="choice-grid">${[['安抚队友','关系 +2'],['参加聚餐','士气 +3'],['邀请加练','信任 +2 / 疲劳 +4']].map(([a,b])=>`<button class="choice-card" data-locker="${a}"><h3>${a}</h3><p>${b}</p></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-locker]').forEach(btn=>btn.onclick=()=>{this.store.set(st=>{if(btn.dataset.locker==='安抚队友')st.relationships.teammates=clamp(st.relationships.teammates+2,0,100);if(btn.dataset.locker==='参加聚餐')st.player.morale=clamp(st.player.morale+3,0,100);if(btn.dataset.locker==='邀请加练'){st.player.coachTrust=clamp(st.player.coachTrust+2,0,100);st.player.fatigue=clamp(st.player.fatigue+4,0,100);}return st;});this.feedback.emit('teammateRelation',btn.dataset.locker);this.overlay.close();})});}
  openHonors(){const s=this.store.get(),honors=ensureHonors(s),items=[...honors.trophies,...honors.personalAwards],seasonRows=honors.seasons.slice(0,8),legend=honors.legendProfile;this.overlay.sheet('荣誉室',`<div class="card-row"><div><div class="card-kicker">奖杯与个人荣誉</div><h3 class="card-title">${items.length} 项荣誉</h3></div><span class="badge gold">${honors.trophies.length} 团队 · ${honors.personalAwards.length} 个人</span></div><div style="height:12px"></div>${legend?`<section class="result-panel"><div class="card-kicker">传奇档案</div><h3 class="card-title">${legend.tier} · ${legend.score}/100</h3><p class="card-copy">退役后生成的生涯评级，仅基于本存档模拟履历。</p></section><div style="height:12px"></div>`:''}${items.length?`<div class="grid-2">${items.map(item=>`<section class="surface-card"><div class="card-row"><div class="icon-tile">${icon('trophy')}</div><span class="badge blue">${item.season}</span></div><h3 class="card-title">${item.name}</h3><p class="card-copy">${item.club} · ${item.category==='team'?'团队奖杯':'个人奖项'} · 游戏模拟结算</p></section>`).join('')}</div>`:emptyState('奖杯柜还在等待第一束灯光','赛季结束后，球队成绩和个人表现会在这里形成可回顾的荣誉记录。','trophy')}<div style="height:14px"></div><section class="surface-card"><div class="card-kicker">逐赛季职业履历</div>${seasonRows.length?`<div class="timeline">${seasonRows.map(row=>`<div class="timeline-item"><div class="timeline-time">${row.year}</div><div class="timeline-title">${row.club} · ${row.appearances} 场 · ${row.goals} 球 · ${row.assists} 助攻</div><div class="timeline-copy">评分 ${row.rating||'—'} · 荣誉 ${row.trophies.length+row.personalAwards.length} 项</div></div>`).join('')}</div>`:'<p class="card-copy">完成第一个赛季后，这里会生成你的职业时间线。</p>'}</section>`);}
  openCareerShare(){const card=createCareerShareCard(this.store.get());const html=`<section class="surface-card share-card"><div class="card-kicker">生涯档案 · ${escapeHtml(card.club)}</div><h2 class="card-title">${escapeHtml(card.player)}</h2><div class="share-card__legend"><strong>${escapeHtml(card.legend.tier)}</strong><span>${card.legend.score}/100</span></div>${statGrid([['出场',card.totals.appearances],['进球',card.totals.goals],['助攻',card.totals.assists],['赛季',card.seasons],['奖杯',card.trophies],['个人荣誉',card.personalAwards]])}<p class="card-copy">${escapeHtml(card.text).replaceAll('\n','<br>')}</p></section><div class="card-row" style="margin-top:14px"><button class="app-button primary" data-copy-share>${icon('save','sm')}复制生涯卡</button><button class="app-button ghost" data-native-share>${icon('share','sm')}系统分享</button></div>`;const overlay=this.overlay.sheet('生涯分享卡',html,{onMount:sheet=>{sheet.querySelector('[data-copy-share]').onclick=async()=>{try{await navigator.clipboard?.writeText(card.text);this.feedback.emit('save','生涯分享卡已复制')}catch{this.feedback.emit('saveConflict','当前浏览器不允许复制，请手动选择文字')}};sheet.querySelector('[data-native-share]').onclick=async()=>{if(!navigator.share)return this.feedback.emit('empty','当前设备不支持系统分享');try{await navigator.share({title:`${card.player}的生涯`,text:card.text})}catch(error){if(error?.name!=='AbortError')this.feedback.emit('networkFail','系统分享未完成')}}}});return overlay;}
  openLeaderboard(){const s=this.store.get();const rows=[['你',s.player.ovr,s.season.goals,s.season.assists],['青年新星 A',72,8,5],['青年新星 B',69,4,9],['青年新星 C',67,7,3]];this.overlay.sheet('生涯排行榜',`<div class="stack">${rows.sort((a,b)=>b[1]-a[1]).map((r,i)=>`<div class="surface-card"><div class="card-row"><div class="card-row" style="justify-content:flex-start"><span class="badge ${i===0?'gold':'blue'}">#${i+1}</span><strong>${r[0]}</strong></div><span>OVR ${r[1]}</span></div><p class="card-copy">${r[2]}球 · ${r[3]}助攻</p></div>`).join('')}</div>`);}
  openCareerHub(){const s=this.store.get();this.overlay.sheet('我的生涯',`<div class="action-grid">${facilityTile('calendar','生涯总结',`${s.season.appearances}场 · ${s.season.goals}球`,'summary')}${facilityTile('teammate','关系','教练、队友与球迷','relations')}${facilityTile('trophy','荣誉室',`${(s.career.honors?.trophies?.length||0)+(s.career.honors?.personalAwards?.length||0)} 项荣誉`,'honors')}${facilityTile('save','存档设置','导入、导出与重置','save')}</div><div style="height:14px"></div><button class="app-button danger" data-retire>提前退役</button>`,{onMount:el=>{el.onclick=e=>{const k=e.target.closest('[data-facility]')?.dataset.facility;if(k==='relations')this.openLocker();if(k==='honors')this.openHonors();if(k==='save')this.openSettings();if(k==='summary')this.feedback.emit('seasonSummary',`${s.season.appearances}场比赛`);if(e.target.closest('[data-retire]'))this.overlay.dialog('确认提前退役','<p class="card-copy">当前存档会保留，可在生涯回顾中查看。</p><button class="app-button danger" data-confirm-retire>确认退役</button>').querySelector('[data-confirm-retire]').onclick=()=>{this.store.set(state=>{retireCareer(state);return state;});this.feedback.emit('careerEnd','生涯进入回顾模式');this.overlay.close();};};}});}
  openContract(){const s=this.store.get();this.overlay.sheet('合同详情',`<section class="surface-card"><div class="card-kicker">${icon('contract','sm')} ${s.player.club}</div><h3 class="card-title">周薪 €${s.career.weeklySalary}</h3><p class="card-copy">剩余 ${s.career.contractMonths} 个月 · 当前身价 €${Math.round(s.career.marketValue/1000)}K</p>${statGrid([['角色','青年队核心'],['出场承诺','竞争'],['奖金','按出场'],['解约金','未设置']])}</section><div style="height:12px"></div><button class="app-button primary" data-renew>请求谈新合同</button>`,{onMount:el=>el.querySelector('[data-renew]').onclick=()=>{this.feedback.emit('negotiation','经纪人已预约体育总监');this.overlay.close();}});}
  openSettings(){const s=this.store.get();this.overlay.sheet('设置与存档',`<div class="stack"><section class="surface-card"><div class="card-kicker">体验设置</div>${settingToggle('sound','音效',s.settings.sound)}${settingToggle('haptics','触控反馈',s.settings.haptics)}${settingToggle('autoSkipLow','自动跳过低优先事件',s.settings.autoSkipLow)}${settingToggle('autoPauseCritical','关键事件自动暂停',s.settings.autoPauseCritical)}</section><section class="surface-card"><div class="card-kicker">存档管理</div><div class="card-row" style="margin-top:12px"><button class="app-button ghost" data-export>导出存档</button><label class="app-button ghost">导入存档<input type="file" data-import accept="application/json" hidden></label><button class="app-button danger" data-reset>重置</button></div></section></div>`,{onMount:el=>{el.querySelectorAll('[data-setting]').forEach(x=>x.onchange=()=>this.store.set(st=>{st.settings[x.dataset.setting]=x.checked;return st;}));el.querySelector('[data-export]').onclick=()=>{const blob=new Blob([this.store.export()],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='football-career-save.json';a.click();URL.revokeObjectURL(a.href);this.feedback.emit('save','存档文件已导出');};el.querySelector('[data-import]').onchange=async e=>{try{this.store.import(await e.target.files[0].text());this.feedback.emit('save','存档已导入');this.overlay.close();}catch{this.feedback.emit('saveConflict','文件无法读取');}};el.querySelector('[data-reset]').onclick=()=>{if(confirm('确定重置全部生涯数据？')){this.store.reset();this.overlay.close();this.mount();}};}});}
}

App.prototype.openThemeSettings=function(){const current=this.store.get().settings.theme;this.overlay.sheet('Appearance',`<div class="choice-grid">${[['system','System'],['dark','Dark'],['light','Light']].map(([id,label])=>`<button class="choice-card ${current===id?'active':''}" data-theme-mode="${id}"><h3>${label}</h3><p>Use the app theme consistently.</p></button>`).join('')}</div>`,{onMount:el=>el.querySelectorAll('[data-theme-mode]').forEach(btn=>btn.onclick=()=>{this.store.set(state=>{state.settings.theme=btn.dataset.themeMode;return state;});applyTheme(btn.dataset.themeMode);this.overlay.close();})});};
function summaryCard(iconName,title,body){return `<section class="surface-card"><div class="card-kicker">${icon(iconName,'sm')} ${title}</div><div style="height:10px"></div>${body}</section>`;}
function facilityTile(iconName,title,copy,key){return `<button class="action-tile" data-facility="${key}"><div class="icon-tile">${icon(iconName)}</div><h3>${title}</h3><p>${copy}</p></button>`;}
function treatmentCard(id,title,copy){return `<button class="surface-card interactive" data-treatment="${id}"><div class="icon-tile">${icon(id==='aggressive'?'fast':id==='light'?'recovery':'medical')}</div><h3 class="card-title">${title}</h3><p class="card-copy">${copy}</p></button>`;}
function relationCard(iconName,title,value,copy){return `<section class="surface-card"><div class="card-row"><div class="icon-tile">${icon(iconName)}</div><span class="badge blue">${Math.round(value)}</span></div><h3 class="card-title">${title}</h3><p class="card-copy">${copy}</p>${metric('状态',value,{tone:value>65?'green':value<35?'red':''})}</section>`;}
function eventIcon(category){return {训练:'training',关系:'teammate',媒体:'media',医疗:'medical',转会:'transfer',比赛:'match',合同:'contract',生活:'fans',成长:'growth','重大剧情':'risk'}[category]||'message';}
function interactionPanel(e){const list=`<div class="surface-card" style="box-shadow:none;background:rgba(91,108,135,.05)"><div class="card-kicker">可观察信息</div><div class="timeline">${e.observations.map((x,i)=>`<div class="timeline-item"><div class="timeline-time">线索 ${i+1}</div><div class="timeline-copy">${x}</div></div>`).join('')}</div></div>`;const special={dice:`<div class="result-panel"><b>骰子判定</b><p class="card-copy">选项会与潜力、士气和当前状态共同决定结果。</p></div>`,wheel:`<div class="result-panel"><b>活动转盘</b><p class="card-copy">随机挑战会改变粉丝、媒体与心态。</p></div>`,risk:`<div class="result-panel"><b>风险滑杆</b><input type="range" min="0" max="100" value="45" style="width:100%"><p class="card-copy">风险越高，短期收益与复发概率越高。</p></div>`,tactics:`<div class="pitch" style="aspect-ratio:2.2"><span class="position-node active" style="left:52%;top:54%">你</span><span class="position-node" style="left:72%;top:26%">空当</span></div>`,negotiation:`<div class="result-panel"><b>合同筹码</b><div class="tag-row"><span class="badge blue">薪资</span><span class="badge green">出场</span><span class="badge orange">奖金</span><span class="badge purple">解约金</span></div></div>`,flip:`<div class="result-panel"><b>两张反扣卡</b><p class="card-copy">选择后会翻开训练内容并立即结算。</p></div>`,interview:`<div class="result-panel"><b>多轮采访</b><p class="card-copy">记者会记住你的措辞，后续问题受本次回答影响。</p></div>`,timeline:`<div class="timeline"><div class="timeline-item"><div class="timeline-title">出场路线</div></div><div class="timeline-item"><div class="timeline-title">荣誉路线</div></div><div class="timeline-item"><div class="timeline-title">商业路线</div></div></div>`,envelope:`<div class="result-panel"><b>神秘信封已拆封</b><p class="card-copy">三家俱乐部的条件不会同时完整公开。</p></div>`,sequence:`<div class="result-panel"><b>顺序安排</b><p class="card-copy">前后顺序会改变训练稳定性和录像评价。</p></div>`,balance:`<div class="result-panel"><b>关系平衡</b><p class="card-copy">帮助一方可能改变另一方对你的看法。</p></div>`,keymoment:`<div class="pitch" style="aspect-ratio:2.2"><span class="position-node active" style="left:54%;top:48%">持球</span><span class="position-node" style="left:76%;top:32%">前锋</span></div>`,unlock:`<div class="result-panel"><b>隐藏条件</b><p class="card-copy">只有部分属性或关系达到要求时，额外选项才会出现。</p></div>`,branch:`<div class="result-panel"><b>分支时间线</b><p class="card-copy">本次选择会在医疗、转会和比赛系统中产生延迟后果。</p></div>`,observation:list,rhythm:`<div class="result-panel"><b>训练节奏互动</b><p class="card-copy">精确、爆发或提前收操将产生不同负荷。</p></div>`};return special[e.interaction]||list;}
function resultPanel(result){const effects=Object.entries(result.effects||{});return `<div class="result-panel"><div class="card-kicker">${icon('check','sm')} 你的选择</div><h3 class="card-title">${result.choiceLabel}</h3><div class="change-grid">${effects.length?effects.map(([k,v])=>`<div class="change-item"><b>${effectName(k)} ${typeof v==='number'&&v>0?'+':''}${v}</b><span>${effectHint(k)}</span></div>`).join(''):`<div class="change-item"><b>状态已记录</b><span>影响会在后续剧情中出现</span></div>`}</div><div class="card-footer"><span class="card-copy">隐藏影响已写入角色记忆与后续事件权重</span></div></div><div class="grid-3" style="margin-top:12px"><button class="app-button ghost" data-result-back>返回页面</button><button class="app-button secondary" data-result-next>下一待办</button><button class="app-button primary" data-result-continue>继续推进</button></div>`;}
function effectName(k){return {...ATTR_CN,fatigue:'疲劳',morale:'士气',trust:'教练信任',relationship:'队友关系',fans:'粉丝',media:'媒体形象',marketValue:'身价',risk:'伤病风险',recovery:'恢复进度',transferInterest:'转会兴趣',potential:'潜力',trait:'新特质',rivalry:'竞争关系'}[k]||k;}
function effectHint(k){return ['speed','shooting','passing','dribbling','defending','physical'].includes(k)?'内部浮点成长':'将影响后续状态与事件';}
function modeName(m){return {standard:'标准',fast:'快速',legend:'传奇',ultra:'极速'}[m];}
function modeCopy(m){return {standard:'平衡事件密度与比赛反馈',fast:'折叠低价值内容，保留关键节点',legend:'更多剧情与高波动职业抉择',ultra:'快速推进，仅危机和关键职业事件暂停'}[m];}
function settingToggle(key,label,checked){return `<label class="card-row" style="min-height:54px;border-top:1px solid var(--line)"><span>${label}</span><input type="checkbox" data-setting="${key}" ${checked?'checked':''}></label>`;}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function matchResultHtml(s,match,r){return `<div class="card-row"><div><div class="card-kicker">${match.competition}</div><h3 class="card-title">${s.player.club} ${r.teamGoals}-${r.oppGoals} ${match.opponent}</h3><p class="card-copy">${r.played}分钟 · 个人评分 ${r.rating}</p></div><span class="badge ${r.teamGoals>=r.oppGoals?'green':'orange'}">${r.teamGoals>=r.oppGoals?'不败':'失利'}</span></div><div style="height:12px"></div><div class="grid-2">${summaryCard('analytics','比赛表现',statGrid([['评分',r.rating],['时间',`${r.played}′`],['进球',r.goals],['助攻',r.assists]]))}${summaryCard('match','关键动作',`<p class="card-copy">${r.timeline.at(-1).title}<br>${r.timeline.at(-1).copy}</p>`)}${summaryCard('coach','教练评价',`<p class="card-copy">${r.rating>=7.5?'很好地执行了战术要求，首发竞争明显升温。':'完成基础任务，仍需提高无球参与。'}</p>`)}${summaryCard('growth','成长与状态',`<p class="card-copy">${Object.entries(r.dev.changes).filter(([,v])=>v>0).map(([k,v])=>`${ATTR_CN[k]} +${v.toFixed(2)}`).join(' · ')||'保持稳定'}</p>`)}</div><div style="height:14px"></div><div class="timeline">${r.timeline.map(x=>`<div class="timeline-item"><div class="timeline-time">${x.time}</div><div class="timeline-title">${x.title}</div><div class="timeline-copy">${x.copy}</div></div>`).join('')}</div><div class="card-row" style="margin-top:15px"><button class="app-button ghost" data-home>返回生涯首页</button><button class="app-button primary" data-next-match>推进到下一场</button></div>`;}

const app=new App();
dataRepository.init().catch(error=>console.warn('world data unavailable, using local fallback',error)).finally(()=>app.mount());
if('serviceWorker' in navigator) addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
