import {DeterministicRng} from '../../services/rng.js';
import {clamp,round} from '../../utils/format.js';
import {performanceFanDelta,applyFanChange} from '../fan/fanSystem.js';
import {applyRelation} from '../relationship/relationshipSystem.js';

const WEATHER=['晴朗','小雨','大雨','低温','炎热','强风'];
const IMPORTANCE=['普通联赛','争四关键战','德比战','杯赛淘汰赛','冠军争夺战'];
const TIMELINE_TYPES=['射门','扑救','抢断','犯规','黄牌','换人','关键传球','VAR','点球','失误'];
const CHOICES={
 attack:[['尝试个人突破','dri','高风险制造机会'],['快速传给空位队友','pas','团队收益稳定'],['直接远射','sho','可能成为英雄'],['保护球等待支援','phy','降低失误'],['回传控制节奏','pas','保存体能']],
 midfield:[['送出直塞','pas','创造高质量机会'],['持球推进','dri','突破中场防线'],['远射试探','sho','结果波动较大'],['控制节奏','pas','提高球队稳定性'],['战术犯规阻止反击','def','有吃牌风险']],
 defense:[['果断上抢','def','成功可发动反击'],['保持站位','def','降低被突破概率'],['身体对抗','phy','强硬但有犯规风险'],['长传解围','pas','迅速解除危险'],['呼叫队友协防','pas','依赖默契']],
 spectator:[['记录对手防线习惯','pas','提高战术理解'],['主动为队友提供观察信息','def','改善团队关系'],['完整热身保持待命','phy','保护体能和职业态度']],
 keeper:[['迅速出击','phy','缩小射门角度'],['留在门线','pac','依赖反应'],['封锁近角','pas','稳定选择'],['用脚挡出','sho','高难度扑救'],['指挥后卫封堵','def','提高整体防守']]
};
function group(pos){if(pos==='GK')return'keeper';if(['CB','LB','RB','CDM'].includes(pos))return'defense';if(['CM','CAM'].includes(pos))return'midfield';return'attack'}
function opponentPool(save,repo){const current=repo.getClub(save.career.clubId);let pool=repo.clubs.filter(c=>c.leagueId===current.leagueId&&c.id!==current.id);if(!pool.length)pool=repo.clubs.filter(c=>Math.abs(c.rep-current.rep)<=8&&c.id!==current.id);return pool}
export function generateMatch(save,repo){
 if(save.career.pending.match)return save.career.pending.match;
 const rng=new DeterministicRng(save.rng.seed,save.rng.state);rng.counter=save.rng.counter||0;const current=repo.getClub(save.career.clubId),opp=rng.pick(opponentPool(save,repo));const home=rng.bool(.52),weather=rng.pick(WEATHER),importance=rng.weighted(IMPORTANCE.map((x,i)=>({x,weight:[48,18,14,12,8][i]})),x=>x.weight).x;
 const youth=save.career.squadLevel!=='一线队';const playerActive=save.career.teamRole!=='未进入名单'&&!save.status.injury&&save.status.suspension<=0;
 const baseChance=clamp((youth?.68:.36)+(save.player.ovr-current.rep)*.018+(save.status.coachTrust-50)*.004,0.12,.94);const starts=playerActive&&rng.bool(baseChance);const substitute=playerActive&&!starts&&rng.bool(.66);const minute=starts?1:substitute?rng.int(55,77):null;
 const choicePool=playerActive?(CHOICES[group(save.player.position)]||CHOICES.midfield):CHOICES.spectator;const keyChoices=rng.shuffle(choicePool).slice(0,rng.int(2,Math.min(5,choicePool.length))).map((x,i)=>({id:`match-choice-${i}`,text:x[0],focus:x[1],hint:x[2]}));
 const match={id:`M-${save.career.season}-${save.career.month}-${rng.state}`,opponentId:opp.id,home,weather,importance,starts,substitute,minute,keyChoices,choice:null,resolved:false,timeline:[],score:null,playerResult:null};save.career.pending.match=match;save.rng=rng.snapshot();return match;
}
function eventMinute(rng,used){let m;do{m=rng.int(3,90)}while(used.has(m));used.add(m);return m}
export function resolveMatch(save,repo,choiceId){
 const match=save.career.pending.match;if(!match||match.resolved)throw new Error('没有待结算比赛');const rng=new DeterministicRng(save.rng.seed,save.rng.state);rng.counter=save.rng.counter||0;const current=repo.getClub(save.career.clubId),opp=repo.getClub(match.opponentId),choice=match.keyChoices.find(x=>x.id===choiceId)||null;const playerActive=save.career.teamRole!=='未进入名单'&&!save.status.injury&&save.status.suspension<=0;match.choice=choice;
 const homeBonus=match.home?2.5:0;const fitness=(save.status.fitness-50)*.04;const morale=(save.status.morale-50)*.03;const teamPower=current.attack*.46+current.defense*.40+current.rep*.14+homeBonus;const oppPower=opp.attack*.46+opp.defense*.40+opp.rep*.14;let teamXg=clamp(1.18+(teamPower-oppPower)*.035+rng.next()*.9,0.2,3.8),oppXg=clamp(1.05+(oppPower-teamPower)*.035+rng.next()*.9,0.2,3.8);
 let contribution=0;if(choice&&playerActive){const skill=save.player.attrs[choice.focus]||60;const chance=clamp(.35+(skill-55)*.009+fitness*.02+morale*.02-(save.status.fatigue*.002),.08,.88);if(rng.bool(chance)){contribution=1;teamXg+=.35}else if(rng.bool(.25)){contribution=-1;oppXg+=.2}}
 const scoreA=Math.min(6,Math.max(0,Math.round(teamXg+(rng.next()-.5)*1.2))),scoreB=Math.min(6,Math.max(0,Math.round(oppXg+(rng.next()-.5)*1.2)));match.score=[scoreA,scoreB];
 const played=match.starts||match.substitute;let goals=0,assists=0,saves=0,tackles=0,keyPasses=0;if(played){const pos=group(save.player.position);if(pos==='attack'){goals=scoreA>0&&rng.bool(clamp((save.player.attrs.sho-45)/80+teamXg*.08,0,.65))?rng.int(1,Math.min(3,scoreA)):0;assists=scoreA>goals&&rng.bool(clamp((save.player.attrs.pas-45)/100,0,.45))?1:0}else if(pos==='midfield'){assists=scoreA>0&&rng.bool(clamp((save.player.attrs.pas-42)/75,0,.7))?rng.int(1,Math.min(2,scoreA)):0;goals=scoreA>assists&&rng.bool(clamp((save.player.attrs.sho-55)/130,0,.28))?1:0;keyPasses=rng.int(1,5)}else if(pos==='defense'){tackles=rng.int(2,7);goals=scoreA>0&&rng.bool(.05)?1:0}else{saves=rng.int(2,8);}}
 if(played&&scoreB===0&&['defense','keeper'].includes(group(save.player.position)))cleanSheets=1;
 const resultBonus=scoreA>scoreB?.35:scoreA===scoreB?.05:-.28;let rating=played?6.15+resultBonus+goals*1.15+assists*.75+saves*.08+tackles*.05+keyPasses*.04+contribution*.35+(rng.next()-.5)*.75:6;rating=clamp(round(rating,1),4.2,10);
 const blockApps=played?rng.int(1,3):(playerActive&&rng.bool(.45)?1:0);let blockGoals=0,blockAssists=0,blockCleanSheets=0;if(blockApps){const grp=group(save.player.position);if(grp==='attack'){blockGoals=Math.max(0,Math.round(blockApps*(save.player.attrs.sho-45)/80+rng.next()*.8));blockAssists=rng.bool((save.player.attrs.pas-45)/100)?1:0}else if(grp==='midfield'){blockAssists=Math.max(0,Math.round(blockApps*(save.player.attrs.pas-45)/90+rng.next()*.7));blockGoals=rng.bool((save.player.attrs.sho-50)/160)?1:0}else if(grp==='defense'){blockCleanSheets=rng.int(0,blockApps)}else{blockCleanSheets=rng.int(0,blockApps)}}
 const timeline=[];const used=new Set();const total=rng.int(7,12);for(let i=0;i<total;i++)timeline.push({minute:eventMinute(rng,used),type:rng.pick(TIMELINE_TYPES),team:rng.bool(.52)?current.cn:opp.cn,text:''});timeline.sort((a,b)=>a.minute-b.minute);if(goals)timeline.push({minute:eventMinute(rng,used),type:'进球',team:current.cn,text:`${save.player.name} 完成进球`});if(assists)timeline.push({minute:eventMinute(rng,used),type:'助攻',team:current.cn,text:`${save.player.name} 送出助攻`});timeline.sort((a,b)=>a.minute-b.minute);match.timeline=timeline;
 match.playerResult={played,starts:match.starts,minutes:played?(match.starts?rng.int(75,90):90-match.minute):0,goals,assists,saves,tackles,keyPasses,rating,background:{apps:blockApps,goals:blockGoals,assists:blockAssists,cleanSheets:blockCleanSheets}};match.resolved=true;
 const ss=save.career.seasonStats,cs=save.career.careerStats;if(played||blockApps){const totalApps=(played?1:0)+blockApps,totalGoals=goals+blockGoals,totalAssists=assists+blockAssists,totalClean=blockCleanSheets;const oldApps=ss.apps;ss.apps+=totalApps;if(match.starts)ss.starts++;ss.starts+=Math.max(0,blockApps-1);ss.minutes+=match.playerResult.minutes+blockApps*rng.int(55,84);ss.goals+=totalGoals;ss.assists+=totalAssists;ss.cleanSheets+=totalClean;ss.saves+=saves;ss.tackles+=tackles;ss.keyPasses+=keyPasses;ss.rating=round(((ss.rating*oldApps)+rating*totalApps)/Math.max(1,ss.apps),2);cs.apps+=totalApps;cs.goals+=totalGoals;cs.assists+=totalAssists;cs.cleanSheets+=totalClean;cs.hatTricks=(cs.hatTricks||0)+(goals>=3?1:0);cs.bigGames=(cs.bigGames||0)+(match.importance!=='普通联赛'&&rating>=7?1:0);cs.saves=(cs.saves||0)+saves;cs.tackles=(cs.tackles||0)+tackles;cs.bestRating=Math.max(cs.bestRating||0,rating);const focus=group(save.player.position)==='attack'?['sho','pac','dri']:group(save.player.position)==='midfield'?['pas','dri','phy']:group(save.player.position)==='defense'?['def','phy','pas']:['pac','sho','pas'];for(const key of focus)save.player.xp[key]=(save.player.xp[key]||0)+Math.max(2,(rating-5.5)*4+totalApps*1.5)}
 save.status.form=clamp(save.status.form+(rating-6.5)*5,0,100);save.status.morale=clamp(save.status.morale+(scoreA>scoreB?4:scoreA<scoreB?-3:1)+(rating-6.5)*2,0,100);save.status.fitness=clamp(save.status.fitness-(played?rng.int(8,17):2),0,100);save.status.fatigue=clamp(save.status.fatigue+(played?rng.int(6,12):1),0,100);save.status.coachTrust=clamp(save.status.coachTrust+(rating-6.4)*3,0,100);applyRelation(save,'coach',{trust:Math.round((rating-6.3)*2),respect:rating>=8?3:0});applyFanChange(save,{...performanceFanDelta({rating,goals,assists,importance:match.importance==='冠军争夺战'?1.7:match.importance==='德比战'?1.35:1,clubRep:current.rep}),reason:`对阵${opp.cn}`});
 const injuryChance=clamp((save.status.fatigue*.003+(100-save.status.fitness)*.002+(save.player.hidden.injuryProne||30)*.0015),0,.38);if(played&&rng.bool(injuryChance)){const severity=round(.12+rng.next()*.45,2);save.status.injury={name:severity>.38?'比赛中肌肉损伤':'轻微碰撞',severity,remainingMatches:severity>.38?rng.int(2,6):1};save.career.history.push({type:'injury',year:save.career.year,title:'比赛伤病',text:save.status.injury.name})}
 save.rng=rng.snapshot();return match;
}
export function consumeMatch(save){if(save.career.pending.match?.resolved)save.career.pending.match=null}
